# Generated by Django 6.0.8 on 2026-08-16 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Configuration",
                "verbose_name_plural": "Dashboard Configurations",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("statistic", "Statistic"),
                            ("chart", "Chart"),
                            ("table", "Table"),
                            ("list", "List"),
                            ("calendar", "Calendar"),
                            ("activity", "Activity Feed"),
                            ("notification", "Notification"),
                            ("quick_actions", "Quick Actions"),
                            ("welcome", "Welcome"),
                            ("profile", "Profile"),
                            ("organizational_info", "Organizational Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Widget-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
            },
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "default_reporting_period",
                    models.CharField(
                        choices=[
                            ("today", "Today"),
                            ("this_week", "This Week"),
                            ("this_month", "This Month"),
                            ("this_quarter", "This Quarter"),
                            ("this_year", "This Year"),
                        ],
                        default="this_month",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_chart_style",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("pie", "Pie"),
                            ("doughnut", "Doughnut"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                (
                    "column_layout",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Number of columns in dashboard layout (1-4)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Dashboard Preference",
                "verbose_name_plural": "User Dashboard Preferences",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Position in dashboard layout (0-based index)"
                    ),
                ),
                (
                    "column_span",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of columns this widget spans (1-4)"
                    ),
                ),
                (
                    "row_span",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of rows this widget spans (1-4)"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Instance-specific widget configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_configurations",
                        to="dashboard.dashboardconfiguration",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboardwidget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget Configuration",
                "verbose_name_plural": "Dashboard Widget Configurations",
                "ordering": ["position"],
                "unique_together": {("dashboard_configuration", "widget", "position")},
            },
        ),
    ]
