# Generated by Django 5.1 on 2026-08-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_userwidgetstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdashboardpreference",
            name="theme",
            field=models.CharField(
                choices=[
                    ("system", "System Default"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
