# Generated by Django 5.1 on 2026-08-01 02:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceNumberScheme",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("memberships", "Memberships"),
                            ("volunteers", "Volunteers"),
                            ("leaders", "Leaders"),
                            ("reports", "Reports"),
                            ("documents", "Documents"),
                            ("programs", "Programs"),
                            ("projects", "Projects"),
                            ("events", "Events"),
                            ("assets", "Assets"),
                            ("finance", "Finance"),
                            ("meetings", "Meetings"),
                            ("grants", "Grants"),
                            ("partners", "Partners"),
                            ("donors", "Donors"),
                            ("beneficiaries", "Beneficiaries"),
                        ],
                        db_index=True,
                        max_length=60,
                        verbose_name="Module",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional narrower type within the module.",
                        max_length=100,
                        verbose_name="Record type",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="Prefix"
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        default="{PREFIX}-{ORG}-{YEAR}-{SEQUENCE}",
                        max_length=250,
                        verbose_name="Pattern",
                    ),
                ),
                (
                    "organization_code",
                    models.CharField(
                        default="SITADC",
                        max_length=20,
                        verbose_name="Organization code",
                    ),
                ),
                (
                    "sequence_length",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Width of the zero-padded sequence token.",
                        verbose_name="Sequence length",
                    ),
                ),
                (
                    "start_value",
                    models.PositiveIntegerField(default=1, verbose_name="Start value"),
                ),
                (
                    "reset_period",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("ANNUALLY", "Annually"),
                            ("MONTHLY", "Monthly"),
                            ("DAILY", "Daily"),
                            ("FISCAL", "Fiscal Year"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="NEVER",
                        max_length=20,
                        verbose_name="Reset period",
                    ),
                ),
                (
                    "fiscal_start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Month the financial year starts (1-12); used when the reset period is Fiscal.",
                        verbose_name="Fiscal start month",
                    ),
                ),
                (
                    "custom_reset_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Interval in days; used when the reset period is Custom.",
                        null=True,
                        verbose_name="Custom reset interval (days)",
                    ),
                ),
                (
                    "is_default_for_module",
                    models.BooleanField(
                        default=False,
                        help_text="Fall back to this scheme when a module has no record-type specific scheme.",
                        verbose_name="Default for module",
                    ),
                ),
                (
                    "is_default_for_record_type",
                    models.BooleanField(
                        default=False,
                        help_text="Use this scheme for the configured module and record type.",
                        verbose_name="Default for record type",
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="Catch-all scheme used when no module scheme matches.",
                        verbose_name="Organizational fallback",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Number Scheme",
                "verbose_name_plural": "Reference Number Schemes",
                "ordering": ("module", "name"),
            },
        ),
        migrations.CreateModel(
            name="GeneratedReferenceNumber",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        help_text="Globally unique, immutable reference number.",
                        max_length=200,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ASSIGNED", "Assigned"),
                            ("CANCELLED", "Cancelled"),
                            ("VOIDED", "Voided"),
                        ],
                        db_index=True,
                        default="RESERVED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Module"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Record type"
                    ),
                ),
                (
                    "record_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="Record ID"
                    ),
                ),
                (
                    "sequence_value",
                    models.PositiveIntegerField(verbose_name="Sequence value"),
                ),
                (
                    "period_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Period key"
                    ),
                ),
                (
                    "tokens_resolved",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resolved tokens"
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Reserved at"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assigned at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled at"
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Voided at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_numbers",
                        to="references.referencenumberscheme",
                        verbose_name="Scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Reference Number",
                "verbose_name_plural": "Generated Reference Numbers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReferenceSequence",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Period key"
                    ),
                ),
                (
                    "start_value",
                    models.PositiveIntegerField(default=1, verbose_name="Start value"),
                ),
                (
                    "current_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current value"
                    ),
                ),
                (
                    "next_value",
                    models.PositiveIntegerField(default=1, verbose_name="Next value"),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="references.referencenumberscheme",
                        verbose_name="Scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Sequence",
                "verbose_name_plural": "Reference Sequences",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ReferenceNumberAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Scheme created"),
                            ("UPDATED", "Scheme updated"),
                            ("ACTIVATED", "Scheme activated"),
                            ("DEACTIVATED", "Scheme deactivated"),
                            ("ARCHIVED", "Scheme archived"),
                            ("RESTORED", "Scheme restored"),
                            ("GENERATED", "Reference generated"),
                            ("RESERVED", "Sequence reserved"),
                            ("CONFIRMED", "Reservation confirmed"),
                            ("ASSIGNED", "Reference assigned"),
                            ("CANCELLED", "Reservation cancelled"),
                            ("VOIDED", "Reference voided"),
                            ("RESET", "Sequence reset"),
                            ("VALIDATION_FAILED", "Validation failed"),
                            ("DUPLICATE_PREVENTED", "Duplicate prevented"),
                            ("CORRECTED", "Manual correction"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reference_audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Number Audit Record",
                "verbose_name_plural": "Reference Number Audit Records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="references__entity__9ae1fe_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="referencenumberscheme",
            index=models.Index(
                fields=["module", "status"], name="references__module_784cff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreferencenumber",
            index=models.Index(
                fields=["scheme", "status"], name="references__scheme__b66ade_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedreferencenumber",
            constraint=models.UniqueConstraint(
                fields=("scheme", "period_key", "sequence_value"),
                name="unique_sequence_value_per_scheme_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencesequence",
            constraint=models.UniqueConstraint(
                fields=("scheme", "period_key"),
                name="unique_reference_sequence_per_period",
            ),
        ),
    ]
