# Generated by Django 5.1 on 2026-08-05 15:52

# ruff: noqa: RUF012 - Django migration attributes are declarative.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0007_seed_beneficiary_record_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencenumberscheme",
            name="module",
            field=models.CharField(
                choices=[
                    ("users", "Users"),
                    ("memberships", "Memberships"),
                    ("volunteers", "Volunteers"),
                    ("leaders", "Leaders"),
                    ("reports", "Reports"),
                    ("documents", "Documents"),
                    ("programs", "Programs"),
                    ("projects", "Projects"),
                    ("events", "Events"),
                    ("assets", "Assets"),
                    ("finance", "Finance"),
                    ("meetings", "Meetings"),
                    ("grants", "Grants"),
                    ("partners", "Partners"),
                    ("donors", "Donors"),
                    ("beneficiaries", "Beneficiaries"),
                    ("meal", "MEAL"),
                ],
                db_index=True,
                max_length=60,
                verbose_name="Module",
            ),
        ),
    ]
