# Generated by Django 5.1 on 2026-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qaconfiguration",
            name="test_execution_schedules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON configuration for test execution schedules.",
                verbose_name="Test Execution Schedules",
            ),
        ),
    ]
