# Generated by Django 5.1 on 2026-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userinvitation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                default="en",
                max_length=10,
                verbose_name="Preferred language",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="time_zone",
            field=models.CharField(
                blank=True,
                default="Africa/Lusaka",
                max_length=100,
                verbose_name="Time zone",
            ),
        ),
    ]
