# Generated by Django 5.1 on 2026-08-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_preferred_language_and_more"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
    ]
