"""Permission constants and helpers for the existing ``partners`` namespace."""

from __future__ import annotations

from apps.rbac.authorization import user_has_permission

from .constants import STAKEHOLDER_ACTION_PERMISSIONS

PARTNERS_VIEW = STAKEHOLDER_ACTION_PERMISSIONS["view"]
PARTNERS_VIEW_DIRECTORY = STAKEHOLDER_ACTION_PERMISSIONS["view_directory"]
PARTNERS_VIEW_PROFILE = STAKEHOLDER_ACTION_PERMISSIONS["view_profile"]
PARTNERS_VIEW_PRIVATE_CONTACTS = STAKEHOLDER_ACTION_PERMISSIONS["view_private_contacts"]
PARTNERS_VIEW_DUE_DILIGENCE = STAKEHOLDER_ACTION_PERMISSIONS["view_due_diligence"]
PARTNERS_VIEW_FINANCIAL = STAKEHOLDER_ACTION_PERMISSIONS["view_financial"]
PARTNERS_VIEW_CONFIDENTIAL = STAKEHOLDER_ACTION_PERMISSIONS["view_confidential"]
PARTNERS_CREATE = STAKEHOLDER_ACTION_PERMISSIONS["create"]
PARTNERS_UPDATE = STAKEHOLDER_ACTION_PERMISSIONS["update"]
PARTNERS_ARCHIVE = STAKEHOLDER_ACTION_PERMISSIONS["archive"]
PARTNERS_RESTORE = STAKEHOLDER_ACTION_PERMISSIONS["restore"]
PARTNERS_ASSIGN = STAKEHOLDER_ACTION_PERMISSIONS["assign"]
PARTNERS_MANAGE_CATEGORIES = STAKEHOLDER_ACTION_PERMISSIONS["manage_categories"]
PARTNERS_MANAGE_CONTACTS = STAKEHOLDER_ACTION_PERMISSIONS["manage_contacts"]
PARTNERS_ASSESS = STAKEHOLDER_ACTION_PERMISSIONS["assess"]
PARTNERS_MANAGE_ENGAGEMENTS = STAKEHOLDER_ACTION_PERMISSIONS["manage_engagements"]
PARTNERS_MANAGE_COMMUNICATIONS = STAKEHOLDER_ACTION_PERMISSIONS["manage_communications"]
PARTNERS_MANAGE_COMMITMENTS = STAKEHOLDER_ACTION_PERMISSIONS["manage_commitments"]
PARTNERS_MANAGE_CONTRIBUTIONS = STAKEHOLDER_ACTION_PERMISSIONS["manage_contributions"]
PARTNERS_MANAGE_AGREEMENTS = STAKEHOLDER_ACTION_PERMISSIONS["manage_agreements"]
PARTNERS_REVIEW_AGREEMENTS = STAKEHOLDER_ACTION_PERMISSIONS["review_agreements"]
PARTNERS_APPROVE_AGREEMENTS = STAKEHOLDER_ACTION_PERMISSIONS["approve_agreements"]
PARTNERS_MANAGE_DUE_DILIGENCE = STAKEHOLDER_ACTION_PERMISSIONS["manage_due_diligence"]
PARTNERS_MANAGE_RISK = STAKEHOLDER_ACTION_PERMISSIONS["manage_risk"]
PARTNERS_MANAGE_PERFORMANCE = STAKEHOLDER_ACTION_PERMISSIONS["manage_performance"]
PARTNERS_REVIEW_PERFORMANCE = STAKEHOLDER_ACTION_PERMISSIONS["review_performance"]
PARTNERS_MANAGE_ACTIONS = STAKEHOLDER_ACTION_PERMISSIONS["manage_actions"]
PARTNERS_MANAGE_NOTES = STAKEHOLDER_ACTION_PERMISSIONS["manage_notes"]
PARTNERS_MANAGE_DOCUMENTS = STAKEHOLDER_ACTION_PERMISSIONS["manage_documents"]
PARTNERS_MANAGE_ACCESS = STAKEHOLDER_ACTION_PERMISSIONS["manage_access"]
PARTNERS_ANALYTICS = STAKEHOLDER_ACTION_PERMISSIONS["analytics"]
PARTNERS_EXPORT = STAKEHOLDER_ACTION_PERMISSIONS["export"]
PARTNERS_MANAGE = STAKEHOLDER_ACTION_PERMISSIONS["manage"]


def user_can_manage_stakeholders(user) -> bool:
    return user_has_permission(user, PARTNERS_MANAGE)


def user_can_view_directory(user) -> bool:
    return user_has_permission(user, PARTNERS_VIEW_DIRECTORY)


def user_can_view_private_contacts(user) -> bool:
    return bool(
        getattr(user, "is_superuser", False)
        or user_has_permission(user, PARTNERS_MANAGE)
        or user_has_permission(user, PARTNERS_VIEW_PRIVATE_CONTACTS)
    )
