# Generated by Django 5.1 on 2026-08-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakeholder_profiles",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakeholder_profiles",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakeholder_profiles",
                to="locations.ward",
                verbose_name="Ward / Community",
            ),
        ),
    ]
