# Generated by Django 5.1 on 2026-08-19 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        ("rbac", "0024_seed_communications_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("service", "Service Account"),
                            ("organization", "Organization"),
                            ("application", "Application"),
                            ("device", "Device"),
                        ],
                        max_length=20,
                        verbose_name="Identity Type",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Identifier"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("pending_review", "Pending Review"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                            ("highly_confidential", "Highly Confidential"),
                        ],
                        default="internal",
                        max_length=30,
                        verbose_name="Confidentiality Level",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Attributes"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "managed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Managed By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "ordering": ("identity_type", "identifier"),
            },
        ),
        migrations.CreateModel(
            name="AccessReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Review Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("role", "Role Assignment Review"),
                            ("permission", "Permission Review"),
                            ("identity", "Identity Review"),
                            ("session", "Session Review"),
                            ("api_key", "API Key Review"),
                            ("service_account", "Service Account Review"),
                        ],
                        max_length=20,
                        verbose_name="Review Type",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Started At")),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "auto_approve_low_risk",
                    models.BooleanField(
                        default=False, verbose_name="Auto-Approve Low Risk"
                    ),
                ),
                (
                    "require_justification_for_changes",
                    models.BooleanField(
                        default=True, verbose_name="Require Justification for Changes"
                    ),
                ),
                (
                    "escalate_overdue_reviews",
                    models.BooleanField(
                        default=True, verbose_name="Escalate Overdue Reviews"
                    ),
                ),
                (
                    "total_items_reviewed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Items Reviewed"
                    ),
                ),
                (
                    "items_approved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items Approved"
                    ),
                ),
                (
                    "items_revoked",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items Revoked"
                    ),
                ),
                (
                    "items_modified",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items Modified"
                    ),
                ),
                (
                    "items_escalated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Items Escalated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lead_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_access_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lead Reviewer",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_reviews_as_reviewer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewers",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_reviews_as_target",
                        to="rbac.role",
                        verbose_name="Target Role",
                    ),
                ),
                (
                    "target_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_reviews_as_target",
                        to="security.identity",
                        verbose_name="Target Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Review",
                "verbose_name_plural": "Access Reviews",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="EnterpriseSecurityPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Policy Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Policy Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("password", "Password Policy"),
                            ("session", "Session Policy"),
                            ("api", "API Security Policy"),
                            ("network", "Network Policy"),
                            ("data", "Data Protection Policy"),
                            ("access", "Access Control Policy"),
                            ("encryption", "Encryption Policy"),
                            ("audit", "Audit Policy"),
                            ("authentication", "Authentication Policy"),
                            ("authorization", "Authorization Policy"),
                        ],
                        max_length=20,
                        verbose_name="Policy Type",
                    ),
                ),
                ("rules", models.JSONField(default=dict, verbose_name="Policy Rules")),
                (
                    "enforcement_level",
                    models.CharField(
                        choices=[
                            ("advisory", "Advisory"),
                            ("warning", "Warning"),
                            ("enforce", "Enforce"),
                            ("block", "Block"),
                        ],
                        default="enforce",
                        max_length=20,
                        verbose_name="Enforcement Level",
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Policy Scope"
                    ),
                ),
                (
                    "exceptions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Policy Exceptions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprise_security_policies_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprise_security_policies_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enterprise Security Policy",
                "verbose_name_plural": "Enterprise Security Policies",
                "ordering": ("policy_type", "name"),
            },
        ),
        migrations.CreateModel(
            name="ServiceIdentity",
            fields=[
                (
                    "identity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="security.identity",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("api", "API Service"),
                            ("integration", "Integration Service"),
                            ("background", "Background Service"),
                            ("scheduled", "Scheduled Service"),
                            ("monitoring", "Monitoring Service"),
                            ("other", "Other Service"),
                        ],
                        max_length=20,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "service_account_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Service Account Token"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token Expires At"
                    ),
                ),
                (
                    "ip_allowlist",
                    models.JSONField(
                        blank=True, default=list, verbose_name="IP Allowlist"
                    ),
                ),
                (
                    "allowed_operations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed Operations"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Identity",
                "verbose_name_plural": "Service Identities",
            },
            bases=("security.identity",),
        ),
        migrations.CreateModel(
            name="IdentityRole",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Assignment Conditions"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "delegation_chain",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Delegation Chain"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_identity_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_roles",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_roles",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Role",
                "verbose_name_plural": "Identity Roles",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Permission Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Permission Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("apps.security.constants", "apps.security.constants"),
                            ("Security module domains.", "Security module domains."),
                            ("identity", "identity"),
                            ("authentication", "authentication"),
                            ("authorization", "authorization"),
                            ("session", "session"),
                            ("accounts", "accounts"),
                            ("api", "api"),
                            ("database", "database"),
                            ("storage", "storage"),
                            ("documents", "documents"),
                            ("communications", "communications"),
                            ("infrastructure", "infrastructure"),
                            ("cloud", "cloud"),
                            ("integrations", "integrations"),
                            ("encryption", "encryption"),
                            ("secrets", "secrets"),
                            ("monitoring", "monitoring"),
                            ("incident_response", "incident_response"),
                            ("vulnerability", "vulnerability"),
                            ("compliance", "compliance"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="Resource Type"),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, verbose_name="Is System Permission"
                    ),
                ),
                (
                    "is_assignable",
                    models.BooleanField(default=True, verbose_name="Is Assignable"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Approval"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Permission Conditions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ("module", "resource_type", "action", "name"),
                "indexes": [
                    models.Index(
                        fields=["module", "resource_type"],
                        name="security_pe_module_a1f249_idx",
                    ),
                    models.Index(fields=["name"], name="security_pe_name_4112dd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessReviewItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("revoke", "Revoke"),
                            ("modify", "Modify"),
                            ("escalate", "Escalate"),
                        ],
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Risk Factors"
                    ),
                ),
                (
                    "previous_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Previous Value"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="New Value"),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="Change Reason"),
                ),
                (
                    "access_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="security.accessreview",
                        verbose_name="Access Review",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_review_items",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_review_items",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
                (
                    "identity_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_review_items",
                        to="security.identityrole",
                        verbose_name="Identity Role",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_review_items",
                        to="security.permission",
                        verbose_name="Permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Review Item",
                "verbose_name_plural": "Access Review Items",
                "ordering": ("-reviewed_at",),
            },
        ),
        migrations.AddField(
            model_name="accessreview",
            name="target_permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_reviews_as_target",
                to="security.permission",
                verbose_name="Target Permission",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Granted At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Permission Conditions"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granted By",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="security.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Session Key"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("suspicious", "Suspicious"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Activity At"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminated At"
                    ),
                ),
                (
                    "is_secure",
                    models.BooleanField(
                        default=False, verbose_name="Is Secure Connection"
                    ),
                ),
                (
                    "is_mfa_used",
                    models.BooleanField(default=False, verbose_name="MFA Used"),
                ),
                (
                    "mfa_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("totp", "Time-based OTP (TOTP)"),
                            ("email", "Email Verification"),
                            ("sms", "SMS Verification"),
                            ("recovery_codes", "Recovery Codes"),
                            ("authenticator_app", "Authenticator App"),
                            ("hardware_token", "Hardware Token"),
                        ],
                        max_length=20,
                        verbose_name="MFA Method",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Device Fingerprint"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Session Attributes"
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationalIdentity",
            fields=[
                (
                    "identity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="security.identity",
                    ),
                ),
                (
                    "org_identity_type",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("team", "Team"),
                            ("division", "Division"),
                            ("unit", "Unit"),
                            ("committee", "Committee"),
                            ("working_group", "Working Group"),
                            ("other", "Other Organizational"),
                        ],
                        max_length=20,
                        verbose_name="Organizational Identity Type",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contact Person",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizational_identities",
                        to="organizations.organizationunit",
                        verbose_name="Organization Unit",
                    ),
                ),
                (
                    "parent_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_identities",
                        to="organizations.organizationunit",
                        verbose_name="Parent Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Identity",
                "verbose_name_plural": "Organizational Identities",
            },
            bases=("security.identity",),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["identity_type", "status"],
                name="security_id_identit_3aba2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["identifier"], name="security_id_identif_50780b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(fields=["owner"], name="security_id_owner_i_a4914b_idx"),
        ),
        migrations.AddIndex(
            model_name="identityrole",
            index=models.Index(
                fields=["identity", "is_active"], name="security_id_identit_042918_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityrole",
            index=models.Index(
                fields=["role", "is_active"], name="security_id_role_id_33177e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityrole",
            index=models.Index(
                fields=["assigned_by"], name="security_id_assigne_0c7628_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="identityrole",
            unique_together={("identity", "role")},
        ),
        migrations.AddIndex(
            model_name="accessreviewitem",
            index=models.Index(
                fields=["access_review", "reviewed_at"],
                name="security_ac_access__69d9e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accessreviewitem",
            index=models.Index(
                fields=["decision"], name="security_ac_decisio_5b1b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessreviewitem",
            index=models.Index(
                fields=["risk_level"], name="security_ac_risk_le_eda4ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessreview",
            index=models.Index(
                fields=["review_type", "status"], name="security_ac_review__5e009a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessreview",
            index=models.Index(
                fields=["due_date"], name="security_ac_due_dat_a8380f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessreview",
            index=models.Index(
                fields=["started_at"], name="security_ac_started_1284a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "is_active"], name="security_ro_role_id_c2aa9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission", "is_active"],
                name="security_ro_permiss_5bd689_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["identity", "status"], name="security_se_identit_7b71c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_key"], name="security_se_session_1df433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["ip_address"], name="security_se_ip_addr_194042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["expires_at"], name="security_se_expires_fd477d_idx"
            ),
        ),
    ]
