# Generated by Django 5.1 on 2026-08-19 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("totp", "Time-based OTP (TOTP)"),
                            ("email", "Email Verification"),
                            ("sms", "SMS Verification"),
                            ("recovery_codes", "Recovery Codes"),
                            ("authenticator_app", "Authenticator App"),
                            ("hardware_token", "Hardware Token"),
                        ],
                        max_length=20,
                        verbose_name="MFA Method",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Is Primary Method"
                    ),
                ),
                (
                    "is_backup",
                    models.BooleanField(default=False, verbose_name="Is Backup Method"),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enrolled At"),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Secret Key"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Backup Codes"
                    ),
                ),
                (
                    "backup_codes_used",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Used Backup Codes"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Is Enabled"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Usage Count"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Friendly Name"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_enrollments_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enrolled By",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_enrollments",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Enrollment",
                "verbose_name_plural": "MFA Enrollments",
            },
        ),
        migrations.CreateModel(
            name="MFAVerificationAttempt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Challenge"
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Response"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed_invalid_code", "Invalid Code"),
                            ("failed_expired_code", "Expired Code"),
                            ("failed_rate_limited", "Rate Limited"),
                            ("failed_other", "Other Failure"),
                        ],
                        max_length=20,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Attempted At"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "trusted_device",
                    models.BooleanField(default=False, verbose_name="Trusted Device"),
                ),
                (
                    "backup_code_used",
                    models.BooleanField(default=False, verbose_name="Backup Code Used"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verization_attempts",
                        to="security.mfaenrollment",
                        verbose_name="MFA Enrollment",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_verification_attempts",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Verification Attempt",
                "verbose_name_plural": "MFA Verification Attempts",
                "ordering": ("-attempted_at",),
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username_attempted",
                    models.CharField(max_length=255, verbose_name="Username Attempted"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed_invalid_credentials", "Invalid Credentials"),
                            ("failed_account_locked", "Account Locked"),
                            ("failed_expired", "Account Expired"),
                            ("failed_disabled", "Account Disabled"),
                            ("failed_mfa_required", "MFA Required"),
                            ("failed_mfa_invalid", "Invalid MFA Code"),
                            ("failed_other", "Other Failure"),
                        ],
                        max_length=30,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Failure Reason"),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Risk score from 0-100",
                        verbose_name="Risk Score",
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="Is Suspicious"),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Country Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["identity", "-created_at"],
                        name="security_lo_identit_0f4fb0_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="security_lo_ip_addr_072023_idx",
                    ),
                    models.Index(
                        fields=["outcome", "-created_at"],
                        name="security_lo_outcome_5f3bde_idx",
                    ),
                    models.Index(
                        fields=["is_suspicious"], name="security_lo_is_susp_4bb9f9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mfaenrollment",
            index=models.Index(
                fields=["identity", "is_enabled"], name="security_mf_identit_d10ea2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfaenrollment",
            index=models.Index(
                fields=["method", "is_enabled"], name="security_mf_method_873b66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mfaenrollment",
            unique_together={("identity", "method")},
        ),
        migrations.AddIndex(
            model_name="mfaverificationattempt",
            index=models.Index(
                fields=["identity", "-attempted_at"],
                name="security_mf_identit_b636bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationattempt",
            index=models.Index(
                fields=["enrollment", "-attempted_at"],
                name="security_mf_enrollm_cec372_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationattempt",
            index=models.Index(
                fields=["outcome", "-attempted_at"],
                name="security_mf_outcome_83b631_idx",
            ),
        ),
    ]
