# Generated by Django 5.1 on 2026-08-19 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0024_seed_communications_permissions"),
        ("security", "0002_mfaenrollment_mfaverificationattempt_loginattempt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGrant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Granted At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Permission Conditions"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granted By",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="security.identity",
                        verbose_name="Identity",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="security.permission",
                        verbose_name="Permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Grant",
                "verbose_name_plural": "Permission Grants",
                "indexes": [
                    models.Index(
                        fields=["identity", "is_active"],
                        name="security_pe_identit_cc6093_idx",
                    ),
                    models.Index(
                        fields=["permission", "is_active"],
                        name="security_pe_permiss_716a36_idx",
                    ),
                    models.Index(
                        fields=["granted_by"], name="security_pe_granted_8bcb51_idx"
                    ),
                ],
                "unique_together": {("identity", "permission")},
            },
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inherit_permissions",
                    models.BooleanField(
                        default=True, verbose_name="Inherit Permissions"
                    ),
                ),
                (
                    "inherit_role_permissions",
                    models.BooleanField(
                        default=True, verbose_name="Inherit Role Permissions"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "child_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_roles",
                        to="rbac.role",
                        verbose_name="Child Role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_roles",
                        to="rbac.role",
                        verbose_name="Parent Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Hierarchy",
                "verbose_name_plural": "Role Hierarchies",
                "indexes": [
                    models.Index(
                        fields=["parent_role"], name="security_ro_parent__59adeb_idx"
                    ),
                    models.Index(
                        fields=["child_role"], name="security_ro_child_r_d9a17b_idx"
                    ),
                ],
                "unique_together": {("parent_role", "child_role")},
            },
        ),
    ]
