# Generated by Django 5.1 on 2026-08-22 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0024_seed_communications_permissions"),
        ("security", "0003_permissiongrant_rolehierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIAccessToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", max_length=50, verbose_name="Token Type"
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Token Scopes"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Token Permissions"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Issued At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Not Before"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Usage Count"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Is Revoked"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revoked At"
                    ),
                ),
                (
                    "revoked_reason",
                    models.TextField(blank=True, verbose_name="Revoked Reason"),
                ),
            ],
            options={
                "verbose_name": "API Access Token",
                "verbose_name_plural": "API Access Tokens",
                "ordering": ("-issued_at",),
            },
        ),
        migrations.CreateModel(
            name="APICredential",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Credential Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Credential Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("oauth_token", "OAuth Token"),
                            ("jwt_token", "JWT Token"),
                            ("basic_auth", "Basic Auth"),
                            ("bearer_token", "Bearer Token"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                        verbose_name="Credential Type",
                    ),
                ),
                (
                    "credential_key",
                    models.CharField(max_length=255, verbose_name="Credential Key"),
                ),
                (
                    "credential_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Credential Secret"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=100, verbose_name="Service Name"),
                ),
                (
                    "service_url",
                    models.URLField(blank=True, verbose_name="Service URL"),
                ),
                (
                    "ip_allowlist",
                    models.JSONField(
                        blank=True, default=list, verbose_name="IP Allowlist"
                    ),
                ),
                (
                    "allowed_endpoints",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed Endpoints"
                    ),
                ),
                (
                    "allowed_methods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed HTTP Methods"
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Maximum API calls per hour",
                        verbose_name="Rate Limit Per Hour",
                    ),
                ),
                (
                    "rate_limit_per_day",
                    models.PositiveIntegerField(
                        default=10000,
                        help_text="Maximum API calls per day",
                        verbose_name="Rate Limit Per Day",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Usage Count"
                    ),
                ),
                (
                    "is_compromised",
                    models.BooleanField(default=False, verbose_name="Is Compromised"),
                ),
                (
                    "compromised_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Compromised At"
                    ),
                ),
                (
                    "compromised_reason",
                    models.TextField(blank=True, verbose_name="Compromised Reason"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Credential",
                "verbose_name_plural": "API Credentials",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="APIRateLimit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("window_start", models.DateTimeField(verbose_name="Window Start")),
                ("window_end", models.DateTimeField(verbose_name="Window End")),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Request Count"
                    ),
                ),
                (
                    "blocked_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Blocked Count"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endpoint"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="HTTP Method"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Status Code"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Rate Limit",
                "verbose_name_plural": "API Rate Limits",
                "ordering": ("-window_start",),
            },
        ),
        migrations.CreateModel(
            name="DatabaseAccessLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session ID"
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="Username")),
                (
                    "client_ip",
                    models.GenericIPAddressField(verbose_name="Client IP Address"),
                ),
                (
                    "client_hostname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Client Hostname"
                    ),
                ),
                (
                    "connection_started",
                    models.DateTimeField(verbose_name="Connection Started"),
                ),
                (
                    "connection_ended",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Connection Ended"
                    ),
                ),
                (
                    "statement_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Statement Timestamp"
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("terminated", "Terminated"),
                            ("idle", "Idle"),
                            ("error", "Error"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="Connection Status",
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Statement Type"
                    ),
                ),
                ("statement", models.TextField(blank=True, verbose_name="Statement")),
                (
                    "statement_duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Statement Duration (ms)"
                    ),
                ),
                (
                    "rows_affected",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Rows Affected"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Error Code"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Access Log",
                "verbose_name_plural": "Database Access Logs",
                "ordering": ("-connection_started",),
            },
        ),
        migrations.CreateModel(
            name="DatabaseSecurityPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Policy Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Policy Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "database_identifier",
                    models.CharField(
                        max_length=100, verbose_name="Database Identifier"
                    ),
                ),
                (
                    "database_type",
                    models.CharField(
                        help_text="e.g., postgresql, mysql, sqlite",
                        max_length=50,
                        verbose_name="Database Type",
                    ),
                ),
                (
                    "host",
                    models.CharField(blank=True, max_length=255, verbose_name="Host"),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Port"
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Database Name"
                    ),
                ),
                (
                    "require_ssl",
                    models.BooleanField(default=True, verbose_name="Require SSL/TLS"),
                ),
                (
                    "ssl_cert_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SSL Certificate Path"
                    ),
                ),
                (
                    "ssl_key_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SSL Key Path"
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        help_text="e.g., password, certificate, ldap",
                        max_length=50,
                        verbose_name="Authentication Method",
                    ),
                ),
                (
                    "use_connection_pooling",
                    models.BooleanField(
                        default=True, verbose_name="Use Connection Pooling"
                    ),
                ),
                (
                    "max_connections",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Max Connections"
                    ),
                ),
                (
                    "statement_timeout_ms",
                    models.PositiveIntegerField(
                        default=30000,
                        help_text="Maximum time to execute a statement",
                        verbose_name="Statement Timeout (ms)",
                    ),
                ),
                (
                    "lock_timeout_ms",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Maximum time to wait for a lock",
                        verbose_name="Lock Timeout (ms)",
                    ),
                ),
                (
                    "audit_connections",
                    models.BooleanField(default=True, verbose_name="Audit Connections"),
                ),
                (
                    "audit_statements",
                    models.BooleanField(default=False, verbose_name="Audit Statements"),
                ),
                (
                    "audit_statement_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("ddl", "DDL Only"),
                            ("dml", "DML Only"),
                            ("all", "All"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Audit Statement Level",
                    ),
                ),
                (
                    "encryption_at_rest",
                    models.BooleanField(
                        default=False, verbose_name="Encryption at Rest"
                    ),
                ),
                (
                    "encryption_key_identifier",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Encryption Key Identifier",
                    ),
                ),
                (
                    "allow_public_access",
                    models.BooleanField(
                        default=False, verbose_name="Allow Public Access"
                    ),
                ),
                (
                    "allowed_networks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed Networks"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Validated At"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("valid", "Valid"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Validation Status",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Security Policy",
                "verbose_name_plural": "Database Security Policies",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SecureFile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="File Size (bytes)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content Type"),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="Storage Path"),
                ),
                (
                    "storage_bucket",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Storage Bucket"
                    ),
                ),
                (
                    "storage_region",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Storage Region"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is Public"),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                            ("highly_confidential", "Highly Confidential"),
                        ],
                        default="internal",
                        max_length=30,
                        verbose_name="Confidentiality Level",
                    ),
                ),
                (
                    "checksum_algorithm",
                    models.CharField(
                        default="sha256",
                        max_length=20,
                        verbose_name="Checksum Algorithm",
                    ),
                ),
                (
                    "checksum_value",
                    models.CharField(max_length=64, verbose_name="Checksum Value"),
                ),
                (
                    "previous_checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Previous Checksum"
                    ),
                ),
                (
                    "virus_scan_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("quarantined", "Quarantined"),
                            ("scan_failed", "Scan Failed"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Virus Scan Status",
                    ),
                ),
                (
                    "virus_scan_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Virus Scan At"
                    ),
                ),
                (
                    "virus_scan_details",
                    models.TextField(blank=True, verbose_name="Virus Scan Details"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="Is Encrypted"),
                ),
                (
                    "encryption_algorithm",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Encryption Algorithm"
                    ),
                ),
                (
                    "encryption_key_identifier",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Encryption Key Identifier",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "is_latest_version",
                    models.BooleanField(default=True, verbose_name="Is Latest Version"),
                ),
                (
                    "retention_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Retention Date"
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Retention Policy"
                    ),
                ),
                (
                    "legal_hold",
                    models.BooleanField(default=False, verbose_name="Legal Hold"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "upload_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Upload Metadata"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secure File",
                "verbose_name_plural": "Secure Files",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Additional Attributes"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="device_fingerprint",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Device Fingerprint"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="device_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Device Name"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="failed_attempt_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Failed Attempt Count"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="is_trusted_device",
            field=models.BooleanField(default=False, verbose_name="Is Trusted Device"),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Locked Until"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="trust_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trust Expires At"
            ),
        ),
        migrations.AddField(
            model_name="mfaenrollment",
            name="trusted_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trusted Since"
            ),
        ),
        migrations.AddField(
            model_name="mfaverificationattempt",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="mfaverificationattempt",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=2, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="mfaverificationattempt",
            name="is_suspicious",
            field=models.BooleanField(default=False, verbose_name="Is Suspicious"),
        ),
        migrations.AddField(
            model_name="mfaverificationattempt",
            name="risk_score",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Risk score from 0-100", verbose_name="Risk Score"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="absolute_timeout_minutes",
            field=models.PositiveIntegerField(
                default=480,
                help_text="Maximum session duration regardless of activity",
                verbose_name="Absolute Timeout Minutes",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="idle_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutes of inactivity before session expires",
                verbose_name="Idle Timeout Minutes",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Session that superseded this one (for concurrent session limits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by_session",
                to="security.session",
                verbose_name="Superseded By",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="Session that this one superseded (for concurrent session limits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes_session",
                to="security.session",
                verbose_name="Supersedes",
            ),
        ),
        migrations.AlterField(
            model_name="mfaverificationattempt",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_attempts",
                to="security.mfaenrollment",
                verbose_name="MFA Enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="mfaenrollment",
            index=models.Index(
                fields=["is_trusted_device"], name="security_mf_is_trus_3fd299_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfaenrollment",
            index=models.Index(
                fields=["device_fingerprint"], name="security_mf_device__59208c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationattempt",
            index=models.Index(
                fields=["is_suspicious"], name="security_mf_is_susp_97fbf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mfaverificationattempt",
            index=models.Index(
                fields=["trusted_device"], name="security_mf_trusted_3d2157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["superseded_by"], name="security_se_superse_fd442b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["supersedes"], name="security_se_superse_1ba5e7_idx"
            ),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity associated with this token (if different from credential owner)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_access_tokens",
                to="security.identity",
                verbose_name="Identity",
            ),
        ),
        migrations.AddField(
            model_name="apicredential",
            name="identity",
            field=models.ForeignKey(
                help_text="Identity that owns this credential",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_credentials",
                to="security.identity",
                verbose_name="Identity",
            ),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_tokens",
                to="security.apicredential",
                verbose_name="API Credential",
            ),
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_limits",
                to="security.apicredential",
                verbose_name="API Credential",
            ),
        ),
        migrations.AddField(
            model_name="apiratelimit",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity making the API calls (if known)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_rate_limits",
                to="security.identity",
                verbose_name="Identity",
            ),
        ),
        migrations.AddIndex(
            model_name="databasesecuritypolicy",
            index=models.Index(
                fields=["database_identifier", "is_active"],
                name="security_da_databas_66cd50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databasesecuritypolicy",
            index=models.Index(
                fields=["database_type", "is_active"],
                name="security_da_databas_594958_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databasesecuritypolicy",
            index=models.Index(
                fields=["is_active"], name="security_da_is_acti_a92b10_idx"
            ),
        ),
        migrations.AddField(
            model_name="databaseaccesslog",
            name="database_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="security.databasesecuritypolicy",
                verbose_name="Database Security Policy",
            ),
        ),
        migrations.AddField(
            model_name="securefile",
            name="allowed_identities",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_files",
                to="security.identity",
                verbose_name="Allowed Identities",
            ),
        ),
        migrations.AddField(
            model_name="securefile",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_files",
                to="rbac.role",
                verbose_name="Allowed Roles",
            ),
        ),
        migrations.AddField(
            model_name="securefile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_files",
                to="security.identity",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="securefile",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_files",
                to="security.securefile",
                verbose_name="Replaced By",
            ),
        ),
        migrations.AddField(
            model_name="securefile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="security.identity",
                verbose_name="Uploaded By",
            ),
        ),
        migrations.AddIndex(
            model_name="apicredential",
            index=models.Index(
                fields=["identity", "is_active"], name="security_ap_identit_52c0fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicredential",
            index=models.Index(
                fields=["service_name", "is_active"],
                name="security_ap_service_4b31bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicredential",
            index=models.Index(
                fields=["credential_type", "is_active"],
                name="security_ap_credent_e01002_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicredential",
            index=models.Index(
                fields=["expires_at"], name="security_ap_expires_47df27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicredential",
            index=models.Index(
                fields=["is_compromised"], name="security_ap_is_comp_d6836b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesstoken",
            index=models.Index(fields=["token"], name="security_ap_token_b45522_idx"),
        ),
        migrations.AddIndex(
            model_name="apiaccesstoken",
            index=models.Index(
                fields=["credential", "-issued_at"],
                name="security_ap_credent_6c1d99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesstoken",
            index=models.Index(
                fields=["identity", "-issued_at"], name="security_ap_identit_f5dfc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesstoken",
            index=models.Index(
                fields=["expires_at"], name="security_ap_expires_81c485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiaccesstoken",
            index=models.Index(
                fields=["is_revoked"], name="security_ap_is_revo_58ee44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(
                fields=["credential", "-window_start"],
                name="security_ap_credent_0090c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(
                fields=["identity", "-window_start"],
                name="security_ap_identit_d26239_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(
                fields=["endpoint", "-window_start"],
                name="security_ap_endpoin_0befa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiratelimit",
            index=models.Index(
                fields=["ip_address", "-window_start"],
                name="security_ap_ip_addr_40d1fc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiratelimit",
            unique_together={("credential", "window_start", "endpoint", "method")},
        ),
        migrations.AddIndex(
            model_name="databaseaccesslog",
            index=models.Index(
                fields=["database_policy", "-connection_started"],
                name="security_da_databas_6fa3a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databaseaccesslog",
            index=models.Index(
                fields=["username", "-connection_started"],
                name="security_da_usernam_e4b0e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databaseaccesslog",
            index=models.Index(
                fields=["client_ip", "-connection_started"],
                name="security_da_client__20e462_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databaseaccesslog",
            index=models.Index(
                fields=["connection_status"], name="security_da_connect_3d08be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="databaseaccesslog",
            index=models.Index(
                fields=["statement_timestamp"], name="security_da_stateme_a76451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["owner", "is_active"], name="security_se_owner_i_086349_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["uploaded_by", "is_active"],
                name="security_se_uploade_b9ef4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["confidentiality", "is_active"],
                name="security_se_confide_dd8fff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["is_encrypted"], name="security_se_is_encr_550dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["virus_scan_status"], name="security_se_virus_s_161283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["is_latest_version"], name="security_se_is_late_5dbfe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securefile",
            index=models.Index(
                fields=["filename"], name="security_se_filenam_7369af_idx"
            ),
        ),
    ]
