# Generated by Django 6.0.8 on 2026-08-15 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="default",
                        help_text="Unique key to enforce singleton pattern.",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "application_name",
                    models.CharField(
                        default="SITADC Youth Hub",
                        max_length=150,
                        verbose_name="Application Name",
                    ),
                ),
                (
                    "application_short_name",
                    models.CharField(
                        default="SITADC Hub",
                        max_length=50,
                        verbose_name="Application Short Name",
                    ),
                ),
                (
                    "system_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Maintenance"),
                            ("disabled", "Disabled"),
                        ],
                        default="operational",
                        max_length=20,
                        verbose_name="System Status",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Default Language"
                    ),
                ),
                (
                    "default_timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Default Timezone"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="Y-m-d", max_length=20, verbose_name="Date Format"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="H:i:s", max_length=20, verbose_name="Time Format"
                    ),
                ),
                (
                    "default_pagination_size",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Number of items per page in lists.",
                        verbose_name="Default Pagination Size",
                    ),
                ),
                (
                    "branding",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Branding overrides (logo, favicon, colors, etc.).",
                        verbose_name="Branding",
                    ),
                ),
                (
                    "email_sender_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Email Sender Name"
                    ),
                ),
                (
                    "email_sender_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Sender Address"
                    ),
                ),
                (
                    "email_footer",
                    models.TextField(blank=True, verbose_name="Email Footer"),
                ),
                (
                    "notification_retention_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How long to retain notifications before deletion.",
                        verbose_name="Notification Retention (days)",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Enable Email Notifications"
                    ),
                ),
                (
                    "enable_sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Enable SMS Notifications"
                    ),
                ),
                (
                    "enable_push_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Enable Push Notifications"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutes of inactivity before session expires.",
                        verbose_name="Session Timeout (minutes)",
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Minimum Password Length"
                    ),
                ),
                (
                    "password_require_uppercase",
                    models.BooleanField(
                        default=True, verbose_name="Require Uppercase Letter"
                    ),
                ),
                (
                    "password_require_lowercase",
                    models.BooleanField(
                        default=True, verbose_name="Require Lowercase Letter"
                    ),
                ),
                (
                    "password_require_digits",
                    models.BooleanField(default=True, verbose_name="Require Digit"),
                ),
                (
                    "password_require_special_chars",
                    models.BooleanField(
                        default=True, verbose_name="Require Special Character"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Failed login attempts before account lockout.",
                        verbose_name="Maximum Login Attempts",
                    ),
                ),
                (
                    "lockout_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutes an account is locked after too many failed attempts.",
                        verbose_name="Lockout Duration (minutes)",
                    ),
                ),
                (
                    "password_validity_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days a password is valid (null for no expiration).",
                        null=True,
                        verbose_name="Password Validity (days)",
                    ),
                ),
                (
                    "require_2fa_for_admin",
                    models.BooleanField(
                        default=False, verbose_name="Require 2FA for Administrators"
                    ),
                ),
                (
                    "invitation_expiry_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days before an invitation expires.",
                        verbose_name="Invitation Expiry (days)",
                    ),
                ),
                (
                    "password_reset_token_expiry_hours",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Hours before a password reset token expires.",
                        verbose_name="Password Reset Token Expiry (hours)",
                    ),
                ),
                (
                    "login_attempt_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of failed login attempts to trigger security actions.",
                        verbose_name="Login Attempt Threshold",
                    ),
                ),
                (
                    "default_review_deadline_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Default hours to complete a review.",
                        verbose_name="Default Review Deadline (hours)",
                    ),
                ),
                (
                    "default_approval_deadline_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Default hours to complete an approval.",
                        verbose_name="Default Approval Deadline (hours)",
                    ),
                ),
                (
                    "default_correction_deadline_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Default hours to complete corrections.",
                        verbose_name="Default Correction Deadline (hours)",
                    ),
                ),
                (
                    "default_escalation_delay_hours",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Default hours before escalating an overdue review or approval.",
                        verbose_name="Default Escalation Delay (hours)",
                    ),
                ),
                (
                    "audit_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="How long to retain audit logs before deletion.",
                        verbose_name="Audit Retention (days)",
                    ),
                ),
                (
                    "audit_log_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable Audit Logging"
                    ),
                ),
                (
                    "default_dashboard_landing_page",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("reports", "Reports"),
                            ("tasks", "Tasks"),
                            ("calendar", "Calendar"),
                        ],
                        default="overview",
                        max_length=20,
                        verbose_name="Default Dashboard Landing Page",
                    ),
                ),
                (
                    "dashboard_refresh_interval_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="How often to refresh dashboard data (in seconds).",
                        verbose_name="Dashboard Refresh Interval (seconds)",
                    ),
                ),
                (
                    "maintenance_mode_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Maintenance Mode Enabled"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        help_text="Message to display to users when maintenance mode is enabled.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                (
                    "maintenance_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Maintenance Start Time"
                    ),
                ),
                (
                    "maintenance_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Maintenance End Time"
                    ),
                ),
                (
                    "maintenance_allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of role names or IDs that can access the system during maintenance.",
                        verbose_name="Allowed Roles During Maintenance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization unit that represents the organization.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organizationunit",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
            },
        ),
    ]
