# Generated by Django 6.0.8 on 2026-08-12 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=90, unique=True, verbose_name="Name"),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        help_text="1=January, 12=December", verbose_name="Start month"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Budget name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Budget code"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total amount"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Allocated amount",
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Spent amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.financialyear",
                        verbose_name="Financial year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ("-financial_year", "name"),
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Account name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Account code"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        default="INCOME", max_length=20, verbose_name="Account type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Account",
                "verbose_name_plural": "Financial Accounts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Program"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Project"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Allocated amount"
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Spent amount",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Percentage"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="finance.budget",
                        verbose_name="Budget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Allocation",
                "verbose_name_plural": "Budget Allocations",
                "unique_together": {("budget", "program", "project")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Transaction type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("RECONCILED", "Reconciled"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GRANT", "Grant"),
                            ("DONATION", "Donation"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("FEE", "Fee"),
                            ("FUNDRAISING", "Fundraising"),
                            ("PARTNERSHIP", "Partnership"),
                            ("GOVERNMENT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Resource source",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "beneficiary",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Beneficiary"
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Program"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Project"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Approval status"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHEQUE", "Cheque"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DIRECT_DEBIT", "Direct Debit"),
                        ],
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Receipt date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Sensitive data"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["transaction_type", "status"],
                        name="finance_tra_transac_4d20c4_idx",
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="finance_tra_source_c4bb68_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="finance_tra_created_945fa1_idx"
                    ),
                ],
            },
        ),
    ]
