# Generated by Django 6.0.8 on 2026-08-15 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={
                "ordering": ("-financial_year", "-start_date", "name"),
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="activity",
            field=models.CharField(blank=True, max_length=200, verbose_name="Activity"),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual Budget"),
                    ("QUARTERLY", "Quarterly Budget"),
                    ("MONTHLY", "Monthly Budget"),
                    ("PROGRAMME", "Programme Budget"),
                    ("PROJECT", "Project Budget"),
                    ("DEPARTMENTAL", "Departmental Budget"),
                    ("ACTIVITY", "Activity Budget"),
                    ("GRANT", "Grant Budget"),
                    ("REVISED", "Revised Budget"),
                ],
                default="ANNUAL",
                max_length=20,
                verbose_name="Budget type",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="budget",
            name="grant",
            field=models.CharField(blank=True, max_length=200, verbose_name="Grant"),
        ),
        migrations.AddField(
            model_name="budget",
            name="is_revised",
            field=models.BooleanField(default=False, verbose_name="Is revised"),
        ),
        migrations.AddField(
            model_name="budget",
            name="programme",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Programme"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="project",
            field=models.CharField(blank=True, max_length=200, verbose_name="Project"),
        ),
        migrations.AddField(
            model_name="budget",
            name="revised_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Revised amount",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity/Fund Balance"),
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                ],
                default="ASSET",
                max_length=20,
                verbose_name="Account type",
            ),
        ),
        migrations.CreateModel(
            name="AssetFinancialTracking",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Asset name")),
                (
                    "asset_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Asset number"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("VEHICLE", "Vehicle"),
                            ("EQUIPMENT", "Equipment"),
                            ("FURNITURE", "Furniture"),
                            ("TECHNOLOGY", "Technology"),
                            ("LAND", "Land"),
                            ("OTHER", "Other"),
                        ],
                        default="EQUIPMENT",
                        max_length=20,
                        verbose_name="Asset type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Acquisition cost"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Current value",
                    ),
                ),
                ("acquisition_date", models.DateField(verbose_name="Acquisition date")),
                (
                    "depreciation_method",
                    models.CharField(
                        help_text="e.g., Straight-line, Declining balance",
                        max_length=50,
                        verbose_name="Depreciation method",
                    ),
                ),
                (
                    "useful_life_years",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Useful life (years)"
                    ),
                ),
                (
                    "annual_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Annual depreciation",
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Accumulated depreciation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("IN_MAINTENANCE", "In Maintenance"),
                            ("RETIRED", "Retired"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last maintenance date"
                    ),
                ),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next maintenance date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Financial Tracking",
                "verbose_name_plural": "Asset Financial Tracking",
                "ordering": ("-acquisition_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Account name")),
                (
                    "account_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Account number"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=200, verbose_name="Bank name"),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bank branch"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current Account"),
                            ("SAVINGS", "Savings Account"),
                            ("FIXED_DEPOSIT", "Fixed Deposit"),
                            ("OTHER", "Other"),
                        ],
                        default="CURRENT",
                        max_length=20,
                        verbose_name="Account type",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Opening balance",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Current balance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "reconciliation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last reconciliation date"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SWIFT code"
                    ),
                ),
                (
                    "routing_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Routing number"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Donor name")),
                (
                    "donor_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Donor number"
                    ),
                ),
                (
                    "donor_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATE", "Corporate"),
                            ("FOUNDATION", "Foundation"),
                            ("GOVERNMENT", "Government"),
                            ("INTERNATIONAL_ORG", "International Organization"),
                            ("OTHER", "Other"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                        verbose_name="Donor type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contact person"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("LAPSED", "Lapsed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_donated",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total donated",
                    ),
                ),
                (
                    "year_to_date_donated",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Year to date donated",
                    ),
                ),
                (
                    "last_donation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last donation date"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Preferred contact method",
                    ),
                ),
                (
                    "communication_preferences",
                    models.TextField(
                        blank=True, verbose_name="Communication preferences"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
                "ordering": ("-total_donated", "name"),
            },
        ),
        migrations.CreateModel(
            name="FinancialForecast",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Forecast name"),
                ),
                (
                    "forecast_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Forecast number"
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue Forecast"),
                            ("EXPENDITURE", "Expenditure Forecast"),
                            ("CASH_FLOW", "Cash Flow Forecast"),
                            ("BUDGET", "Budget Forecast"),
                        ],
                        default="REVENUE",
                        max_length=20,
                        verbose_name="Forecast type",
                    ),
                ),
                (
                    "forecast_period_start",
                    models.DateField(verbose_name="Forecast period start"),
                ),
                (
                    "forecast_period_end",
                    models.DateField(verbose_name="Forecast period end"),
                ),
                (
                    "projected_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Projected income",
                    ),
                ),
                (
                    "projected_expenditure",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Projected expenditure",
                    ),
                ),
                (
                    "projected_surplus_deficit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Projected surplus/deficit",
                    ),
                ),
                (
                    "assumptions",
                    models.TextField(blank=True, verbose_name="Assumptions"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_forecasts",
                        to="finance.financialyear",
                        verbose_name="Financial year",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Forecast",
                "verbose_name_plural": "Financial Forecasts",
                "ordering": ("-forecast_period_start", "name"),
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Grant name")),
                (
                    "grant_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Grant number"
                    ),
                ),
                (
                    "funding_agency",
                    models.CharField(max_length=200, verbose_name="Funding agency"),
                ),
                (
                    "grant_type",
                    models.CharField(max_length=100, verbose_name="Grant type"),
                ),
                (
                    "amount_awarded",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount awarded"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                ("award_date", models.DateField(verbose_name="Award date")),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROSPECTIVE", "Prospective"),
                            ("APPLIED", "Applied"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PROSPECTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Programme"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Project"
                    ),
                ),
                (
                    "reporting_frequency",
                    models.CharField(
                        help_text="e.g., Monthly, Quarterly, Annual",
                        max_length=50,
                        verbose_name="Reporting frequency",
                    ),
                ),
                (
                    "next_report_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next report due"
                    ),
                ),
                (
                    "special_conditions",
                    models.TextField(blank=True, verbose_name="Special conditions"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant",
                "verbose_name_plural": "Grants",
                "ordering": ("-award_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="PettyCash",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Petty cash name"),
                ),
                (
                    "custodian",
                    models.CharField(max_length=200, verbose_name="Custodian"),
                ),
                (
                    "custodian_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Custodian position"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Opening balance",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Current balance",
                    ),
                ),
                (
                    "max_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum amount allowed in petty cash",
                        max_digits=15,
                        verbose_name="Maximum limit",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "last_replenished",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last replenished"
                    ),
                ),
                (
                    "replenishment_approval_level",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Replenishment approval level",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petty Cash",
                "verbose_name_plural": "Petty Cash",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProcurementFinancialTracking",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Procurement name"),
                ),
                (
                    "procurement_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Procurement number"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Estimated cost"
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Actual cost",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                ("required_date", models.DateField(verbose_name="Required date")),
                (
                    "promised_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Promised date"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual delivery date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("ORDERED", "Ordered"),
                            ("RECEIVED", "Received"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "budget_line",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Budget line"
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Programme"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Project"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supplier name"
                    ),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supplier contact"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        help_text="e.g., Net 30, Net 60",
                        max_length=100,
                        verbose_name="Payment terms",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Financial Tracking",
                "verbose_name_plural": "Procurement Financial Tracking",
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Sponsor name")),
                (
                    "sponsor_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sponsor number"
                    ),
                ),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("CORPORATE", "Corporate"),
                            ("GOVERNMENT", "Government"),
                            ("INSTITUTIONAL", "Institutional"),
                            ("INDIVIDUAL", "Individual"),
                            ("OTHER", "OTHER"),
                        ],
                        default="CORPORATE",
                        max_length=20,
                        verbose_name="Sponsor type",
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial Support"),
                            ("IN_KIND", "In-Kind Support"),
                            ("MEDIA", "Media Support"),
                            ("TECHNICAL", "Technical Support"),
                            ("VENUE", "VENUE Support"),
                            ("OTHER", "OTHER"),
                        ],
                        default="FINANCIAL",
                        max_length=20,
                        verbose_name="Sponsorship type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contact person"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "sponsored_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sponsored amount",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROSPECTIVE", "Prospective"),
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="PROSPECTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Programme"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Project"
                    ),
                ),
                (
                    "event",
                    models.CharField(blank=True, max_length=200, verbose_name="Event"),
                ),
                (
                    "benefits_received",
                    models.TextField(blank=True, verbose_name="Benefits received"),
                ),
                (
                    "reporting_frequency",
                    models.CharField(
                        help_text="e.g., Monthly, Quarterly, Annual",
                        max_length=50,
                        verbose_name="Reporting frequency",
                    ),
                ),
                (
                    "next_report_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next report due"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ("-sponsored_amount", "name"),
            },
        ),
        migrations.CreateModel(
            name="FundraisingCampaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Campaign name"),
                ),
                (
                    "campaign_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Campaign number"
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online Campaign"),
                            ("EVENT", "Event-Based Campaign"),
                            ("MAIL", "Mail Campaign"),
                            ("PHONE", "Phone Campaign"),
                            ("FACE_TO_FACE", "Face-to-Face Campaign"),
                            ("CORPORATE", "Corporate Partnership"),
                            ("GRANT", "Grant Application"),
                            ("OTHER", "Other"),
                        ],
                        default="ONLINE",
                        max_length=20,
                        verbose_name="Campaign type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Target amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "amount_raised",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Amount raised",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, verbose_name="Progress notes"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundraising_campaigns",
                        to="finance.donor",
                        verbose_name="Donor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundraising_campaigns",
                        to="finance.sponsor",
                        verbose_name="Sponsor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fundraising Campaign",
                "verbose_name_plural": "Fundraising Campaigns",
                "ordering": ("-start_date", "name"),
            },
        ),
    ]
