# Generated by Django 5.1 on 2026-08-17 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_budget_options_budget_activity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetallocation",
            name="line_item",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Line item"
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="currency",
            field=models.CharField(
                default="USD", max_length=10, verbose_name="Currency"
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Opening balance",
            ),
        ),
        migrations.AddField(
            model_name="financialyear",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="financialyear",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddField(
            model_name="grant",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="grant",
            name="disbursed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Amount disbursed",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grants",
                to="finance.donor",
                verbose_name="Donor",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.budget",
                verbose_name="Budget",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.financialaccount",
                verbose_name="Financial account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Posted at"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Posted by",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Transaction date",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Voided at"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Voided by",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("POSTED", "Posted"),
                    ("PAID", "Paid"),
                    ("RECONCILED", "Reconciled"),
                    ("VOIDED", "Voided"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-transaction_date"], name="finance_tra_transac_a139cf_idx"
            ),
        ),
    ]
