# Generated by Django 5.1 on 2026-08-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_budgetallocation_line_item_financialaccount_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetallocation",
            options={
                "ordering": ("budget", "line_item"),
                "verbose_name": "Budget Allocation",
                "verbose_name_plural": "Budget Allocations",
            },
        ),
        migrations.AlterModelOptions(
            name="financialyear",
            options={
                "ordering": ("name",),
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
            },
        ),
    ]
