# Generated by Django 5.1 on 2026-08-22 02:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityApproval",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("AUDIT_REPORT", "Audit Report"),
                            ("POLICY", "Policy"),
                            ("EXCEPTION", "Exception"),
                            ("RELEASE", "Release Sign-off"),
                            ("CONFIGURATION", "Configuration Change"),
                        ],
                        max_length=20,
                        verbose_name="Approval type",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=50, verbose_name="Reference number"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decision date"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Decision notes"),
                ),
                ("conditions", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "expires_on",
                    models.DateField(blank=True, null=True, verbose_name="Expires on"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_accessibility_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_accessibility_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Approval",
                "verbose_name_plural": "Accessibility Approvals",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("SMALL", "Small (14px)"),
                            ("MEDIUM", "Medium (16px)"),
                            ("LARGE", "Large (18px)"),
                            ("EXTRA_LARGE", "Extra Large (20px)"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Font size",
                    ),
                ),
                (
                    "custom_font_size_px",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Custom font size (px)"
                    ),
                ),
                (
                    "colour_theme",
                    models.CharField(
                        choices=[
                            ("SMALL", "Small (14px)"),
                            ("MEDIUM", "Medium (16px)"),
                            ("LARGE", "Large (18px)"),
                            ("EXTRA_LARGE", "Extra Large (20px)"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="SYSTEM",
                        max_length=30,
                        verbose_name="Colour theme",
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False, verbose_name="High contrast mode"
                    ),
                ),
                (
                    "reduced_motion",
                    models.BooleanField(default=False, verbose_name="Reduced motion"),
                ),
                (
                    "enhanced_focus",
                    models.BooleanField(
                        default=False, verbose_name="Enhanced focus indicators"
                    ),
                ),
                (
                    "keyboard_navigation_enhanced",
                    models.BooleanField(
                        default=False, verbose_name="Enhanced keyboard navigation"
                    ),
                ),
                (
                    "screen_reader_optimized",
                    models.BooleanField(
                        default=False, verbose_name="Screen reader optimizations"
                    ),
                ),
                (
                    "notification_timing",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DELAYED_3S", "3 Seconds"),
                            ("DELAYED_5S", "5 Seconds"),
                            ("DELAYED_10S", "10 Seconds"),
                            ("PERSISTENT", "Persistent Until Dismissed"),
                        ],
                        default="DELAYED_5S",
                        max_length=20,
                        verbose_name="Notification display timing",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Preferred language"
                    ),
                ),
                (
                    "reading_line_height",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=3,
                        verbose_name="Line height multiplier",
                    ),
                ),
                (
                    "reading_letter_spacing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Letter spacing (em)",
                    ),
                ),
                (
                    "reading_word_spacing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Word spacing (em)",
                    ),
                ),
                (
                    "sync_across_devices",
                    models.BooleanField(
                        default=True, verbose_name="Sync across devices"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last synced"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Preference",
                "verbose_name_plural": "Accessibility Preferences",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityStandardRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Standard name"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                (
                    "standard_type",
                    models.CharField(
                        choices=[
                            ("WCAG_2_2_A", "WCAG 2.2 Level A"),
                            ("WCAG_2_2_AA", "WCAG 2.2 Level AA"),
                            ("WCAG_2_2_AAA", "WCAG 2.2 Level AAA"),
                            ("SECTION_508", "Section 508"),
                            ("EN_301_549", "EN 301 549"),
                        ],
                        default="WCAG_2_2_AA",
                        max_length=30,
                        verbose_name="Standard type",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="2.2", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=10,
                        verbose_name="Target conformance level",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "reference_url",
                    models.URLField(blank=True, verbose_name="Reference URL"),
                ),
                ("effective_date", models.DateField(verbose_name="Effective date")),
                (
                    "review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next review date"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Standard",
                "verbose_name_plural": "Accessibility Standards",
                "ordering": ("-effective_date",),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="default",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "target_wcag_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=10,
                        verbose_name="Target WCAG level",
                    ),
                ),
                (
                    "enable_high_contrast",
                    models.BooleanField(
                        default=True, verbose_name="Enable high contrast mode"
                    ),
                ),
                (
                    "enable_font_scaling",
                    models.BooleanField(
                        default=True, verbose_name="Enable font scaling"
                    ),
                ),
                (
                    "enable_reduced_motion",
                    models.BooleanField(
                        default=True, verbose_name="Enable reduced motion"
                    ),
                ),
                (
                    "enable_focus_indicators",
                    models.BooleanField(
                        default=True, verbose_name="Enhanced focus indicators"
                    ),
                ),
                (
                    "enable_skip_links",
                    models.BooleanField(
                        default=True, verbose_name="Enable skip navigation links"
                    ),
                ),
                (
                    "auto_scan_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Automated scanning enabled"
                    ),
                ),
                (
                    "scan_schedule_cron",
                    models.CharField(
                        blank=True,
                        default="0 2 * * *",
                        max_length=100,
                        verbose_name="Scan schedule (cron)",
                    ),
                ),
                (
                    "scan_modules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Modules to scan"
                    ),
                ),
                (
                    "notify_on_critical",
                    models.BooleanField(
                        default=True, verbose_name="Notify on critical issues"
                    ),
                ),
                (
                    "notify_on_regression",
                    models.BooleanField(
                        default=True, verbose_name="Notify on regressions"
                    ),
                ),
                (
                    "report_retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Report retention (days)"
                    ),
                ),
                (
                    "include_in_dashboard",
                    models.BooleanField(
                        default=True, verbose_name="Include in dashboard"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "notification_recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessibility_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Notification recipients",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "default_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accessibility.accessibilitystandardrecord",
                        verbose_name="Default standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Configuration",
                "verbose_name_plural": "Accessibility Configurations",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityAudit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Audit name")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("AUTOMATED", "Automated Scan"),
                            ("MANUAL", "Manual Review"),
                            ("KEYBOARD", "Keyboard Testing"),
                            ("SCREEN_READER", "Screen Reader Testing"),
                            ("USER_TESTING", "User Testing"),
                            ("COLOUR_CONTRAST", "Colour Contrast Analysis"),
                            ("REGRESSION", "Regression Testing"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="Audit type",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("MODULE", "Module"),
                            ("COMPONENT", "Component"),
                            ("PAGE", "Page"),
                            ("WORKFLOW", "Workflow"),
                            ("FULL_SITE", "Full Site"),
                        ],
                        max_length=20,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Component"
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Page URL"
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=10,
                        verbose_name="Target level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                            ("NOT_TESTED", "Not Tested"),
                        ],
                        db_index=True,
                        default="NOT_TESTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "total_criteria_tested",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Criteria tested"
                    ),
                ),
                (
                    "compliant_count",
                    models.PositiveIntegerField(default=0, verbose_name="Compliant"),
                ),
                (
                    "non_compliant_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Non-compliant"
                    ),
                ),
                (
                    "partial_count",
                    models.PositiveIntegerField(default=0, verbose_name="Partial"),
                ),
                (
                    "not_applicable_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Not applicable"
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Overall score (%)",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        upload_to="accessibility_reports/",
                        verbose_name="Report file",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auditor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="accessibility.accessibilitystandardrecord",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Audit",
                "verbose_name_plural": "Accessibility Audits",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityTimeline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STANDARD_CREATED", "Standard Created"),
                            ("STANDARD_UPDATED", "Standard Updated"),
                            ("POLICY_CREATED", "Policy Created"),
                            ("POLICY_UPDATED", "Policy Updated"),
                            ("AUDIT_STARTED", "Audit Started"),
                            ("AUDIT_COMPLETED", "Audit Completed"),
                            ("FINDING_CREATED", "Finding Created"),
                            ("FINDING_UPDATED", "Finding Updated"),
                            ("FINDING_RESOLVED", "Finding Resolved"),
                            ("FINDING_VERIFIED", "Finding Verified"),
                            ("ISSUE_REPORTED", "Issue Reported"),
                            ("ISSUE_ASSIGNED", "Issue Assigned"),
                            ("ISSUE_RESOLVED", "Issue Resolved"),
                            ("RECOMMENDATION_CREATED", "Recommendation Created"),
                            (
                                "RECOMMENDATION_IMPLEMENTED",
                                "Recommendation Implemented",
                            ),
                            ("CONFIGURATION_CHANGED", "Configuration Changed"),
                            ("PREFERENCE_CHANGED", "User Preference Changed"),
                            ("SCAN_TRIGGERED", "Automated Scan Triggered"),
                            ("SCAN_COMPLETED", "Automated Scan Completed"),
                        ],
                        max_length=30,
                        verbose_name="Event type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "event_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Event date"
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Component"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Reference number"
                    ),
                ),
                (
                    "wcag_criterion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="WCAG criterion"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status_before",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Status before"
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Status after"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accessibility_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Timeline Event",
                "verbose_name_plural": "Accessibility Timeline Events",
                "ordering": ("-event_date",),
            },
        ),
        migrations.CreateModel(
            name="WCAGCriterion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "guideline_number",
                    models.CharField(max_length=20, verbose_name="Guideline number"),
                ),
                (
                    "criterion_number",
                    models.CharField(max_length=20, verbose_name="Criterion number"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "principle",
                    models.CharField(
                        choices=[
                            ("PERCEIVABLE", "1. Perceivable"),
                            ("OPERABLE", "2. Operable"),
                            ("UNDERSTANDABLE", "3. Understandable"),
                            ("ROBUST", "4. Robust"),
                        ],
                        max_length=20,
                        verbose_name="Principle",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        max_length=10,
                        verbose_name="Conformance level",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERCEIVABLE", "Perceivable"),
                            ("OPERABLE", "Operable"),
                            ("UNDERSTANDABLE", "Understandable"),
                            ("ROBUST", "Robust"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "understanding_url",
                    models.URLField(blank=True, verbose_name="Understanding doc URL"),
                ),
                (
                    "techniques_url",
                    models.URLField(blank=True, verbose_name="Techniques doc URL"),
                ),
                (
                    "how_to_meet_url",
                    models.URLField(blank=True, verbose_name="How to meet URL"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criteria",
                        to="accessibility.accessibilitystandardrecord",
                        verbose_name="Standard",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "WCAG Criterion",
                "verbose_name_plural": "WCAG Criteria",
                "ordering": ("guideline_number", "criterion_number"),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityRecommendation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Recommendation title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("rationale", models.TextField(blank=True, verbose_name="Rationale")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("FUTURE", "Future Enhancement"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "affected_modules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Affected modules"
                    ),
                ),
                (
                    "estimated_effort",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Estimated effort"
                    ),
                ),
                (
                    "implementation_notes",
                    models.TextField(blank=True, verbose_name="Implementation notes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("VERIFIED", "Verified Fixed"),
                            ("WONT_FIX", "Won't Fix"),
                            ("FALSE_POSITIVE", "False Positive"),
                            ("DEFERRED", "Deferred"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "implemented_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Implemented at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_accessibility_recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Implemented by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "related_criteria",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommendations",
                        to="accessibility.wcagcriterion",
                        verbose_name="Related WCAG criteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Recommendation",
                "verbose_name_plural": "Accessibility Recommendations",
                "ordering": ("priority", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Issue title")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("USER_REPORT", "User Report"),
                            ("AUTOMATED_SCAN", "Automated Scan"),
                            ("MANUAL_TESTING", "Manual Testing"),
                            ("REGRESSION", "Regression"),
                            ("EXTERNAL_AUDIT", "External Audit"),
                        ],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "component",
                    models.CharField(max_length=200, verbose_name="Component"),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Page URL"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "steps_to_reproduce",
                    models.TextField(blank=True, verbose_name="Steps to reproduce"),
                ),
                (
                    "expected_behavior",
                    models.TextField(blank=True, verbose_name="Expected behavior"),
                ),
                (
                    "actual_behavior",
                    models.TextField(blank=True, verbose_name="Actual behavior"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("VERIFIED", "Verified Fixed"),
                            ("WONT_FIX", "Won't Fix"),
                            ("FALSE_POSITIVE", "False Positive"),
                            ("DEFERRED", "Deferred"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                (
                    "is_regression",
                    models.BooleanField(default=False, verbose_name="Is regression"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_accessibility_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "regression_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regressions",
                        to="accessibility.accessibilityissue",
                        verbose_name="Regression from",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_accessibility_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reporter",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_accessibility_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="accessibility.wcagcriterion",
                        verbose_name="WCAG criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Issue",
                "verbose_name_plural": "Accessibility Issues",
                "ordering": ("-severity", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityFinding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component",
                    models.CharField(max_length=200, verbose_name="Component"),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Page URL"
                    ),
                ),
                ("description", models.TextField(verbose_name="Finding description")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("VERIFIED", "Verified Fixed"),
                            ("WONT_FIX", "Won't Fix"),
                            ("FALSE_POSITIVE", "False Positive"),
                            ("DEFERRED", "Deferred"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                            ("NOT_TESTED", "Not Tested"),
                        ],
                        default="NON_COMPLIANT",
                        max_length=20,
                        verbose_name="Compliance status",
                    ),
                ),
                (
                    "code_snippet",
                    models.TextField(blank=True, verbose_name="Code snippet"),
                ),
                (
                    "recommended_fix",
                    models.TextField(blank=True, verbose_name="Recommended fix"),
                ),
                (
                    "wcag_technique_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="WCAG technique reference",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_accessibility_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned to",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="accessibility.accessibilityaudit",
                        verbose_name="Audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_accessibility_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_accessibility_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified by",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="accessibility.wcagcriterion",
                        verbose_name="WCAG criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Finding",
                "verbose_name_plural": "Accessibility Findings",
                "ordering": ("-severity", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityException",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="Module")),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Component"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for exception")),
                (
                    "justification",
                    models.TextField(verbose_name="Technical/business justification"),
                ),
                (
                    "alternative_provided",
                    models.TextField(blank=True, verbose_name="Alternative provided"),
                ),
                ("approved_date", models.DateField(verbose_name="Approved date")),
                ("expires_on", models.DateField(verbose_name="Expires on")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review notes"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_accessibility_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="accessibility.wcagcriterion",
                        verbose_name="WCAG criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Exception",
                "verbose_name_plural": "Accessibility Exceptions",
                "ordering": ("-approved_date",),
            },
        ),
        migrations.CreateModel(
            name="AccessibilityAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Snapshot date")),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "overall_compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Overall compliance score (%)",
                    ),
                ),
                (
                    "critical_issues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Critical issues"
                    ),
                ),
                (
                    "high_issues",
                    models.PositiveIntegerField(default=0, verbose_name="High issues"),
                ),
                (
                    "medium_issues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medium issues"
                    ),
                ),
                (
                    "low_issues",
                    models.PositiveIntegerField(default=0, verbose_name="Low issues"),
                ),
                (
                    "total_issues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total open issues"
                    ),
                ),
                (
                    "resolved_this_period",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Resolved this period"
                    ),
                ),
                (
                    "new_this_period",
                    models.PositiveIntegerField(
                        default=0, verbose_name="New this period"
                    ),
                ),
                (
                    "avg_resolution_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Average resolution (days)",
                    ),
                ),
                (
                    "audit_coverage_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Audit coverage (%)",
                    ),
                ),
                (
                    "keyboard_test_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Keyboard test coverage (%)",
                    ),
                ),
                (
                    "screen_reader_test_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Screen reader test coverage (%)",
                    ),
                ),
                (
                    "user_preference_adoption",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="User preference adoption (%)",
                    ),
                ),
                (
                    "regressions_count",
                    models.PositiveIntegerField(default=0, verbose_name="Regressions"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Analytics",
                "verbose_name_plural": "Accessibility Analytics",
                "ordering": ("-snapshot_date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_date", "module"),
                        name="accessibility_analytics_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityNotification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CRITICAL_ISSUE", "Critical Issue Found"),
                            ("REGRESSION_DETECTED", "Regression Detected"),
                            ("AUDIT_COMPLETED", "Audit Completed"),
                            ("ISSUE_ASSIGNED", "Issue Assigned"),
                            ("ISSUE_RESOLVED", "Issue Resolved"),
                            ("ISSUE_VERIFIED", "Issue Verified"),
                            ("SCAN_SCHEDULED", "Scan Scheduled"),
                            ("SCAN_COMPLETED", "Scan Completed"),
                            ("REVIEW_DUE", "Review Due"),
                            ("COMPLIANCE_CHANGED", "Compliance Status Changed"),
                        ],
                        max_length=30,
                        verbose_name="Event type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(default=False, verbose_name="Sent via email"),
                ),
                (
                    "sent_via_in_app",
                    models.BooleanField(default=True, verbose_name="Sent via in-app"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_notifications_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "related_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="accessibility.accessibilityaudit",
                        verbose_name="Related audit",
                    ),
                ),
                (
                    "related_finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="accessibility.accessibilityfinding",
                        verbose_name="Related finding",
                    ),
                ),
                (
                    "related_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="accessibility.accessibilityissue",
                        verbose_name="Related issue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Notification",
                "verbose_name_plural": "Accessibility Notifications",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="accessibili_recipie_71c2c2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Policy title"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERCEIVABLE", "Perceivable"),
                            ("OPERABLE", "Operable"),
                            ("UNDERSTANDABLE", "Understandable"),
                            ("ROBUST", "Robust"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Requirements"
                    ),
                ),
                ("scope", models.TextField(blank=True, verbose_name="Scope")),
                ("exceptions", models.TextField(blank=True, verbose_name="Exceptions")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved date"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective date")),
                ("review_date", models.DateField(verbose_name="Next review date")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_accessibility_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="accessibility.accessibilitystandardrecord",
                        verbose_name="Accessibility standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Policy",
                "verbose_name_plural": "Accessibility Policies",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="accessibili_categor_25e973_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessibilityComplianceRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="Module")),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Component"
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Page URL"
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A"),
                            ("AA", "Level AA"),
                            ("AAA", "Level AAA"),
                        ],
                        default="AA",
                        max_length=10,
                        verbose_name="Target level",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("NOT_APPLICABLE", "Not Applicable"),
                            ("NOT_TESTED", "Not Tested"),
                        ],
                        db_index=True,
                        default="NOT_TESTED",
                        max_length=20,
                        verbose_name="Compliance status",
                    ),
                ),
                (
                    "last_tested",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last tested"
                    ),
                ),
                (
                    "next_review_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next review due"
                    ),
                ),
                (
                    "open_findings",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Open findings"
                    ),
                ),
                (
                    "critical_findings",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Critical findings"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "exception_granted",
                    models.BooleanField(
                        default=False, verbose_name="Exception granted"
                    ),
                ),
                (
                    "exception_reason",
                    models.TextField(blank=True, verbose_name="Exception reason"),
                ),
                (
                    "exception_expires",
                    models.DateField(
                        blank=True, null=True, verbose_name="Exception expires"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "exception_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_accessibility_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Exception approved by",
                    ),
                ),
                (
                    "last_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_records",
                        to="accessibility.accessibilityaudit",
                        verbose_name="Last audit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_records",
                        to="accessibility.accessibilitystandardrecord",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Compliance Record",
                "verbose_name_plural": "Accessibility Compliance Records",
                "ordering": ("module", "component"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "component", "page_url"),
                        name="accessibility_compliance_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="accessibilityaudit",
            index=models.Index(
                fields=["audit_type", "status"], name="accessibili_audit_t_ba5149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityaudit",
            index=models.Index(
                fields=["module", "status"], name="accessibili_module_8445d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilitytimeline",
            index=models.Index(
                fields=["event_type", "event_date"],
                name="accessibili_event_t_b27fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilitytimeline",
            index=models.Index(
                fields=["module", "event_date"], name="accessibili_module_3fc009_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wcagcriterion",
            constraint=models.UniqueConstraint(
                fields=("standard", "guideline_number", "criterion_number"),
                name="accessibility_wcag_criterion_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityissue",
            index=models.Index(
                fields=["module", "status"], name="accessibili_module_80de88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityissue",
            index=models.Index(
                fields=["status", "due_date"], name="accessibili_status_14d90b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityissue",
            index=models.Index(
                fields=["source", "created_at"], name="accessibili_source_5de2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityfinding",
            index=models.Index(
                fields=["audit", "severity"], name="accessibili_audit_i_e5260b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessibilityfinding",
            index=models.Index(
                fields=["status", "due_date"], name="accessibili_status_b3cd14_idx"
            ),
        ),
    ]
