"""Permission constants and helpers for the ``report_templates`` namespace."""

from __future__ import annotations

from apps.rbac.authorization import user_has_permission

from .constants import REPORT_TEMPLATE_ACTION_PERMISSIONS

REPORT_TEMPLATE_VIEW = REPORT_TEMPLATE_ACTION_PERMISSIONS["view"]
REPORT_TEMPLATE_CREATE = REPORT_TEMPLATE_ACTION_PERMISSIONS["create"]
REPORT_TEMPLATE_UPDATE = REPORT_TEMPLATE_ACTION_PERMISSIONS["update"]
REPORT_TEMPLATE_DELETE = REPORT_TEMPLATE_ACTION_PERMISSIONS["delete"]
REPORT_TEMPLATE_PREVIEW = REPORT_TEMPLATE_ACTION_PERMISSIONS["preview"]
REPORT_TEMPLATE_PUBLISH = REPORT_TEMPLATE_ACTION_PERMISSIONS["publish"]
REPORT_TEMPLATE_ARCHIVE = REPORT_TEMPLATE_ACTION_PERMISSIONS["archive"]
REPORT_TEMPLATE_RESTORE = REPORT_TEMPLATE_ACTION_PERMISSIONS["restore"]
REPORT_TEMPLATE_CLONE = REPORT_TEMPLATE_ACTION_PERMISSIONS["clone"]
REPORT_TEMPLATE_IMPORT = REPORT_TEMPLATE_ACTION_PERMISSIONS["import"]
REPORT_TEMPLATE_EXPORT = REPORT_TEMPLATE_ACTION_PERMISSIONS["export"]
REPORT_TEMPLATE_CONFIGURE = REPORT_TEMPLATE_ACTION_PERMISSIONS["configure"]
REPORT_TEMPLATE_MANAGE = REPORT_TEMPLATE_ACTION_PERMISSIONS["manage"]


def user_can_view_templates(user) -> bool:
    return user_has_permission(user, REPORT_TEMPLATE_VIEW) or user_has_permission(
        user, REPORT_TEMPLATE_MANAGE
    )


def user_can_manage_templates(user) -> bool:
    return user_has_permission(user, REPORT_TEMPLATE_MANAGE)
