# Generated by Django 5.1 on 2026-08-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-starts_at"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="brandasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Brand Asset",
                "verbose_name_plural": "Brand Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="communication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
            },
        ),
        migrations.AlterModelOptions(
            name="communicationattachment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Communication Attachment",
                "verbose_name_plural": "Communication Attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="eventcommunication",
            options={
                "ordering": ["-event_date"],
                "verbose_name": "Event Communication",
                "verbose_name_plural": "Event Communications",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="newsarticle",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-scheduled_send"],
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
            },
        ),
        migrations.AlterModelOptions(
            name="photograph",
            options={
                "ordering": ["-taken_date"],
                "verbose_name": "Photograph",
                "verbose_name_plural": "Photographs",
            },
        ),
        migrations.AlterModelOptions(
            name="pressrelease",
            options={
                "ordering": ["-release_date"],
                "verbose_name": "Press Release",
                "verbose_name_plural": "Press Releases",
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.AlterModelOptions(
            name="socialmediapost",
            options={
                "ordering": ["-scheduled_time"],
                "verbose_name": "Social Media Post",
                "verbose_name_plural": "Social Media Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.AlterModelOptions(
            name="websitepage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Website Page",
                "verbose_name_plural": "Website Pages",
            },
        ),
    ]
