# Generated by Django 5.1 on 2026-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_instances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_PROGRESS", "In Progress"),
                    ("AWAITING_VALIDATION", "Awaiting Validation"),
                    ("VALIDATION_FAILED", "Validation Failed"),
                    ("READY_FOR_SUBMISSION", "Ready for Submission"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("RETURNED_FOR_CORRECTION", "Returned for Correction"),
                    ("RESUBMITTED", "Resubmitted"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("FINALIZED", "Finalized"),
                    ("ARCHIVED", "Archived"),
                    ("RESTORED", "Restored"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
