# Generated by Django 5.1 on 2026-08-10 13:35

import apps.search.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Query"
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=list,
                        help_text="Entity type keys targeted by the search.",
                        validators=[apps.search.validators.validate_entity_type_keys],
                        verbose_name="Entity types",
                    ),
                ),
                (
                    "result_count",
                    models.PositiveIntegerField(default=0, verbose_name="Result count"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Search",
                "verbose_name_plural": "Recent Searches",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "query"), name="uniq_recent_search_user_query"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("query", models.CharField(max_length=200, verbose_name="Query")),
                (
                    "entity_types",
                    models.JSONField(
                        default=list,
                        help_text="Entity type keys targeted by the saved search.",
                        validators=[apps.search.validators.validate_entity_type_keys],
                        verbose_name="Entity types",
                    ),
                ),
                (
                    "result_count",
                    models.PositiveIntegerField(default=0, verbose_name="Result count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="uniq_saved_search_user_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Query"
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=list,
                        help_text="Entity type keys targeted by the query.",
                        verbose_name="Entity types",
                    ),
                ),
                (
                    "result_count",
                    models.PositiveIntegerField(default=0, verbose_name="Result count"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duration (ms)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_query_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query Log",
                "verbose_name_plural": "Search Query Logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at", "user"],
                        name="search_sear_created_7a89f1_idx",
                    )
                ],
            },
        ),
    ]
