# Generated by Django 5.1 on 2026-08-01 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        help_text="Immutable reference number issued by the numbering service.",
                        max_length=60,
                        unique=True,
                        verbose_name="Leadership reference number",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="leadership/profiles/",
                        verbose_name="Profile photograph",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="National ID or identification number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=20, verbose_name="Gender"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "residential_address",
                    models.TextField(blank=True, verbose_name="Residential address"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Emergency contact name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Emergency contact phone",
                    ),
                ),
                (
                    "leadership_level",
                    models.CharField(
                        choices=[
                            ("BOARD_OF_TRUSTEES", "Board of Trustees"),
                            (
                                "NATIONAL_EXECUTIVE_COMMITTEE",
                                "National Executive Committee",
                            ),
                            ("EXECUTIVE_MANAGEMENT", "Executive Management"),
                            ("DIRECTORATE", "Directorate"),
                            ("DEPARTMENT", "Department"),
                            ("REGIONAL", "Regional"),
                            ("DISTRICT", "District"),
                            ("COMMUNITY", "Community"),
                            ("TEAM", "Team"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Leadership level",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Appointment date"
                    ),
                ),
                (
                    "term_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Term expiry date"
                    ),
                ),
                (
                    "terms_completed",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Number of completed terms"
                    ),
                ),
                (
                    "max_terms",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Maximum permitted terms"
                    ),
                ),
                (
                    "term_status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("EXPIRING", "Expiring"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="CURRENT",
                        max_length=20,
                        verbose_name="Term status",
                    ),
                ),
                (
                    "renewal_eligible",
                    models.BooleanField(default=False, verbose_name="Renewal eligible"),
                ),
                (
                    "renewal_status",
                    models.CharField(
                        choices=[
                            ("NOT_ELIGIBLE", "Not Eligible"),
                            ("ELIGIBLE", "Eligible"),
                            ("RENEWED", "Renewed"),
                            ("NOT_RENEWED", "Not Renewed"),
                        ],
                        default="NOT_ELIGIBLE",
                        max_length=20,
                        verbose_name="Renewal status",
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(blank=True, verbose_name="Qualifications"),
                ),
                (
                    "professional_skills",
                    models.TextField(blank=True, verbose_name="Professional skills"),
                ),
                (
                    "areas_of_expertise",
                    models.TextField(blank=True, verbose_name="Areas of expertise"),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOMINATED", "Nominated"),
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPOINTED", "Appointed"),
                            ("ACTIVE", "Active"),
                            ("ACTING", "Acting"),
                            ("PROBATION", "Probation"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("COMPLETED_TERM", "Completed Term"),
                            ("RETIRED", "Retired"),
                            ("RESIGNED", "Resigned"),
                            ("REMOVED", "Removed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="NOMINATED",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The directorate the leader reports into, where applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_profiles_in_directorate",
                        to="organizations.organizationunit",
                        verbose_name="Directorate",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_profiles",
                        to="organizations.organizationunit",
                        verbose_name="Organizational unit",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_profiles",
                        to="organizations.position",
                        verbose_name="Leadership position",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The leader this record reports to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="leadership.leadershipprofile",
                        verbose_name="Immediate supervisor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The authenticated user this leader is linked to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Linked user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Profile",
                "verbose_name_plural": "Leadership Profiles",
                "ordering": ("user__last_name", "user__first_name"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipLeave",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("COMPASSIONATE", "Compassionate Leave"),
                            ("SICK", "Sick Leave"),
                            ("OFFICIAL_TRAVEL", "Official Travel"),
                            ("STUDY", "Study Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("SPECIAL", "Special Leave"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Leave type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("TAKEN", "Taken"),
                            ("ENDED", "Ended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_leave_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Leave",
                "verbose_name_plural": "Leadership Leave",
                "ordering": ("-start_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipKPI",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=200, verbose_name="KPI name")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Category"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Target value",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Actual value",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period start")),
                ("period_end", models.DateField(verbose_name="Period end")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TRACK", "On Track"),
                            ("AT_RISK", "At Risk"),
                            ("OFF_TRACK", "Off Track"),
                            ("ACHIEVED", "Achieved"),
                        ],
                        db_index=True,
                        default="ON_TRACK",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership KPI",
                "verbose_name_plural": "Leadership KPIs",
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipGoal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("title", models.CharField(max_length=200, verbose_name="Goal title")),
                (
                    "strategic_objective",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Strategic objective"
                    ),
                ),
                (
                    "performance_indicator",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Performance indicator"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Target value",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Current value",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ACHIEVED", "Achieved"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Goal",
                "verbose_name_plural": "Leadership Goals",
                "ordering": ("-due_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_LETTER", "Appointment Letter"),
                            ("CONTRACT", "Contract"),
                            ("IDENTIFICATION", "Identification Document"),
                            ("CURRICULUM_VITAE", "Curriculum Vitae"),
                            ("ACADEMIC_CERTIFICATE", "Academic Certificate"),
                            (
                                "PROFESSIONAL_CERTIFICATION",
                                "Professional Certification",
                            ),
                            ("PERFORMANCE_REVIEW", "Performance Review Report"),
                            ("DECLARATION", "Signed Declaration"),
                            ("POLICY_ACKNOWLEDGEMENT", "Policy Acknowledgement"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        upload_to="leadership/documents/", verbose_name="File"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                        verbose_name="Confidentiality",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Document",
                "verbose_name_plural": "Leadership Documents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LeadershipAttendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("MEETING", "Meeting"),
                            ("TRAINING", "Training"),
                            ("EVENT", "Organizational Event"),
                            ("COMMUNITY_ACTIVITY", "Community Activity"),
                            ("PROGRAM_VISIT", "Program Implementation Visit"),
                            ("BOARD_MEETING", "Board Meeting"),
                            ("EXECUTIVE_MEETING", "Executive Meeting"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Attendance type",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Attendance date",
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Activity name"
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Venue / location"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                            ("REMOTE", "Remote"),
                        ],
                        default="PRESENT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Attendance",
                "verbose_name_plural": "Leadership Attendance",
                "ordering": ("-attendance_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipAppointment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        help_text="Immutable reference number issued by the numbering service.",
                        max_length=60,
                        unique=True,
                        verbose_name="Appointment reference number",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("ACTING", "Acting"),
                            ("INTERIM", "Interim"),
                            ("TEMPORARY", "Temporary"),
                            ("HONORARY", "Honorary"),
                            ("CONTRACT", "Contract"),
                        ],
                        db_index=True,
                        default="PERMANENT",
                        max_length=20,
                        verbose_name="Appointment type",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Appointment date",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Effective date",
                    ),
                ),
                (
                    "term_start",
                    models.DateField(blank=True, null=True, verbose_name="Term start"),
                ),
                (
                    "term_end",
                    models.DateField(blank=True, null=True, verbose_name="Term end"),
                ),
                (
                    "renewal_eligible",
                    models.BooleanField(default=False, verbose_name="Renewal eligible"),
                ),
                (
                    "renewal_status",
                    models.CharField(
                        choices=[
                            ("NOT_ELIGIBLE", "Not Eligible"),
                            ("ELIGIBLE", "Eligible"),
                            ("RENEWED", "Renewed"),
                            ("NOT_RENEWED", "Not Renewed"),
                        ],
                        default="NOT_ELIGIBLE",
                        max_length=20,
                        verbose_name="Renewal status",
                    ),
                ),
                (
                    "terms_completed",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Number of completed terms"
                    ),
                ),
                (
                    "max_terms",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Maximum permitted terms"
                    ),
                ),
                (
                    "appointment_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leadership/appointments/letters/",
                        verbose_name="Appointment letter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("RESIGNED", "Resigned"),
                            ("REMOVED", "Removed"),
                            ("REVOKED", "Revoked"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "appointing_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_appointments_authorized",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Appointing authority",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_appointments",
                        to="organizations.organizationunit",
                        verbose_name="Organizational unit",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_appointments",
                        to="organizations.position",
                        verbose_name="Position",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Appointment",
                "verbose_name_plural": "Leadership Appointments",
                "ordering": ("-effective_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("WRITTEN_WARNING", "Written Warning"),
                            ("PERFORMANCE_IMPROVEMENT", "Performance Improvement Plan"),
                            ("INVESTIGATION", "Investigation"),
                            ("SUSPENSION", "Suspension"),
                            ("APPEAL", "Appeal"),
                            ("FINAL_DECISION", "Final Decision"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Record type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "incident_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Incident date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, verbose_name="Resolution / decision"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leadership/disciplinary/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=True,
                        help_text="Restricted to authorized personnel.",
                        verbose_name="Confidential",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Record",
                "verbose_name_plural": "Disciplinary Records",
                "ordering": ("-incident_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CoachingRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LEADERSHIP", "Leadership"),
                            ("PERFORMANCE", "Performance"),
                            ("CAREER", "Career Development"),
                            ("TECHNICAL", "Technical"),
                            ("COMMUNICATION", "Communication"),
                            ("OTHER", "Other"),
                        ],
                        default="LEADERSHIP",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Session date",
                    ),
                ),
                ("objectives", models.TextField(blank=True, verbose_name="Objectives")),
                (
                    "topics_discussed",
                    models.TextField(blank=True, verbose_name="Topics discussed"),
                ),
                (
                    "agreed_actions",
                    models.TextField(blank=True, verbose_name="Agreed actions"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow-up date"
                    ),
                ),
                ("outcomes", models.TextField(blank=True, verbose_name="Outcomes")),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=True,
                        help_text="Restricted to authorized users.",
                        verbose_name="Confidential",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_coaching_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coach",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coaching Record",
                "verbose_name_plural": "Coaching Records",
                "ordering": ("-session_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipScorecard",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("period_start", models.DateField(verbose_name="Period start")),
                ("period_end", models.DateField(verbose_name="Period end")),
                (
                    "attendance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Attendance score",
                    ),
                ),
                (
                    "report_submission_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Report submission score",
                    ),
                ),
                (
                    "goal_achievement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Goal achievement score",
                    ),
                ),
                (
                    "kpi_performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="KPI performance score",
                    ),
                ),
                (
                    "team_supervision_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Team supervision score",
                    ),
                ),
                (
                    "program_oversight_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Program oversight score",
                    ),
                ),
                (
                    "community_engagement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Community engagement score",
                    ),
                ),
                (
                    "stakeholder_engagement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Stakeholder engagement score",
                    ),
                ),
                (
                    "training_participation_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Training participation score",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Overall rating",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Scorecard",
                "verbose_name_plural": "Leadership Scorecards",
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipStatusHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("NOMINATED", "Nominated"),
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPOINTED", "Appointed"),
                            ("ACTIVE", "Active"),
                            ("ACTING", "Acting"),
                            ("PROBATION", "Probation"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("COMPLETED_TERM", "Completed Term"),
                            ("RETIRED", "Retired"),
                            ("RESIGNED", "Resigned"),
                            ("REMOVED", "Removed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=30,
                        verbose_name="From status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("NOMINATED", "Nominated"),
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPOINTED", "Appointed"),
                            ("ACTIVE", "Active"),
                            ("ACTING", "Acting"),
                            ("PROBATION", "Probation"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("COMPLETED_TERM", "Completed Term"),
                            ("RETIRED", "Retired"),
                            ("RESIGNED", "Resigned"),
                            ("REMOVED", "Removed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=30,
                        verbose_name="To status",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Changed at"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Status History",
                "verbose_name_plural": "Leadership Status History",
                "ordering": ("-changed_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeadershipTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("title", models.CharField(max_length=200, verbose_name="Task title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Progress (%)"
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leadership/tasks/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="leadership.leadershipprofile",
                        verbose_name="Assigned leader",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Task",
                "verbose_name_plural": "Leadership Tasks",
                "ordering": ("-due_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="MentorshipRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "development_objectives",
                    models.TextField(blank=True, verbose_name="Development objectives"),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, verbose_name="Progress notes"),
                ),
                ("outcomes", models.TextField(blank=True, verbose_name="Outcomes")),
                ("evaluation", models.TextField(blank=True, verbose_name="Evaluation")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Mentee",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_mentorships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentorship Record",
                "verbose_name_plural": "Mentorship Records",
                "ordering": ("-start_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "review_cycle",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("SEMI_ANNUAL", "Semi-Annual"),
                            ("QUARTERLY", "Quarterly"),
                            ("MONTHLY", "Monthly"),
                            ("AD_HOC", "Ad Hoc"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                        verbose_name="Review cycle",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Review period start")),
                ("period_end", models.DateField(verbose_name="Review period end")),
                (
                    "performance_ratings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of dimension to 1-5 rating.",
                        verbose_name="Performance ratings",
                    ),
                ),
                (
                    "achievements",
                    models.TextField(blank=True, verbose_name="Achievements"),
                ),
                ("challenges", models.TextField(blank=True, verbose_name="Challenges")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "improvement_plan",
                    models.TextField(blank=True, verbose_name="Improvement plan"),
                ),
                (
                    "overall_assessment",
                    models.TextField(blank=True, verbose_name="Overall assessment"),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Unsatisfactory"),
                            (2, "2 - Needs Improvement"),
                            (3, "3 - Meets Expectations"),
                            (4, "4 - Exceeds Expectations"),
                            (5, "5 - Outstanding"),
                        ],
                        null=True,
                        verbose_name="Overall rating",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("RETURNED", "Returned"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="RecognitionRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "award_name",
                    models.CharField(max_length=200, verbose_name="Award name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EXCELLENCE", "Excellence"),
                            ("SERVICE", "Service"),
                            ("INNOVATION", "Innovation"),
                            ("LEADERSHIP", "Leadership"),
                            ("COMMUNITY", "Community Impact"),
                            ("OTHER", "Other"),
                        ],
                        default="LEADERSHIP",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "date_awarded",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date awarded",
                    ),
                ),
                ("citation", models.TextField(blank=True, verbose_name="Citation")),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leadership/recognition/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "awarding_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_awards_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Awarding authority",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognition_records",
                        to="leadership.leadershipprofile",
                        verbose_name="Leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recognition Record",
                "verbose_name_plural": "Recognition Records",
                "ordering": ("-date_awarded", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SuccessionPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "readiness_level",
                    models.CharField(
                        choices=[
                            ("NOT_READY", "Not Ready"),
                            ("DEVELOPING", "Developing"),
                            ("READY", "Ready"),
                            ("IMMEDIATE", "Immediate"),
                        ],
                        default="DEVELOPING",
                        max_length=20,
                        verbose_name="Readiness level",
                    ),
                ),
                (
                    "required_competencies",
                    models.TextField(blank=True, verbose_name="Required competencies"),
                ),
                (
                    "development_activities",
                    models.TextField(blank=True, verbose_name="Development activities"),
                ),
                (
                    "target_readiness_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target readiness date"
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Risk assessment",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "current_holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="succession_plans_holding",
                        to="leadership.leadershipprofile",
                        verbose_name="Current office holder",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succession_plans",
                        to="organizations.position",
                        verbose_name="Critical position",
                    ),
                ),
                (
                    "potential_successors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="succession_candidates",
                        to="leadership.leadershipprofile",
                        verbose_name="Potential successors",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Succession Plan",
                "verbose_name_plural": "Succession Plans",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LeadershipAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("APPOINTED", "Appointed"),
                            ("APPOINTMENT_APPROVED", "Appointment Approved"),
                            ("APPOINTMENT_ACTIVATED", "Appointment Activated"),
                            ("APPOINTMENT_COMPLETED", "Appointment Completed"),
                            ("APPOINTMENT_TERMINATED", "Appointment Terminated"),
                            ("APPOINTMENT_RENEWED", "Appointment Renewed"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("SUPERVISOR_CHANGED", "Supervisor Changed"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("REVIEW_SUBMITTED", "Review Submitted"),
                            ("REVIEW_APPROVED", "Review Approved"),
                            ("REVIEW_RETURNED", "Review Returned"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Audit Record",
                "verbose_name_plural": "Leadership Audit Records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="leadership__entity__29fa7b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="leadershipprofile",
            index=models.Index(
                fields=["status", "leadership_level"],
                name="leadership__status_7b986a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershipkpi",
            constraint=models.UniqueConstraint(
                fields=("profile", "name", "period_start", "period_end"),
                name="unique_leadership_kpi_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershipattendance",
            constraint=models.UniqueConstraint(
                fields=(
                    "profile",
                    "attendance_type",
                    "attendance_date",
                    "activity_name",
                ),
                name="unique_leadership_attendance_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershipappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("profile", "position"),
                name="unique_active_leadership_appointment_per_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershipscorecard",
            constraint=models.UniqueConstraint(
                fields=("profile", "period_start", "period_end"),
                name="unique_leadership_scorecard_per_period",
            ),
        ),
        migrations.AddIndex(
            model_name="leadershipstatushistory",
            index=models.Index(
                fields=["profile", "changed_at"], name="leadership__profile_32e16f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadershiptask",
            index=models.Index(
                fields=["profile", "status"], name="leadership__profile_7fa985_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorshiprecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("mentor", "mentee"),
                name="unique_active_mentorship_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancereview",
            constraint=models.UniqueConstraint(
                fields=("profile", "period_start", "period_end"),
                name="unique_leadership_review_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="successionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("position",),
                name="unique_active_succession_plan_per_position",
            ),
        ),
    ]
