# Generated by Django 5.1 on 2026-08-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0001_initial"),
        ("organizations", "0002_seed_organizations_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipprofile",
            name="community",
            field=models.ForeignKey(
                blank=True,
                help_text="The community the leader is assigned to, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_community",
                to="organizations.organizationunit",
                verbose_name="Community",
            ),
        ),
        migrations.AddField(
            model_name="leadershipprofile",
            name="district",
            field=models.ForeignKey(
                blank=True,
                help_text="The district the leader is assigned to, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_district",
                to="organizations.organizationunit",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="leadershipprofile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="The region the leader is assigned to, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_region",
                to="organizations.organizationunit",
                verbose_name="Region",
            ),
        ),
        migrations.AddField(
            model_name="leadershipprofile",
            name="reporting_line",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array representing the full reporting chain from top to this leader.",
                verbose_name="Reporting line",
            ),
        ),
        migrations.AlterField(
            model_name="leadershipprofile",
            name="leadership_level",
            field=models.CharField(
                choices=[
                    ("BOARD_OF_TRUSTEES", "Board of Trustees"),
                    ("NATIONAL_EXECUTIVE_COMMITTEE", "National Executive Committee"),
                    ("EXECUTIVE_DIRECTOR", "Executive Director"),
                    ("EXECUTIVE_MANAGEMENT", "Executive Management"),
                    ("DIRECTORATE", "Directorate"),
                    ("REGIONAL_COORDINATOR", "Regional Coordinator"),
                    ("DISTRICT_COORDINATOR", "District Coordinator"),
                    ("COMMUNITY_COORDINATOR", "Community Coordinator"),
                    ("TEAM_LEADER", "Team Leader"),
                    ("REPORT_AUTHOR", "Report Author"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Leadership level",
            ),
        ),
    ]
