# Generated by Django 5.1 on 2026-08-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0002_leadershipprofile_community_and_more"),
        ("organizations", "0003_alter_organizationunit_unit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="The department the leader reports into, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_department",
                to="organizations.organizationunit",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="leadershipprofile",
            name="program_technical_management",
            field=models.ForeignKey(
                blank=True,
                help_text="The program/technical management unit the leader belongs to, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_program_technical",
                to="organizations.organizationunit",
                verbose_name="Program and Technical Management",
            ),
        ),
        migrations.AddField(
            model_name="leadershipprofile",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team the leader is assigned to, where applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadership_profiles_in_team",
                to="organizations.organizationunit",
                verbose_name="Team",
            ),
        ),
        migrations.AlterField(
            model_name="leadershipprofile",
            name="leadership_level",
            field=models.CharField(
                choices=[
                    ("GENERAL_ASSEMBLY", "General Assembly"),
                    (
                        "BOARD_OF_DIRECTORS_TRUSTEES",
                        "Board of Directors / Board of Trustees",
                    ),
                    ("NATIONAL_EXECUTIVE_COMMITTEE", "National Executive Committee"),
                    ("EXECUTIVE_MANAGEMENT", "Executive Management"),
                    ("EXECUTIVE_DIRECTOR", "Executive Director"),
                    ("EXECUTIVE_OFFICE", "Executive Office"),
                    ("DIRECTORATE", "Directorate"),
                    ("DEPARTMENT", "Department"),
                    (
                        "PROGRAM_TECHNICAL_MANAGEMENT",
                        "Program and Technical Management",
                    ),
                    ("REGIONAL_COORDINATOR", "Regional Coordinator"),
                    ("DISTRICT_COORDINATOR", "District Coordinator"),
                    ("COMMUNITY_COORDINATOR", "Community Coordinator"),
                    ("TEAM_LEADER", "Team Leader"),
                    ("VOLUNTEER_MEMBER", "Volunteers / Members"),
                    ("REPORT_AUTHOR", "Report Author"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Leadership level",
            ),
        ),
    ]
