# Generated by Django 5.1 on 2026-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0003_leadershipprofile_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadershipprofile",
            name="max_terms",
            field=models.PositiveSmallIntegerField(
                blank=True, default=2, verbose_name="Maximum permitted terms"
            ),
        ),
        migrations.AlterField(
            model_name="leadershipprofile",
            name="renewal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_ELIGIBLE", "Not Eligible"),
                    ("ELIGIBLE", "Eligible"),
                    ("RENEWED", "Renewed"),
                    ("NOT_RENEWED", "Not Renewed"),
                ],
                default="NOT_ELIGIBLE",
                max_length=20,
                verbose_name="Renewal status",
            ),
        ),
        migrations.AlterField(
            model_name="leadershipprofile",
            name="terms_completed",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Number of completed terms"
            ),
        ),
    ]
