# Generated by Django 5.1 on 2026-08-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadership", "0004_alter_leadershipprofile_max_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipprofile",
            name="full_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full name of the leader.",
                max_length=150,
                verbose_name="Full Names",
            ),
        ),
        migrations.AlterField(
            model_name="leadershipprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("NON_BINARY", "Non-Binary"),
                    ("PREFER_NOT_TO_SAY", "Prefer Not to Say"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
    ]
