"""Business services for the Export Engine (Phase 27).

Every state-changing export operation flows through these services so the
invariants hold transactionally:

* a request is created, reference-numbered (centralized service), and given an
  immutable activity timeline,
* generation validates the actor's export + format + source + sensitivity
  permissions and the configured limits before any data is collected,
* generated files are written under the private media tree and served only
  through the authenticated download endpoint,
* expiry/cancel transitions remove the file while the metadata is retained
  for audit history.

All permission gates fail closed: an anonymous or unauthorized actor never
learns what exists.
"""

from __future__ import annotations

import logging
import os
from contextlib import suppress
from datetime import timedelta

from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _

from apps.core.services import BaseService
from apps.references.services import ReferenceNumberService

from .constants import (
    EXPORT_MODULE,
    EXPORT_SCHEME_CODE,
    EXPORT_STORAGE_DIRECTORY,
    ConfidentialityLevel,
    ExportActivityAction,
    ExportFormat,
    ExportStatus,
)
from .exceptions import (
    ExportDownloadDenied,
    ExportExpiredError,
    ExportNotFoundError,
    ExportPermissionDenied,
    ExportProviderError,
    ExportValidationError,
    UnsupportedExportFormat,
)
from .models import ExportActivity, ExportConfiguration, ExportRequest
from .permissions import (
    user_can_export_sensitive,
    user_can_export_source,
    user_can_use_format,
)
from .providers import registry
from .renderers import get_renderer

logger = logging.getLogger(__name__)


def _require(user, *codes: str, exc_class=ExportPermissionDenied) -> None:
    """Raise a domain exception unless the actor holds any of the codes."""
    if not user or not getattr(user, "is_authenticated", False):
        raise exc_class(_("You are not authorized to perform this operation."))
    if getattr(user, "is_superuser", False):
        return
    from apps.rbac.authorization import user_has_permission

    if not any(user_has_permission(user, code) for code in codes):
        raise exc_class(_("You do not have permission to perform this operation."))


def _validate_format_enabled(config: ExportConfiguration, format_code: str) -> None:
    """Raise unless the format is enabled in the engine configuration."""
    enabled = config.enabled_formats or list(ExportFormat.choices)
    if format_code not in enabled:
        raise UnsupportedExportFormat(
            _("The %(format)s format is not enabled for export.")
            % {"format": format_code}
        )


def _client_ip(request) -> str | None:
    if request is None:
        return None
    forwarded = request.META.get("HTTP_X_FORWARDED_FOR")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.META.get("REMOTE_ADDR")


class ExportFileService:
    """Read/write/delete export files on the private media tree."""

    storage_root = os.path.join(
        str(settings.PRIVATE_MEDIA_ROOT), EXPORT_STORAGE_DIRECTORY
    )

    @classmethod
    def _directory(cls, reference_number: str) -> str:
        now = timezone.now()
        return os.path.join(
            cls.storage_root, str(now.year), f"{now.month:02d}", reference_number
        )

    @classmethod
    def save_export_file(
        cls, request: ExportRequest, content: bytes, extension: str
    ) -> str:
        """Persist the generated bytes and return the relative storage path."""
        os.makedirs(cls._directory(request.reference_number), exist_ok=True)
        filename = f"{request.reference_number}.{extension}"
        path = os.path.join(cls._directory(request.reference_number), filename)
        with open(path, "wb") as handle:
            handle.write(content)
        relative = os.path.relpath(path, str(settings.PRIVATE_MEDIA_ROOT))
        return relative.replace("\\", "/")

    @classmethod
    def absolute_path(cls, request: ExportRequest) -> str | None:
        """Resolve the on-disk path of a stored export file."""
        if not request.storage_path:
            return None
        return os.path.join(str(settings.PRIVATE_MEDIA_ROOT), request.storage_path)

    @classmethod
    def file_exists(cls, request: ExportRequest) -> bool:
        path = cls.absolute_path(request)
        return bool(path and os.path.isfile(path))

    @classmethod
    def delete_export_file(cls, request: ExportRequest) -> None:
        """Remove the generated file and its (now empty) directory."""
        path = cls.absolute_path(request)
        if path and os.path.isfile(path):
            try:
                os.remove(path)
            except OSError:
                logger.warning("Could not remove export file %s", path)
        directory = cls._directory(request.reference_number)
        if os.path.isdir(directory) and not os.listdir(directory):
            with suppress(OSError):
                os.rmdir(directory)


class RequestExportService(BaseService):
    """Create a new export request and reserve its reference number."""

    def _execute(
        self,
        *,
        source_type: str,
        format: str,
        filters: dict | None = None,
        selected_columns: list[str] | None = None,
        requested_by=None,
        request_obj=None,
    ) -> ExportRequest:
        actor = requested_by or self.user
        _require(actor, "exports.create", "exports.manage")

        config = ExportConfiguration.load()
        _validate_format_enabled(config, format)
        if not user_can_export_source(actor, source_type):
            raise ExportPermissionDenied(
                _("You do not have permission to export this data source.")
            )
        if not user_can_use_format(actor, format):
            raise ExportPermissionDenied(
                _("You do not have permission to generate %(format)s exports.")
                % {"format": format}
            )

        provider = registry.get(self._provider_key(source_type))
        if provider is None:
            raise ExportProviderError(
                _("No export provider is registered for this data source.")
            )
        if not provider.is_available(actor):
            raise ExportPermissionDenied(
                _("You do not have permission to access this data source.")
            )

        reference = ReferenceNumberService(user=actor).execute(
            module=EXPORT_MODULE,
            record_type=source_type.lower(),
            scheme_code=EXPORT_SCHEME_CODE,
            notes=f"Export request for {source_type} ({format}).",
        )

        request = ExportRequest.objects.create(
            reference_number=reference.reference_number,
            requested_by=actor,
            source_type=source_type,
            format=format,
            filters=filters or {},
            selected_columns=selected_columns or [],
            status=ExportStatus.QUEUED,
        )
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.REQUESTED,
            actor=actor,
            details={"source_type": source_type, "format": format},
            request_obj=request_obj,
        )
        logger.info(
            "Export requested %s (%s %s) by %s",
            request.reference_number,
            source_type,
            format,
            actor,
        )
        return request

    @staticmethod
    def _provider_key(source_type: str) -> str:
        mapping = {
            "REPORT": "reports.template",
            "REGISTER": "registers.register",
            "BENEFICIARY": "beneficiaries.profile",
            "PROGRAM": "programs.program",
            "PROJECT": "programs.project",
            "MEAL": "meal.indicators",
            "MEETING": "meetings.meeting",
            "DOCUMENT": "documents.metadata",
        }
        return mapping.get(source_type, "")


class GenerateExportService(BaseService):
    """Generate the output file for an export request.

    Runs synchronously; the engine is designed so the whole pipeline
    (validate -> collect -> render -> store) stays inside one request.
    """

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        if request.status == ExportStatus.COMPLETED:
            return request
        if request.status == ExportStatus.CANCELLED:
            raise ExportValidationError(_("This export request was cancelled."))

        actor = request.requested_by
        config = ExportConfiguration.load()
        _validate_format_enabled(config, request.format)
        if not user_can_export_source(actor, request.source_type):
            raise ExportPermissionDenied(
                _("You do not have permission to export this data source.")
            )
        if not user_can_use_format(actor, request.format):
            raise ExportPermissionDenied(
                _("You do not have permission to generate %(format)s exports.")
                % {"format": request.format}
            )

        provider = registry.get(self._provider_key(request.source_type))
        if provider is None or not provider.is_available(actor):
            raise ExportProviderError(
                _("The export provider for this data source is unavailable.")
            )

        request.status = ExportStatus.PROCESSING
        request.started_at = timezone.now()
        request.save(update_fields=["status", "started_at", "updated_at"])

        include_sensitive = False
        if request.is_sensitive or (
            provider.source_type in self._sensitive_source_types()
            and provider.can_export_sensitive(actor)
        ):
            include_sensitive = user_can_export_sensitive(actor)
            if not include_sensitive:
                raise ExportPermissionDenied(
                    _("This dataset requires the sensitive-export permission.")
                )

        dataset = provider.build_dataset(
            actor,
            filters=request.filters,
            selected_columns=request.selected_columns,
            include_sensitive=include_sensitive,
        )
        dataset.reference = request.reference_number
        dataset.generated_by = self._display_name(actor)
        dataset.generated_at = timezone.now()
        if (
            request.confidentiality == ConfidentialityLevel.INTERNAL
            and dataset.confidentiality
        ):
            request.confidentiality = dataset.confidentiality
        dataset.confidentiality = request.confidentiality
        dataset.watermark = self._watermark(request, config)
        dataset.page_size = config.default_page_size
        dataset.orientation = config.default_orientation
        dataset.logo_enabled = config.logo_enabled

        renderer = self._get_renderer(request.format)
        result = renderer.render(dataset, config)

        request.record_count = len(dataset.rows)
        request.filename = f"{request.reference_number}.{result.filename}"
        request.mime_type = result.mime_type
        request.file_size = len(result.content)
        request.storage_path = ExportFileService.save_export_file(
            request, result.content, result.filename
        )
        request.status = ExportStatus.COMPLETED
        request.completed_at = timezone.now()
        request.expires_at = timezone.now() + timedelta(
            hours=config.download_expiry_hours
        )
        request.save()

        action = ExportActivityAction.GENERATED
        if include_sensitive:
            action = ExportActivityAction.SENSITIVE_GENERATED
        elif request.record_count > config.max_sync_rows:
            action = ExportActivityAction.BULK_GENERATED
        ExportActivity.record(
            request=request,
            action=action,
            actor=actor,
            details={
                "record_count": request.record_count,
                "file_size": request.file_size,
                "expires_at": (
                    request.expires_at.isoformat() if request.expires_at else ""
                ),
            },
            request_obj=request_obj,
        )
        logger.info(
            "Export %s completed (%s rows, %s bytes)",
            request.reference_number,
            request.record_count,
            request.file_size,
        )
        return request

    @staticmethod
    def _display_name(user) -> str:
        if not user:
            return ""
        return (
            getattr(user, "full_name", "")
            or getattr(user, "get_full_name", lambda: "")()
            or user.email
            or str(user.pk)
        )

    @staticmethod
    def _get_renderer(format_code: str):
        try:
            return get_renderer(format_code)
        except ValueError as exc:
            raise UnsupportedExportFormat(str(exc)) from exc

    @staticmethod
    def _watermark(request: ExportRequest, config: ExportConfiguration) -> str:
        if request.confidentiality in (
            ConfidentialityLevel.RESTRICTED,
            ConfidentialityLevel.CONFIDENTIAL,
            ConfidentialityLevel.HIGHLY_CONFIDENTIAL,
        ):
            return str(request.confidentiality)
        return ""

    @staticmethod
    def _provider_key(source_type: str) -> str:
        mapping = {
            "REPORT": "reports.template",
            "REGISTER": "registers.register",
            "BENEFICIARY": "beneficiaries.profile",
            "PROGRAM": "programs.program",
            "PROJECT": "programs.project",
            "MEAL": "meal.indicators",
            "MEETING": "meetings.meeting",
            "DOCUMENT": "documents.metadata",
        }
        return mapping.get(source_type, "")

    @staticmethod
    def _sensitive_source_types():
        from .constants import SENSITIVE_SOURCE_TYPES

        return SENSITIVE_SOURCE_TYPES


class DownloadExportService(BaseService):
    """Authorize and record the download of a completed export file."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.download", "exports.manage")

        if request.status == ExportStatus.EXPIRED:
            raise ExportExpiredError(_("This export has expired."))
        if request.status != ExportStatus.COMPLETED:
            raise ExportNotFoundError(_("This export is not ready for download."))
        if request.expires_at and request.expires_at <= timezone.now():
            request.mark_expired()
            raise ExportExpiredError(_("This export has expired."))

        if request.requested_by_id != getattr(actor, "id", None):
            from apps.rbac.authorization import user_has_permission

            if not (
                actor.is_superuser
                or user_has_permission(actor, "exports.view_all_history")
            ):
                raise ExportDownloadDenied(
                    _("You may only download your own export requests.")
                )

        if not ExportFileService.file_exists(request):
            raise ExportNotFoundError(_("The export file is no longer available."))

        action = ExportActivityAction.DOWNLOADED
        if request.is_sensitive:
            action = ExportActivityAction.SENSITIVE_DOWNLOADED
        ExportActivity.record(
            request=request,
            action=action,
            actor=actor,
            details={"filename": request.filename, "file_size": request.file_size},
            request_obj=request_obj,
        )
        return request

    def file_handle(self, request: ExportRequest):
        """Return an open file handle for streaming.

        The caller (the download view) hands the handle to ``FileResponse``,
        which closes it once the response is streamed.
        """
        path = ExportFileService.absolute_path(request)
        if not path or not os.path.isfile(path):
            raise ExportNotFoundError(_("The export file is no longer available."))
        return open(path, "rb")  # noqa: SIM115 - ownership transferred to FileResponse


class CancelExportService(BaseService):
    """Cancel a pending/queued/processing export request."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.cancel", "exports.manage")

        if request.is_finished:
            raise ExportValidationError(
                _("Only pending or processing exports can be cancelled.")
            )

        request.status = ExportStatus.CANCELLED
        request.save(update_fields=["status", "updated_at"])
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.CANCELLED,
            actor=actor,
            details={"reason": request.failure_summary or ""},
            request_obj=request_obj,
        )
        return request


class RegenerateExportService(BaseService):
    """Regenerate a previously completed export (same criteria)."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.regenerate", "exports.manage")
        if request.requested_by_id != getattr(actor, "id", None):
            from apps.rbac.authorization import user_has_permission

            if not (
                actor.is_superuser
                or user_has_permission(actor, "exports.view_all_history")
            ):
                raise ExportPermissionDenied(
                    _("You may only regenerate your own export requests.")
                )

        ExportFileService.delete_export_file(request)
        request.status = ExportStatus.QUEUED
        request.failure_summary = ""
        request.error_code = ""
        request.completed_at = None
        request.expires_at = None
        request.storage_path = ""
        request.filename = ""
        request.mime_type = ""
        request.file_size = 0
        request.save()
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.REGENERATED,
            actor=actor,
            details={},
            request_obj=request_obj,
        )
        return GenerateExportService(user=actor).execute(
            request, request_obj=request_obj
        )


class ExpireStaleExportsService(BaseService):
    """Mark completed exports past their download expiry as expired."""

    def _execute(self, *, limit: int = 500) -> int:
        now = timezone.now()
        stale = ExportRequest.objects.filter(
            status=ExportStatus.COMPLETED,
            expires_at__isnull=False,
            expires_at__lte=now,
        )[:limit]
        expired = 0
        for request in stale:
            request.mark_expired()
            expired += 1
        return expired
