"""Business services for the Export Engine (Phase 27).

Every state-changing export operation flows through these services so the
invariants hold transactionally:

* a request is created, reference-numbered (centralized service), and given an
  immutable activity timeline,
* generation validates the actor's export + format + source + sensitivity
  permissions and the configured limits before any data is collected,
* generated files are written under the private media tree and served only
  through the authenticated download endpoint,
* expiry/cancel transitions remove the file while the metadata is retained
  for audit history.

All permission gates fail closed: an anonymous or unauthorized actor never
learns what exists.
"""

from __future__ import annotations

import logging
import os
from contextlib import suppress
from datetime import timedelta

from django.conf import settings
from django.db.models import Avg, Count, Q, Sum
from django.utils import timezone
from django.utils.translation import gettext as _

from apps.core.services import BaseService
from apps.rbac.authorization import user_has_permission
from apps.references.services import ReferenceNumberService

from .constants import (
    EXPORT_MODULE,
    EXPORT_SCHEME_CODE,
    EXPORT_STORAGE_DIRECTORY,
    ConfidentialityLevel,
    ExportActivityAction,
    ExportFormat,
    ExportStatus,
)
from .exceptions import (
    ExportDownloadDenied,
    ExportExpiredError,
    ExportNotFoundError,
    ExportPermissionDenied,
    ExportProviderError,
    ExportValidationError,
    UnsupportedExportFormat,
)
from .models import ExportActivity, ExportConfiguration, ExportRequest
from .permissions import (
    user_can_export_sensitive,
    user_can_export_source,
    user_can_use_format,
)
from .providers import registry
from .renderers import get_renderer

logger = logging.getLogger(__name__)


def _require(user, *codes: str, exc_class=ExportPermissionDenied) -> None:
    """Raise a domain exception unless the actor holds any of the codes."""
    if not user or not getattr(user, "is_authenticated", False):
        raise exc_class(_("You are not authorized to perform this operation."))
    if getattr(user, "is_superuser", False):
        return
    if not any(user_has_permission(user, code) for code in codes):
        raise exc_class(_("You do not have permission to perform this operation."))


def _validate_format_enabled(config: ExportConfiguration, format_code: str) -> None:
    """Raise unless the format is enabled in the engine configuration."""
    enabled = config.enabled_formats or list(ExportFormat.choices)
    if format_code not in enabled:
        raise UnsupportedExportFormat(
            _("The %(format)s format is not enabled for export.")
            % {"format": format_code}
        )


def _client_ip(request) -> str | None:
    if request is None:
        return None
    forwarded = request.META.get("HTTP_X_FORWARDED_FOR")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.META.get("REMOTE_ADDR")


class ExportFileService:
    """Read/write/delete export files on the private media tree."""

    storage_root = os.path.join(
        str(settings.PRIVATE_MEDIA_ROOT), EXPORT_STORAGE_DIRECTORY
    )

    @classmethod
    def _directory(cls, reference_number: str) -> str:
        now = timezone.now()
        return os.path.join(
            cls.storage_root, str(now.year), f"{now.month:02d}", reference_number
        )

    @classmethod
    def save_export_file(
        cls, request: ExportRequest, content: bytes, extension: str
    ) -> str:
        """Persist the generated bytes and return the relative storage path."""
        os.makedirs(cls._directory(request.reference_number), exist_ok=True)
        filename = f"{request.reference_number}.{extension}"
        path = os.path.join(cls._directory(request.reference_number), filename)
        with open(path, "wb") as handle:
            handle.write(content)
        relative = os.path.relpath(path, str(settings.PRIVATE_MEDIA_ROOT))
        return relative.replace("\\", "/")

    @classmethod
    def absolute_path(cls, request: ExportRequest) -> str | None:
        """Resolve the on-disk path of a stored export file."""
        if not request.storage_path:
            return None
        return os.path.join(str(settings.PRIVATE_MEDIA_ROOT), request.storage_path)

    @classmethod
    def file_exists(cls, request: ExportRequest) -> bool:
        path = cls.absolute_path(request)
        return bool(path and os.path.isfile(path))

    @classmethod
    def delete_export_file(cls, request: ExportRequest) -> None:
        """Remove the generated file and its (now empty) directory."""
        path = cls.absolute_path(request)
        if path and os.path.isfile(path):
            try:
                os.remove(path)
            except OSError:
                logger.warning("Could not remove export file %s", path)
        directory = cls._directory(request.reference_number)
        if os.path.isdir(directory) and not os.listdir(directory):
            with suppress(OSError):
                os.rmdir(directory)


class RequestExportService(BaseService):
    """Create a new export request and reserve its reference number."""

    def _execute(
        self,
        *,
        source_type: str,
        format: str,
        filters: dict | None = None,
        selected_columns: list[str] | None = None,
        requested_by=None,
        request_obj=None,
    ) -> ExportRequest:
        actor = requested_by or self.user
        _require(actor, "exports.create", "exports.manage")

        config = ExportConfiguration.load()
        _validate_format_enabled(config, format)
        if not user_can_export_source(actor, source_type):
            raise ExportPermissionDenied(
                _("You do not have permission to export this data source.")
            )
        if not user_can_use_format(actor, format):
            raise ExportPermissionDenied(
                _("You do not have permission to generate %(format)s exports.")
                % {"format": format}
            )

        provider = registry.get(self._provider_key(source_type))
        if provider is None:
            raise ExportProviderError(
                _("No export provider is registered for this data source.")
            )
        if not provider.is_available(actor):
            raise ExportPermissionDenied(
                _("You do not have permission to access this data source.")
            )

        reference = ReferenceNumberService(user=actor).execute(
            module=EXPORT_MODULE,
            record_type=source_type.lower(),
            scheme_code=EXPORT_SCHEME_CODE,
            notes=f"Export request for {source_type} ({format}).",
        )

        request = ExportRequest.objects.create(
            reference_number=reference.reference_number,
            requested_by=actor,
            source_type=source_type,
            format=format,
            filters=filters or {},
            selected_columns=selected_columns or [],
            status=ExportStatus.QUEUED,
        )
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.REQUESTED,
            actor=actor,
            details={"source_type": source_type, "format": format},
            request_obj=request_obj,
        )
        logger.info(
            "Export requested %s (%s %s) by %s",
            request.reference_number,
            source_type,
            format,
            actor,
        )
        return request

    @staticmethod
    def _provider_key(source_type: str) -> str:
        mapping = {
            "REPORT": "reports.template",
            "REGISTER": "registers.register",
            "BENEFICIARY": "beneficiaries.profile",
            "PROGRAM": "programs.program",
            "PROJECT": "programs.project",
            "MEAL": "meal.indicators",
            "MEETING": "meetings.meeting",
            "DOCUMENT": "documents.metadata",
        }
        return mapping.get(source_type, "")


class GenerateExportService(BaseService):
    """Generate the output file for an export request.

    Runs synchronously; the engine is designed so the whole pipeline
    (validate -> collect -> render -> store) stays inside one request.
    """

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        if request.status == ExportStatus.COMPLETED:
            return request
        if request.status == ExportStatus.CANCELLED:
            raise ExportValidationError(_("This export request was cancelled."))

        actor = request.requested_by
        config = ExportConfiguration.load()
        _validate_format_enabled(config, request.format)
        if not user_can_export_source(actor, request.source_type):
            raise ExportPermissionDenied(
                _("You do not have permission to export this data source.")
            )
        if not user_can_use_format(actor, request.format):
            raise ExportPermissionDenied(
                _("You do not have permission to generate %(format)s exports.")
                % {"format": request.format}
            )

        provider = registry.get(self._provider_key(request.source_type))
        if provider is None or not provider.is_available(actor):
            raise ExportProviderError(
                _("The export provider for this data source is unavailable.")
            )

        request.status = ExportStatus.PROCESSING
        request.started_at = timezone.now()
        request.save(update_fields=["status", "started_at", "updated_at"])

        include_sensitive = False
        if request.is_sensitive or (
            provider.source_type in self._sensitive_source_types()
            and provider.can_export_sensitive(actor)
        ):
            include_sensitive = user_can_export_sensitive(actor)
            if not include_sensitive:
                raise ExportPermissionDenied(
                    _("This dataset requires the sensitive-export permission.")
                )

        dataset = provider.build_dataset(
            actor,
            filters=request.filters,
            selected_columns=request.selected_columns,
            include_sensitive=include_sensitive,
        )
        dataset.reference = request.reference_number
        dataset.generated_by = self._display_name(actor)
        dataset.generated_at = timezone.now()
        if (
            request.confidentiality == ConfidentialityLevel.INTERNAL
            and dataset.confidentiality
        ):
            request.confidentiality = dataset.confidentiality
        dataset.confidentiality = request.confidentiality
        dataset.watermark = self._watermark(request, config)
        dataset.page_size = config.default_page_size
        dataset.orientation = config.default_orientation
        dataset.logo_enabled = config.logo_enabled

        # Add digital verification data
        if request.qr_code:
            dataset.qr_code = request.qr_code
        if request.barcode:
            dataset.barcode = request.barcode
        if request.digital_signature:
            dataset.digital_signature = request.digital_signature

        renderer = self._get_renderer(request.format)
        result = renderer.render(dataset, config)

        request.record_count = len(dataset.rows)
        request.filename = f"{request.reference_number}.{result.filename}"
        request.mime_type = result.mime_type
        request.file_size = len(result.content)
        request.storage_path = ExportFileService.save_export_file(
            request, result.content, result.filename
        )
        request.status = ExportStatus.COMPLETED
        request.completed_at = timezone.now()
        request.expires_at = timezone.now() + timedelta(
            hours=config.download_expiry_hours
        )
        request.save()

        action = ExportActivityAction.GENERATED
        if include_sensitive:
            action = ExportActivityAction.SENSITIVE_GENERATED
        elif request.record_count > config.max_sync_rows:
            action = ExportActivityAction.BULK_GENERATED
        ExportActivity.record(
            request=request,
            action=action,
            actor=actor,
            details={
                "record_count": request.record_count,
                "file_size": request.file_size,
                "expires_at": (
                    request.expires_at.isoformat() if request.expires_at else ""
                ),
            },
            request_obj=request_obj,
        )
        logger.info(
            "Export %s completed (%s rows, %s bytes)",
            request.reference_number,
            request.record_count,
            request.file_size,
        )
        # Send notification
        ExportNotificationService.notify_export_completed(request, actor)
        return request

    @staticmethod
    def _display_name(user) -> str:
        if not user:
            return ""
        return (
            getattr(user, "full_name", "")
            or getattr(user, "get_full_name", lambda: "")()
            or user.email
            or str(user.pk)
        )

    @staticmethod
    def _get_renderer(format_code: str):
        try:
            return get_renderer(format_code)
        except ValueError as exc:
            raise UnsupportedExportFormat(str(exc)) from exc

    @staticmethod
    def _watermark(request: ExportRequest, config: ExportConfiguration) -> str:
        if request.confidentiality in (
            ConfidentialityLevel.RESTRICTED,
            ConfidentialityLevel.CONFIDENTIAL,
            ConfidentialityLevel.HIGHLY_CONFIDENTIAL,
        ):
            return str(request.confidentiality)
        return ""

    @staticmethod
    def _provider_key(source_type: str) -> str:
        mapping = {
            "REPORT": "reports.template",
            "REGISTER": "registers.register",
            "BENEFICIARY": "beneficiaries.profile",
            "PROGRAM": "programs.program",
            "PROJECT": "programs.project",
            "MEAL": "meal.indicators",
            "MEETING": "meetings.meeting",
            "DOCUMENT": "documents.metadata",
        }
        return mapping.get(source_type, "")

    @staticmethod
    def _sensitive_source_types():
        from .constants import SENSITIVE_SOURCE_TYPES

        return SENSITIVE_SOURCE_TYPES


class DownloadExportService(BaseService):
    """Authorize and record the download of a completed export file."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.download", "exports.manage")

        if request.status == ExportStatus.EXPIRED:
            raise ExportExpiredError(_("This export has expired."))
        if request.status != ExportStatus.COMPLETED:
            raise ExportNotFoundError(_("This export is not ready for download."))
        if request.expires_at and request.expires_at <= timezone.now():
            request.mark_expired()
            raise ExportExpiredError(_("This export has expired."))

        if (
            request.requested_by_id != getattr(actor, "id", None)
            and not actor.is_superuser
            and not user_has_permission(actor, "exports.view_all_history")
        ):
            raise ExportDownloadDenied(
                _("You may only download your own export requests.")
            )

        if not ExportFileService.file_exists(request):
            raise ExportNotFoundError(_("The export file is no longer available."))

        action = ExportActivityAction.DOWNLOADED
        if request.is_sensitive:
            action = ExportActivityAction.SENSITIVE_DOWNLOADED
        ExportActivity.record(
            request=request,
            action=action,
            actor=actor,
            details={"filename": request.filename, "file_size": request.file_size},
            request_obj=request_obj,
        )
        return request

    def file_handle(self, request: ExportRequest):
        """Return an open file handle for streaming.

        The caller (the download view) hands the handle to ``FileResponse``,
        which closes it once the response is streamed.
        """
        path = ExportFileService.absolute_path(request)
        if not path or not os.path.isfile(path):
            raise ExportNotFoundError(_("The export file is no longer available."))
        return open(path, "rb")  # noqa: SIM115 - ownership transferred to FileResponse


class CancelExportService(BaseService):
    """Cancel a pending/queued/processing export request."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.cancel", "exports.manage")

        if request.is_finished:
            raise ExportValidationError(
                _("Only pending or processing exports can be cancelled.")
            )

        request.status = ExportStatus.CANCELLED
        request.save(update_fields=["status", "updated_at"])
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.CANCELLED,
            actor=actor,
            details={"reason": request.failure_summary or ""},
            request_obj=request_obj,
        )
        return request


class RegenerateExportService(BaseService):
    """Regenerate a previously completed export (same criteria)."""

    def _execute(
        self, export_request: ExportRequest, *, request_obj=None
    ) -> ExportRequest:
        request = export_request
        actor = self.user
        _require(actor, "exports.regenerate", "exports.manage")
        if (
            request.requested_by_id != getattr(actor, "id", None)
            and not actor.is_superuser
            and not user_has_permission(actor, "exports.view_all_history")
        ):
            raise ExportPermissionDenied(
                _("You may only regenerate your own export requests.")
            )

        ExportFileService.delete_export_file(request)
        request.status = ExportStatus.QUEUED
        request.failure_summary = ""
        request.error_code = ""
        request.completed_at = None
        request.expires_at = None
        request.storage_path = ""
        request.filename = ""
        request.mime_type = ""
        request.file_size = 0
        request.save()
        ExportActivity.record(
            request=request,
            action=ExportActivityAction.REGENERATED,
            actor=actor,
            details={},
            request_obj=request_obj,
        )
        return GenerateExportService(user=actor).execute(
            request, request_obj=request_obj
        )


class ExpireStaleExportsService(BaseService):
    """Mark completed exports past their download expiry as expired."""

    def _execute(self, *, limit: int = 500) -> int:
        now = timezone.now()
        stale = ExportRequest.objects.filter(
            status=ExportStatus.COMPLETED,
            expires_at__isnull=False,
            expires_at__lte=now,
        )[:limit]
        expired = 0
        for request in stale:
            request.mark_expired()
            ExportNotificationService.notify_export_expired(request)
            expired += 1
        return expired


class QueueExportService(BaseService):
    """Enqueue an export request for batch/async processing."""

    def _execute(
        self,
        export_request: ExportRequest,
        *,
        priority: int = 0,
        scheduled_for=None,
        request_obj=None,
    ):
        from .models import ExportQueue, ExportQueueStatus

        request = export_request
        actor = self.user
        _require(actor, "exports.create", "exports.manage")

        queue_entry, created = ExportQueue.objects.get_or_create(
            export_request=request,
            defaults={
                "status": ExportQueueStatus.PENDING,
                "priority": priority,
                "scheduled_for": scheduled_for,
            },
        )
        if not created:
            queue_entry.status = ExportQueueStatus.PENDING
            queue_entry.priority = priority
            queue_entry.scheduled_for = scheduled_for
            queue_entry.attempts = 0
            queue_entry.save()

        ExportActivity.record(
            request=request,
            action=ExportActivityAction.QUEUED,
            actor=actor,
            details={
                "priority": priority,
                "scheduled_for": str(scheduled_for) if scheduled_for else "",
            },
            request_obj=request_obj,
        )
        logger.info("Export %s queued for batch processing", request.reference_number)
        return queue_entry


class ProcessExportQueueService(BaseService):
    """Process pending export queue entries (management command entry point)."""

    def _execute(self, *, limit: int = 50) -> dict:
        from django.db import models

        from .models import ExportQueue, ExportQueueStatus

        now = timezone.now()
        pending = (
            ExportQueue.objects.filter(
                status__in=[ExportQueueStatus.PENDING, ExportQueueStatus.PROCESSING],
                attempts__lt=models.F("max_attempts"),
            )
            .filter(
                models.Q(scheduled_for__isnull=True) | models.Q(scheduled_for__lte=now)
            )
            .order_by("-priority", "scheduled_for", "created_at")[:limit]
        )

        processed = 0
        succeeded = 0
        failed = 0

        for queue_entry in pending:
            if queue_entry.status == ExportQueueStatus.PROCESSING:
                continue

            queue_entry.status = ExportQueueStatus.PROCESSING
            queue_entry.started_at = timezone.now()
            queue_entry.attempts += 1
            fields = ["status", "started_at", "attempts", "updated_at"]
            queue_entry.save(update_fields=fields)

            try:
                # Use the original requester's permissions
                actor = queue_entry.export_request.requested_by
                GenerateExportService(user=actor).execute(
                    queue_entry.export_request, request_obj=None
                )
                queue_entry.status = ExportQueueStatus.COMPLETED
                queue_entry.completed_at = timezone.now()
                queue_entry.save(update_fields=["status", "completed_at", "updated_at"])
                ExportActivity.record(
                    request=queue_entry.export_request,
                    action=ExportActivityAction.BATCH_COMPLETED,
                    actor=actor,
                    details={"queue_entry": str(queue_entry.pk)},
                )
                ExportNotificationService.notify_batch_completed(
                    queue_entry.export_request, actor
                )
                succeeded += 1
            except Exception as exc:
                queue_entry.status = ExportQueueStatus.FAILED
                queue_entry.failure_summary = str(exc)
                queue_entry.error_code = exc.__class__.__name__
                fields = ["status", "failure_summary", "error_code", "updated_at"]
                queue_entry.save(update_fields=fields)
                ExportActivity.record(
                    request=queue_entry.export_request,
                    action=ExportActivityAction.FAILED,
                    actor=queue_entry.export_request.requested_by,
                    details={"error": str(exc), "queue_entry": str(queue_entry.pk)},
                )
                ExportNotificationService.notify_export_failed(
                    queue_entry.export_request, str(exc)
                )
                failed += 1
                logger.error(
                    "Batch export %s failed: %s",
                    queue_entry.export_request.reference_number,
                    exc,
                )

            processed += 1

        return {"processed": processed, "succeeded": succeeded, "failed": failed}


class BulkExportService(BaseService):
    """Create and queue multiple export requests for bulk processing."""

    def _execute(
        self,
        *,
        source_type: str,
        format: str,
        filters_list: list[dict],
        requested_by=None,
        request_obj=None,
    ) -> list[ExportRequest]:
        actor = requested_by or self.user
        _require(actor, "exports.export_bulk", "exports.manage")

        config = ExportConfiguration.load()
        _validate_format_enabled(config, format)
        if not user_can_export_source(actor, source_type):
            raise ExportPermissionDenied(
                _("You do not have permission to export this data source.")
            )
        if not user_can_use_format(actor, format):
            raise ExportPermissionDenied(
                _("You do not have permission to generate %(format)s exports.")
                % {"format": format}
            )

        provider = registry.get(self._provider_key(source_type))
        if provider is None or not provider.is_available(actor):
            raise ExportProviderError(
                _("No export provider is registered for this data source.")
            )

        requests = []
        for idx, filters in enumerate(filters_list):
            reference = ReferenceNumberService(user=actor).execute(
                module=EXPORT_MODULE,
                record_type=source_type.lower(),
                scheme_code=EXPORT_SCHEME_CODE,
                notes=(
                    f"Bulk export {idx + 1}/{len(filters_list)} "
                    f"for {source_type} ({format})."
                ),
            )

            request = ExportRequest.objects.create(
                reference_number=reference.reference_number,
                requested_by=actor,
                source_type=source_type,
                format=format,
                filters=filters,
                selected_columns=[],
                status=ExportStatus.QUEUED,
                is_bulk=True,
            )
            ExportActivity.record(
                request=request,
                action=ExportActivityAction.REQUESTED,
                actor=actor,
                details={
                    "source_type": source_type,
                    "format": format,
                    "bulk_index": idx,
                },
                request_obj=request_obj,
            )
            # Queue for batch processing
            QueueExportService(user=actor).execute(
                request, priority=-idx, request_obj=request_obj
            )
            requests.append(request)

        logger.info(
            "Bulk export created: %s requests for %s (%s)",
            len(requests),
            source_type,
            format,
        )
        return requests

    @staticmethod
    def _provider_key(source_type: str) -> str:
        mapping = {
            "REPORT": "reports.template",
            "REGISTER": "registers.register",
            "BENEFICIARY": "beneficiaries.profile",
            "PROGRAM": "programs.program",
            "PROJECT": "programs.project",
            "MEAL": "meal.indicators",
            "MEETING": "meetings.meeting",
            "DOCUMENT": "documents.metadata",
        }
        return mapping.get(source_type, "")


class DigitalSignatureService:
    """Service for generating and verifying digital signatures on exports."""

    @staticmethod
    def sign_export(export_request, user, signature_data: dict | None = None) -> dict:
        """Add a digital signature to an export request."""
        from django.utils import timezone

        signature = {
            "signed_by": str(user.pk),
            "signed_by_name": getattr(user, "full_name", "")
            or getattr(user, "get_full_name", lambda: "")()
            or user.email,
            "signed_at": timezone.now().isoformat(),
            "reference_number": export_request.reference_number,
            "file_hash": DigitalSignatureService._compute_file_hash(export_request),
            "role": getattr(user, "role", ""),
            "data": signature_data or {},
        }
        export_request.digital_signature = signature
        export_request.save(update_fields=["digital_signature", "updated_at"])
        return signature

    @staticmethod
    def verify_signature(export_request) -> dict:
        """Verify the digital signature on an export request."""
        signature = export_request.digital_signature or {}
        if not signature:
            return {"valid": False, "reason": "No signature present"}

        current_hash = DigitalSignatureService._compute_file_hash(export_request)
        original_hash = signature.get("file_hash", "")

        return {
            "valid": current_hash == original_hash,
            "signed_by": signature.get("signed_by_name"),
            "signed_at": signature.get("signed_at"),
            "file_integrity": current_hash == original_hash,
            "reference_match": (
                signature.get("reference_number") == export_request.reference_number
            ),
        }

    @staticmethod
    def _compute_file_hash(export_request) -> str:
        """Compute SHA-256 hash of the export file."""
        import hashlib

        from .services import ExportFileService

        path = ExportFileService.absolute_path(export_request)
        if not path or not os.path.isfile(path):
            return ""
        hasher = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                hasher.update(chunk)
        return hasher.hexdigest()


class QRCodeService:
    """Service for generating QR codes for export verification."""

    @staticmethod
    def generate_verification_qr(export_request, base_url: str | None = None) -> str:
        """Generate a QR code linking to the export verification page."""
        try:
            import qrcode

            if base_url is None:
                from django.conf import settings

                base_url = getattr(
                    settings, "EXPORT_VERIFICATION_BASE_URL", "https://sitadc.org"
                )

            verify_url = f"{base_url}/exports/verify/{export_request.reference_number}/"

            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=4,
            )
            qr.add_data(verify_url)
            qr.make(fit=True)

            img = qr.make_image(fill_color="black", back_color="white")

            import io

            buffer = io.BytesIO()
            img.save(buffer, format="PNG")
            buffer.seek(0)

            import base64

            qr_b64 = base64.b64encode(buffer.getvalue()).decode("ascii")
            export_request.qr_code = qr_b64
            export_request.save(update_fields=["qr_code", "updated_at"])
            return qr_b64
        except ImportError:
            logger.warning("qrcode library not available; QR code generation skipped")
            return ""

    @staticmethod
    def embed_qr_in_pdf(dataset, qr_data: str) -> bytes:
        """Embed a QR code image into the PDF dataset."""
        # This would be handled by the PDF renderer
        return qr_data


class BarcodeService:
    """Service for generating barcodes for export tracking."""

    @staticmethod
    def generate_barcode(export_request, barcode_type: str = "CODE128") -> str:
        """Generate a barcode for the export request."""
        try:
            import barcode
            from barcode.writer import ImageWriter

            code = export_request.reference_number
            barcode_class = barcode.get_barcode_class(barcode_type)
            bc = barcode_class(code, writer=ImageWriter())

            import io

            buffer = io.BytesIO()
            bc.write(buffer)
            buffer.seek(0)

            import base64

            barcode_b64 = base64.b64encode(buffer.getvalue()).decode("ascii")
            export_request.barcode = barcode_b64
            export_request.save(update_fields=["barcode", "updated_at"])
            return barcode_b64
        except ImportError:
            logger.warning(
                "python-barcode library not available; " "barcode generation skipped"
            )
            return ""


class ExportNotificationService:
    """Service for sending export-related notifications."""

    @staticmethod
    def _send_notification(
        user,
        title: str,
        message: str,
        notification_type: str = "INFO",
        source_app: str = "exports",
        source_model: str = "ExportRequest",
        source_object_id: str = "",
        source_object_reference: str = "",
        **kwargs,
    ):
        """Send a notification via the notifications module."""
        try:
            from apps.notifications.constants import DeliveryChannel
            from apps.notifications.services import NotificationService

            # Create in-app notification
            NotificationService(user=user).execute(
                recipient=user,
                title=title,
                message=message,
                notification_type=notification_type,
                channels=[DeliveryChannel.IN_APP],
                source_app=source_app,
                source_model=source_model,
                source_object_id=source_object_id,
                source_object_reference=source_object_reference,
                **kwargs,
            )
        except Exception as exc:
            logger.warning("Failed to send export notification: %s", exc)

    @classmethod
    def notify_export_completed(cls, export_request, actor=None):
        """Notify when an export is completed successfully."""
        if actor is None:
            actor = export_request.requested_by

        fmt = export_request.get_format_display()
        cls._send_notification(
            user=actor,
            title="Export Completed",
            message=(
                f'Your export "{export_request.reference_number}" ({fmt}) '
                "is ready for download."
            ),
            notification_type="SUCCESS",
            source_object_id=str(export_request.pk),
            source_object_reference=export_request.reference_number,
            priority="normal",
        )

    @classmethod
    def notify_export_failed(cls, export_request, error: str, actor=None):
        """Notify when an export fails."""
        if actor is None:
            actor = export_request.requested_by

        cls._send_notification(
            user=actor,
            title="Export Failed",
            message=f'Your export "{export_request.reference_number}" failed: {error}',
            notification_type="ERROR",
            source_object_id=str(export_request.pk),
            source_object_reference=export_request.reference_number,
            priority="high",
        )

    @classmethod
    def notify_export_ready(cls, export_request, actor=None):
        """Notify when an export is ready for download (alias for completed)."""
        cls.notify_export_completed(export_request, actor)

    @classmethod
    def notify_batch_completed(cls, export_request, actor=None):
        """Notify when a batch export is completed."""
        if actor is None:
            actor = export_request.requested_by

        cls._send_notification(
            user=actor,
            title="Batch Export Completed",
            message=f'Batch export "{export_request.reference_number}" '
            "has been processed.",
            notification_type="SUCCESS",
            source_object_id=str(export_request.pk),
            source_object_reference=export_request.reference_number,
            priority="normal",
        )

    @classmethod
    def notify_scheduled_run(cls, scheduled_export, export_request=None):
        """Notify when a scheduled export runs."""
        user = scheduled_export.created_by

        cls._send_notification(
            user=user,
            title="Scheduled Export Executed",
            message=f'Scheduled export "{scheduled_export.name}" has been queued.',
            notification_type="INFO",
            source_app="exports",
            source_model="ScheduledExport",
            source_object_id=str(scheduled_export.pk),
            source_object_reference=scheduled_export.name,
            priority="normal",
        )

    @classmethod
    def notify_export_expired(cls, export_request, actor=None):
        """Notify when an export has expired."""
        if actor is None:
            actor = export_request.requested_by

        cls._send_notification(
            user=actor,
            title="Export Expired",
            message=(
                f'Your export "{export_request.reference_number}" '
                "has expired and is no longer available for download."
            ),
            notification_type="WARNING",
            source_object_id=str(export_request.pk),
            source_object_reference=export_request.reference_number,
            priority="normal",
        )


# ---------------------------------------------------------------------------
# Export Analytics Services
# ---------------------------------------------------------------------------


class ExportAnalyticsService(BaseService):
    """Compute and store export analytics snapshots."""

    def _execute(
        self,
        *,
        period: str = "DAILY",
        period_start=None,
        period_end=None,
        source_type: str = "",
        format: str = "",
        requested_by=None,
    ) -> ExportAnalytics:
        from django.db.models import Count, F, Q, Sum

        from .models import ExportAnalytics, ExportRequest, ExportStatus

        if period_start is None:
            period_start = timezone.now().replace(
                hour=0, minute=0, second=0, microsecond=0
            )
        if period_end is None:
            period_end = period_start + timedelta(days=1)

        qs = ExportRequest.objects.filter(
            requested_at__gte=period_start, requested_at__lt=period_end
        )
        if source_type:
            qs = qs.filter(source_type=source_type)
        if format:
            qs = qs.filter(format=format)
        if requested_by:
            qs = qs.filter(requested_by=requested_by)

        stats = qs.aggregate(
            total=Count("id"),
            completed=Count("id", filter=Q(status=ExportStatus.COMPLETED)),
            failed=Count("id", filter=Q(status=ExportStatus.FAILED)),
            cancelled=Count("id", filter=Q(status=ExportStatus.CANCELLED)),
            expired=Count("id", filter=Q(status=ExportStatus.EXPIRED)),
            total_records=Sum("record_count"),
            total_size=Sum("file_size"),
            avg_gen_time=Avg(
                (F("completed_at") - F("started_at")).total_seconds()
                * 1000,
                filter=Q(status=ExportStatus.COMPLETED)
                & Q(completed_at__isnull=False)
                & Q(started_at__isnull=False),
            ),
        )

        # Storage stats
        completed_qs = qs.filter(
            status=ExportStatus.COMPLETED, storage_path__isnull=False
        ).exclude(storage_path="")
        storage_stats = completed_qs.aggregate(
            storage_used=Sum("file_size"),
            storage_expired=Sum(
                "file_size",
                filter=Q(expires_at__isnull=False) & Q(expires_at__lt=timezone.now()),
            ),
        )

        # Distribution stats
        format_dist = dict(
            qs.values("format").annotate(c=Count("id")).values_list("format", "c")
        )
        source_dist = dict(
            qs.values("source_type")
            .annotate(c=Count("id"))
            .values_list("source_type", "c")
        )
        user_dist = dict(
            qs.values("requested_by")
            .annotate(c=Count("id"))
            .values_list("requested_by", "c")
        )

        template_dist = {}
        for req in qs.filter(template__isnull=False).select_related("template"):
            key = req.template.code
            template_dist[key] = template_dist.get(key, 0) + 1

        analytics, _ = ExportAnalytics.objects.update_or_create(
            period=period,
            period_start=period_start,
            period_end=period_end,
            source_type=source_type or "",
            format=format or "",
            requested_by=requested_by,
            defaults={
                "total_exports": stats["total"] or 0,
                "completed_exports": stats["completed"] or 0,
                "failed_exports": stats["failed"] or 0,
                "cancelled_exports": stats["cancelled"] or 0,
                "expired_exports": stats["expired"] or 0,
                "total_records_exported": stats["total_records"] or 0,
                "total_file_size_bytes": stats["total_size"] or 0,
                "avg_generation_time_ms": int(stats["avg_gen_time"] or 0),
                "avg_file_size_bytes": int(
                    (stats["total_size"] or 0) / max(stats["total"] or 1, 1)
                ),
                "storage_used_bytes": storage_stats["storage_used"] or 0,
                "storage_expired_bytes": storage_stats["storage_expired"] or 0,
                "format_distribution": format_dist,
                "source_type_distribution": source_dist,
                "user_activity": user_dist,
                "template_usage": template_dist,
            },
        )
        return analytics

    def compute_all_periods(self, *, days_back: int = 30) -> list:
        """Compute analytics for daily, weekly, monthly periods."""
        results = []
        now = timezone.now()

        # Daily
        for i in range(days_back):
            period_start = (now - timedelta(days=i)).replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            period_end = period_start + timedelta(days=1)
            results.append(
                self.execute(period="DAILY", period_start=period_start, period_end=period_end)
            )

        # Weekly (last 12 weeks)
        for i in range(12):
            period_start = (
                now - timedelta(weeks=i + 1)
            ).replace(hour=0, minute=0, second=0, microsecond=0)
            # Align to Monday
            period_start = period_start - timedelta(days=period_start.weekday())
            period_end = period_start + timedelta(weeks=1)
            results.append(
                self.execute(period="WEEKLY", period_start=period_start, period_end=period_end)
            )

        # Monthly (last 12 months)
        for i in range(12):
            month = (now.month - i - 1) % 12 + 1
            year = now.year - ((now.month - i - 1) // 12)
            period_start = timezone.datetime(year, month, 1, tzinfo=timezone.utc)
            next_month = month % 12 + 1
            next_year = year + (month == 12)
            period_end = timezone.datetime(next_year, next_month, 1, tzinfo=timezone.utc)
            results.append(
                self.execute(period="MONTHLY", period_start=period_start, period_end=period_end)
            )

        return results

    def get_dashboard_data(self, user) -> dict:
        """Get analytics data for the export dashboard."""

        from .models import ExportRequest, ExportStatus

        # Get user's scope
        if user.is_superuser or user_has_permission(user, "exports.manage"):
            qs = ExportRequest.objects.all()
        else:
            qs = ExportRequest.objects.filter(requested_by=user)

        # Recent period stats (last 30 days)
        recent_start = timezone.now() - timedelta(days=30)
        recent_qs = qs.filter(requested_at__gte=recent_start)

        total_recent = recent_qs.count()
        completed_recent = recent_qs.filter(status=ExportStatus.COMPLETED).count()
        failed_recent = recent_qs.filter(status=ExportStatus.FAILED).count()
        total_records = recent_qs.aggregate(Sum("record_count"))["record_count__sum"] or 0
        total_size = recent_qs.aggregate(Sum("file_size"))["file_size__sum"] or 0

        # Format distribution
        format_dist = dict(
            recent_qs.values("format")
            .annotate(c=Count("id"))
            .values_list("format", "c")
        )

        # Source type distribution
        source_dist = dict(
            recent_qs.values("source_type")
            .annotate(c=Count("id"))
            .values_list("source_type", "c")
        )

        # Top users (if manage permission)
        if user.is_superuser or user_has_permission(user, "exports.manage"):
            user_qs = (
                recent_qs.values("requested_by")
                .annotate(c=Count("id"))
                .order_by("-c")[:10]
            )
            top_users = list(user_qs)
        else:
            top_users = []

        # Scheduled exports
        from .models import ScheduledExport

        active_scheduled = ScheduledExport.objects.filter(is_active=True).count()
        due_scheduled = ScheduledExport.objects.filter(
            is_active=True, next_run_at__lte=timezone.now()
        ).count()

        # Queue stats
        from .models import ExportQueue

        queue_pending = ExportQueue.objects.filter(status=ExportQueue.Status.PENDING).count()
        queue_processing = ExportQueue.objects.filter(
            status=ExportQueue.Status.PROCESSING
        ).count()
        queue_failed = ExportQueue.objects.filter(status=ExportQueue.Status.FAILED).count()

        return {
            "total_recent": total_recent,
            "completed_recent": completed_recent,
            "failed_recent": failed_recent,
            "success_rate": (
                (completed_recent / total_recent * 100) if total_recent > 0 else 0
            ),
            "total_records": total_records,
            "total_size_bytes": total_size,
            "format_distribution": format_dist,
            "source_type_distribution": source_dist,
            "top_users": top_users,
            "active_scheduled": active_scheduled,
            "due_scheduled": due_scheduled,
            "queue_pending": queue_pending,
            "queue_processing": queue_processing,
            "queue_failed": queue_failed,
        }


class ExportTemplateAnalyticsService(BaseService):
    """Per-template analytics computation."""

    def compute(
        self,
        *,
        period: str = "DAILY",
        period_start=None,
        period_end=None,
        template=None,
    ) -> list:
        from django.db.models import Count, F, Q, Sum

        from .models import (
            ExportRequest,
            ExportStatus,
            ExportTemplate,
            ExportTemplateAnalytics,
        )

        if period_start is None:
            period_start = timezone.now().replace(
                hour=0, minute=0, second=0, microsecond=0
            )
        if period_end is None:
            period_end = period_start + timedelta(days=1)

        templates = [template] if template else ExportTemplate.objects.filter(is_active=True)
        results = []

        for tmpl in templates:
            qs = ExportRequest.objects.filter(
                template=tmpl,
                requested_at__gte=period_start,
                requested_at__lt=period_end,
            )

            stats = qs.aggregate(
                total=Count("id"),
                completed=Count("id", filter=Q(status=ExportStatus.COMPLETED)),
                failed=Count("id", filter=Q(status=ExportStatus.FAILED)),
                total_records=Sum("record_count"),
                total_size=Sum("file_size"),
                avg_gen_time=Avg(
                    (F("completed_at") - F("started_at")).total_seconds()
                    * 1000,
                    filter=Q(status=ExportStatus.COMPLETED)
                    & Q(completed_at__isnull=False)
                    & Q(started_at__isnull=False),
                ),
            )

            format_dist = dict(
                qs.values("format").annotate(c=Count("id")).values_list("format", "c")
            )

            analytics, _ = ExportTemplateAnalytics.objects.update_or_create(
                template=tmpl,
                period=period,
                period_start=period_start,
                period_end=period_end,
                defaults={
                    "export_count": stats["total"] or 0,
                    "completed_count": stats["completed"] or 0,
                    "failed_count": stats["failed"] or 0,
                    "total_records": stats["total_records"] or 0,
                    "total_size_bytes": stats["total_size"] or 0,
                    "avg_generation_time_ms": int(stats["avg_gen_time"] or 0),
                    "format_breakdown": format_dist,
                },
            )
            results.append(analytics)

        return results


class ExportUserAnalyticsService(BaseService):
    """Per-user analytics computation."""

    def compute(
        self,
        *,
        period: str = "DAILY",
        period_start=None,
        period_end=None,
        user=None,
    ) -> list:
        from django.contrib.auth import get_user_model
        from django.db.models import Count

        from .models import ExportRequest, ExportStatus, ExportUserAnalytics

        User = get_user_model()

        if period_start is None:
            period_start = timezone.now().replace(
                hour=0, minute=0, second=0, microsecond=0
            )
        if period_end is None:
            period_end = period_start + timedelta(days=1)

        users = [user] if user else User.objects.filter(is_active=True)
        results = []

        for u in users:
            qs = ExportRequest.objects.filter(
                requested_by=u,
                requested_at__gte=period_start,
                requested_at__lt=period_end,
            )

            stats = qs.aggregate(
                total=Count("id"),
                completed=Count("id", filter=Q(status=ExportStatus.COMPLETED)),
                failed=Count("id", filter=Q(status=ExportStatus.FAILED)),
                total_records=Sum("record_count"),
                total_size=Sum("file_size"),
            )

            format_dist = dict(
                qs.values("format").annotate(c=Count("id")).values_list("format", "c")
            )
            source_dist = dict(
                qs.values("source_type")
                .annotate(c=Count("id"))
                .values_list("source_type", "c")
            )
            template_dist = dict(
                qs.filter(template__isnull=False)
                .values("template__code")
                .annotate(c=Count("id"))
                .values_list("template__code", "c")
            )

            analytics, _ = ExportUserAnalytics.objects.update_or_create(
                user=u,
                period=period,
                period_start=period_start,
                period_end=period_end,
                defaults={
                    "export_count": stats["total"] or 0,
                    "completed_count": stats["completed"] or 0,
                    "failed_count": stats["failed"] or 0,
                    "total_records": stats["total_records"] or 0,
                    "total_size_bytes": stats["total_size"] or 0,
                    "format_breakdown": format_dist,
                    "source_type_breakdown": source_dist,
                    "template_breakdown": template_dist,
                },
            )
            results.append(analytics)

        return results
