"""Word (DOCX) renderer for the Export Engine.

Built on ``python-docx``.  Produces a branded Word document with a title,
metadata table, narrative sections, a data table and an approval block.
"""

from __future__ import annotations

import io
from typing import Any

from ..constants import ExportFormat
from ..utils import neutralize_spreadsheet_value
from .base import BaseRenderer, ExportDataset, RendererRegistry, RenderResult

_NAVY = "003366"
_LIGHT_GREY = "EEF2F7"


@RendererRegistry.register(ExportFormat.DOCX)
class DOCXRenderer(BaseRenderer):
    """Render an ExportDataset to a Word document."""

    format = ExportFormat.DOCX

    def render(self, dataset: ExportDataset, configuration: Any) -> RenderResult:
        from docx import Document
        from docx.enum.section import WD_ORIENT
        from docx.enum.table import WD_TABLE_ALIGNMENT
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Cm, Pt, RGBColor

        document = Document()

        section = document.sections[0]
        section.page_width = Cm(21.0)
        section.page_height = Cm(29.7)
        if dataset.orientation == "LANDSCAPE":
            section.orientation = WD_ORIENT.LANDSCAPE
            section.page_width, section.page_height = (
                section.page_height,
                section.page_width,
            )

        style = document.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(10)

        # Title + subtitle
        title = document.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = title.add_run(dataset.title)
        run.bold = True
        run.font.size = Pt(16)
        run.font.color.rgb = RGBColor(0x00, 0x33, 0x66)

        if dataset.subtitle:
            sub = document.add_paragraph(dataset.subtitle)
            sub.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            sub.runs[0].font.size = Pt(10)

        # Meta table
        meta_rows = list(dataset.meta_rows)
        if dataset.reference:
            meta_rows.append(("Reference", dataset.reference))
        if dataset.report_period:
            meta_rows.append(("Reporting Period", dataset.report_period))
        if dataset.status:
            meta_rows.append(("Status", dataset.status))
        meta_rows.append(("Generated By", dataset.generated_by))
        meta_rows.append(("Generated At", f"{dataset.generated_at:%Y-%m-%d %H:%M}"))
        meta_rows.append(("Confidentiality", str(dataset.confidentiality)))

        if meta_rows:
            meta_table = document.add_table(rows=0, cols=2)
            meta_table.style = "Table Grid"
            meta_table.alignment = WD_TABLE_ALIGNMENT.LEFT
            for label, value in meta_rows:
                cells = meta_table.add_row().cells
                label_cell = cells[0]
                label_cell.text = label
                for paragraph in label_cell.paragraphs:
                    for r in paragraph.runs:
                        r.bold = True
                        r.font.size = Pt(9)
                self._shade_cell(label_cell, _LIGHT_GREY)
                value_cell = cells[1]
                value_cell.text = str(value)
                for paragraph in value_cell.paragraphs:
                    for r in paragraph.runs:
                        r.font.size = Pt(9)

        # Draft banner
        if dataset.draft:
            draft = document.add_paragraph(
                "DRAFT — UNCONTROLLED COPY, NOT FOR DISTRIBUTION"
            )
            draft.alignment = WD_ALIGN_PARAGRAPH.CENTER
            draft_runs = draft.runs
            for r in draft_runs:
                r.bold = True
                r.font.color.rgb = RGBColor(0xB2, 0x22, 0x22)

        # Narrative sections
        for heading, blocks in dataset.sections:
            h = document.add_heading(level=2)
            h_run = h.add_run(heading)
            h_run.font.color.rgb = RGBColor(0x00, 0x33, 0x66)
            for block in blocks:
                if isinstance(block, list):
                    self._add_table(document, block)
                else:
                    document.add_paragraph(str(block))

        # Data table
        if dataset.columns and dataset.rows:
            document.add_heading("Data", level=2)
            self._add_table(
                document,
                [dataset.column_labels, *dataset.rows],
            )

        if not dataset.columns and not dataset.rows and not dataset.sections:
            document.add_paragraph("No records matched the requested export criteria.")

        # Approval block
        if dataset.approval:
            document.add_heading("Approval and Sign-off", level=2)
            approval_table = document.add_table(rows=0, cols=2)
            approval_table.style = "Table Grid"
            for label in ("Prepared By", "Reviewed By", "Approved By"):
                cells = approval_table.add_row().cells
                label_cell = cells[0]
                label_cell.text = label
                for paragraph in label_cell.paragraphs:
                    for r in paragraph.runs:
                        r.bold = True
                        r.font.size = Pt(9)
                cells[1].text = dataset.approval.get(label, "—")

        buffer = io.BytesIO()
        document.save(buffer)
        buffer.seek(0)
        return RenderResult(
            content=buffer.getvalue(),
            mime_type=self.content_type,
            filename=self.default_extension,
        )

    def _add_table(self, document, rows: list[list]) -> None:
        """Add a data table with a bold header row."""
        from docx.enum.table import WD_TABLE_ALIGNMENT
        from docx.shared import Pt, RGBColor

        if not rows:
            return
        headers, body = rows[0], rows[1:]
        table = document.add_table(rows=1, cols=len(headers))
        table.style = "Table Grid"
        table.alignment = WD_TABLE_ALIGNMENT.LEFT

        for col_index, header in enumerate(headers):
            cell = table.rows[0].cells[col_index]
            cell.text = str(header)
            for paragraph in cell.paragraphs:
                for r in paragraph.runs:
                    r.bold = True
                    r.font.size = Pt(9)
                    r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
            self._shade_cell(cell, _NAVY)

        for row in body:
            cells = table.add_row().cells
            for col_index, value in enumerate(row):
                cells[col_index].text = str(neutralize_spreadsheet_value(value))
                for paragraph in cells[col_index].paragraphs:
                    for r in paragraph.runs:
                        r.font.size = Pt(9)

    @staticmethod
    def _shade_cell(cell, hex_color: str) -> None:
        """Apply a background shading to a table cell."""
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        tc_pr = cell._tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), hex_color)
        tc_pr.append(shd)
