"""Print-ready HTML renderer for the Export Engine.

Produces a self-contained HTML document styled for printing (A4 margins,
branded header/footer, watermark) that the user can open in a browser and
export to PDF via the browser's print dialog.
"""

from __future__ import annotations

from html import escape
from typing import Any

from django.template.loader import render_to_string

from ..constants import ExportFormat
from ..utils import cell_to_text
from .base import BaseRenderer, ExportDataset, RendererRegistry, RenderResult


@RendererRegistry.register(ExportFormat.PRINT_HTML)
class PrintHTMLRenderer(BaseRenderer):
    """Render an ExportDataset to a print-ready HTML document."""

    format = ExportFormat.PRINT_HTML

    def render(self, dataset: ExportDataset, configuration: Any) -> RenderResult:
        context = {
            "dataset": dataset,
            "organization_name": configuration.organization_name,
            "short_name": configuration.short_name,
            "headers": [escape(h) for h in dataset.column_labels],
            "rows": [
                [escape(cell_to_text(value)) for value in row] for row in dataset.rows
            ],
            "meta_rows": self._build_meta(dataset),
            "sections": [
                (
                    escape(heading),
                    [
                        (
                            block
                            if isinstance(block, list)
                            else escape(cell_to_text(block))
                        )
                        for block in blocks
                    ],
                )
                for heading, blocks in dataset.sections
            ],
            "watermark": dataset.watermark_text,
        }
        html = render_to_string("exports/partials/print_export.html", context)
        return RenderResult(
            content=html.encode("utf-8"),
            mime_type=self.content_type,
            filename=self.default_extension,
        )

    def _build_meta(self, dataset: ExportDataset) -> list[tuple[str, str]]:
        meta_rows = list(dataset.meta_rows)
        if dataset.reference:
            meta_rows.append(("Reference", dataset.reference))
        if dataset.report_period:
            meta_rows.append(("Reporting Period", dataset.report_period))
        if dataset.status:
            meta_rows.append(("Status", dataset.status))
        if dataset.version:
            meta_rows.append(("Version", dataset.version))
        meta_rows.append(("Generated By", dataset.generated_by))
        meta_rows.append(("Generated At", f"{dataset.generated_at:%Y-%m-%d %H:%M}"))
        meta_rows.append(("Confidentiality", str(dataset.confidentiality)))
        return [
            (escape(label), escape(cell_to_text(value))) for label, value in meta_rows
        ]
