# Generated by Django 5.1 on 2026-08-07 13:50

import apps.registers.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0002_seed_organizations_permissions"),
        ("programs", "0006_deliverable_submitted_by"),
        ("references", "0009_seed_register_scheme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "number_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix used when generating reference numbers for registers in this category (e.g. MEM for Membership).",
                        max_length=10,
                        verbose_name="Number prefix",
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Default confidentiality",
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed Term"),
                            ("ARCHIVE_AFTER_INACTIVITY", "Archive after Inactivity"),
                            ("LEGAL_HOLD", "Legal Hold"),
                            ("SCHEDULED_DISPOSAL", "Scheduled Disposal"),
                        ],
                        default="PERMANENT",
                        max_length=40,
                        verbose_name="Retention policy",
                    ),
                ),
                (
                    "retention_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Retention years"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Category",
                "verbose_name_plural": "Register Categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Register ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Register name"),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="Register code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "responsible_department",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Responsible department",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Confidentiality",
                    ),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Entries must be approved before they become active.",
                        verbose_name="Approval required",
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("FIXED_TERM", "Fixed Term"),
                            ("ARCHIVE_AFTER_INACTIVITY", "Archive after Inactivity"),
                            ("LEGAL_HOLD", "Legal Hold"),
                            ("SCHEDULED_DISPOSAL", "Scheduled Disposal"),
                        ],
                        default="PERMANENT",
                        max_length=40,
                        verbose_name="Retention policy",
                    ),
                ),
                (
                    "retention_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Retention years"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "numbering_scheme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scheme used to number this register's entries.  Defaults to the category prefix scheme when left empty.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers",
                        to="references.referencenumberscheme",
                        verbose_name="Numbering scheme",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_registers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Register owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="registers.registercategory",
                        verbose_name="Register category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register",
                "verbose_name_plural": "Registers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RegisterEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Reference Number",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Entry title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "reporting_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Reporting period start"
                    ),
                ),
                (
                    "reporting_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Reporting period end"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        db_index=True,
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Confidentiality",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                        verbose_name="Approval status",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "field_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Field data"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Keywords"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted at"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_entries_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_entries",
                        to="organizations.organizationunit",
                        verbose_name="Directorate",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="register_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_entries",
                        to="programs.program",
                        verbose_name="Program",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_entries",
                        to="programs.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="registers.register",
                        verbose_name="Register",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Entry",
                "verbose_name_plural": "Register Entries",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.registers.storage.PrivateRegisterStorage(),
                        upload_to="registers/attachments/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original filename"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Content type"
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Size (bytes)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Attachment",
                "verbose_name_plural": "Register Attachments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("VALIDATED", "Validated"),
                            ("SUBMITTED", "Submitted"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("EXPORTED", "Exported"),
                            ("RELATIONSHIP_ADDED", "Relationship added"),
                            ("RELATIONSHIP_REMOVED", "Relationship removed"),
                            ("ATTACHMENT_ADDED", "Attachment added"),
                            ("ATTACHMENT_REMOVED", "Attachment removed"),
                            ("CONFIDENTIALITY_CHANGED", "Confidentiality changed"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Previous status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="New status"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="registers.register",
                        verbose_name="Register",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Activity",
                "verbose_name_plural": "Register Activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=40,
                        verbose_name="Decision",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "reviewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reviewed at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="register_reviews_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Review",
                "verbose_name_plural": "Register Reviews",
                "ordering": ("-reviewed_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field definitions: key, label, type, required, options.",
                        verbose_name="Fields",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Validation rules"
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Default confidentiality",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default template"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="registers.register",
                        verbose_name="Register",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Template",
                "verbose_name_plural": "Register Templates",
                "ordering": ("register", "name"),
            },
        ),
        migrations.AddField(
            model_name="registerentry",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="registers.registertemplate",
                verbose_name="Template",
            ),
        ),
        migrations.CreateModel(
            name="RegisterValidation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(max_length=80, verbose_name="Rule code"),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Passed")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Checked at"),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_validations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Validation",
                "verbose_name_plural": "Register Validations",
                "ordering": ("-checked_at",),
            },
        ),
        migrations.CreateModel(
            name="RegisterVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Version number"
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(blank=True, verbose_name="Change summary"),
                ),
                (
                    "data_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data snapshot"
                    ),
                ),
                (
                    "is_restored",
                    models.BooleanField(default=False, verbose_name="Restored version"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="register_entry_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Version",
                "verbose_name_plural": "Register Versions",
                "ordering": ("entry", "-version_number"),
            },
        ),
        migrations.CreateModel(
            name="RegisterRelationship",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("REPORT", "Report"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("VOLUNTEER", "Volunteer"),
                            ("MEMBER", "Member"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("STAKEHOLDER", "Stakeholder"),
                            ("EVENT", "Event"),
                            ("RISK", "Risk"),
                            ("ASSET", "Asset"),
                            ("DECISION", "Decision"),
                            ("ENTRY", "Register Entry"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                        verbose_name="Relationship type",
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="Related record ID")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_relationships",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="registers.registerentry",
                        verbose_name="Entry",
                    ),
                ),
                (
                    "related_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="registers.registerentry",
                        verbose_name="Related register entry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Relationship",
                "verbose_name_plural": "Register Relationships",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="registers_r_content_1931db_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="registertemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("register",),
                name="unique_default_template_per_register",
            ),
        ),
        migrations.AddConstraint(
            model_name="registerversion",
            constraint=models.UniqueConstraint(
                fields=("entry", "version_number"), name="unique_version_per_entry"
            ),
        ),
    ]
