# Generated by Django 5.1 on 2026-08-22 03:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Benchmark",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Benchmark Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("DASHBOARD", "Dashboard"),
                            ("REPORTS", "Reports"),
                            ("DOCUMENTS", "Documents"),
                            ("SEARCH", "Search"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("BENEFICIARIES", "Beneficiaries"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                            ("MEAL", "MEAL"),
                            ("FINANCE", "Finance"),
                            ("GOVERNANCE", "Governance"),
                            ("COMMUNICATION", "Communication"),
                            ("PROCUREMENT", "Procurement"),
                            ("INTEGRATIONS", "Integrations"),
                            ("APIS", "APIs"),
                            ("DATABASE", "Database"),
                            ("STORAGE", "Storage"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("CACHING", "Caching"),
                            ("QUEUES", "Background Queues"),
                            ("EXPORTS", "Exports"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Component",
                    ),
                ),
                ("test_scenario", models.TextField(verbose_name="Test Scenario")),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="Configuration"),
                ),
                (
                    "environment",
                    models.CharField(
                        default="staging", max_length=20, verbose_name="Environment"
                    ),
                ),
                (
                    "target_metrics",
                    models.JSONField(default=dict, verbose_name="Target Metrics"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=dict, verbose_name="Results"),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="Passed"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Application Version"
                    ),
                ),
                (
                    "git_commit",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Git Commit"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark",
                "verbose_name_plural": "Benchmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenchmarkRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_number", models.PositiveIntegerField(verbose_name="Run Number")),
                ("started_at", models.DateTimeField(verbose_name="Started At")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("results", models.JSONField(default=dict, verbose_name="Results")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "benchmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="performance.benchmark",
                        verbose_name="Benchmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark Run",
                "verbose_name_plural": "Benchmark Runs",
                "ordering": ["-run_number"],
            },
        ),
        migrations.CreateModel(
            name="CacheConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cache Name"
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("LOCAL_MEMORY", "Local Memory"),
                            ("REDIS", "Redis"),
                            ("DATABASE", "Database"),
                            ("FILESYSTEM", "Filesystem"),
                            ("DUMMY", "Dummy (No Cache)"),
                        ],
                        default="LOCAL_MEMORY",
                        max_length=20,
                        verbose_name="Backend",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Location"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Default Timeout (seconds)"
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        default="sitadc_perf", max_length=100, verbose_name="Key Prefix"
                    ),
                ),
                (
                    "max_entries",
                    models.PositiveIntegerField(
                        default=10000, verbose_name="Max Entries"
                    ),
                ),
                (
                    "options",
                    models.JSONField(default=dict, verbose_name="Backend Options"),
                ),
                (
                    "scope",
                    models.CharField(blank=True, max_length=100, verbose_name="Scope"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "monitor_hit_ratio",
                    models.BooleanField(default=True, verbose_name="Monitor Hit Ratio"),
                ),
                (
                    "alert_threshold_hit_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        max_digits=5,
                        verbose_name="Alert Threshold Hit Ratio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Configuration",
                "verbose_name_plural": "Cache Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CacheMetrics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_requests",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total Requests"
                    ),
                ),
                (
                    "hits",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Cache Hits"
                    ),
                ),
                (
                    "misses",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Cache Misses"
                    ),
                ),
                (
                    "hit_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Hit Ratio (%)",
                    ),
                ),
                (
                    "memory_usage_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Memory Usage (bytes)"
                    ),
                ),
                (
                    "entry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Entry Count"),
                ),
                (
                    "eviction_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Eviction Count"
                    ),
                ),
                (
                    "error_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Error Count"
                    ),
                ),
                (
                    "cache_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="performance.cacheconfiguration",
                        verbose_name="Cache Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Metrics",
                "verbose_name_plural": "Cache Metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseMonitoring",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Database Name"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        default="default", max_length=100, verbose_name="Database Alias"
                    ),
                ),
                (
                    "monitor_query_performance",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Query Performance"
                    ),
                ),
                (
                    "monitor_connections",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Connections"
                    ),
                ),
                (
                    "monitor_table_sizes",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Table Sizes"
                    ),
                ),
                (
                    "monitor_index_usage",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Index Usage"
                    ),
                ),
                (
                    "slow_query_threshold_ms",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Slow Query Threshold (ms)"
                    ),
                ),
                (
                    "max_connections",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Max Connections"
                    ),
                ),
                (
                    "alert_connection_usage_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        max_digits=5,
                        verbose_name="Alert Connection Usage Threshold (%)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Monitoring",
                "verbose_name_plural": "Database Monitorings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseMetrics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active_connections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Active Connections"
                    ),
                ),
                (
                    "idle_connections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Idle Connections"
                    ),
                ),
                (
                    "max_used_connections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Max Used Connections"
                    ),
                ),
                (
                    "total_queries",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total Queries"
                    ),
                ),
                (
                    "slow_queries",
                    models.PositiveIntegerField(default=0, verbose_name="Slow Queries"),
                ),
                (
                    "avg_query_time",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Average Query Time (ms)",
                    ),
                ),
                (
                    "cache_hit_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Cache Hit Ratio (%)",
                    ),
                ),
                (
                    "database_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Database Size (bytes)"
                    ),
                ),
                (
                    "index_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Index Size (bytes)"
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="performance.databasemonitoring",
                        verbose_name="Database",
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Metrics",
                "verbose_name_plural": "Database Metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "optimization_type",
                    models.CharField(
                        choices=[
                            ("FRONTEND", "Frontend Optimization"),
                            ("BACKEND", "Backend Optimization"),
                            ("DATABASE", "Database Optimization"),
                            ("QUERY", "Query Optimization"),
                            ("API", "API Optimization"),
                            ("CACHING", "Caching Optimization"),
                            ("BACKGROUND_JOBS", "Background Job Optimization"),
                            ("STORAGE", "Storage Optimization"),
                            ("REPORT", "Report Optimization"),
                            ("DASHBOARD", "Dashboard Optimization"),
                            ("SEARCH", "Search Optimization"),
                            ("EXPORT", "Export Optimization"),
                            ("NETWORK", "Network Optimization"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Optimization Type",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("DASHBOARD", "Dashboard"),
                            ("REPORTS", "Reports"),
                            ("DOCUMENTS", "Documents"),
                            ("SEARCH", "Search"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("BENEFICIARIES", "Beneficiaries"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                            ("MEAL", "MEAL"),
                            ("FINANCE", "Finance"),
                            ("GOVERNANCE", "Governance"),
                            ("COMMUNICATION", "Communication"),
                            ("PROCUREMENT", "Procurement"),
                            ("INTEGRATIONS", "Integrations"),
                            ("APIS", "APIs"),
                            ("DATABASE", "Database"),
                            ("STORAGE", "Storage"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("CACHING", "Caching"),
                            ("QUEUES", "Background Queues"),
                            ("EXPORTS", "Exports"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Component",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Module"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("rationale", models.TextField(verbose_name="Rationale")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("TESTING", "Testing"),
                            ("DEPLOYED", "Deployed"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="IDENTIFIED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "identified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Identified At"
                    ),
                ),
                (
                    "planned_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planned Start"
                    ),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Start"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "baseline_metrics",
                    models.JSONField(default=dict, verbose_name="Baseline Metrics"),
                ),
                (
                    "target_metrics",
                    models.JSONField(default=dict, verbose_name="Target Metrics"),
                ),
                (
                    "actual_metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Actual Metrics"
                    ),
                ),
                (
                    "improvement_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Improvement Percentage",
                    ),
                ),
                (
                    "estimated_impact",
                    models.TextField(blank=True, verbose_name="Estimated Impact"),
                ),
                (
                    "actual_impact",
                    models.TextField(blank=True, verbose_name="Actual Impact"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "rollback_plan",
                    models.TextField(blank=True, verbose_name="Rollback Plan"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_optimizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "benchmark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimizations",
                        to="performance.benchmark",
                        verbose_name="Benchmark",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimization Record",
                "verbose_name_plural": "Optimization Records",
                "ordering": ["-identified_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceKPI",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="KPI Name"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("DASHBOARD", "Dashboard"),
                            ("REPORTS", "Reports"),
                            ("DOCUMENTS", "Documents"),
                            ("SEARCH", "Search"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("BENEFICIARIES", "Beneficiaries"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                            ("MEAL", "MEAL"),
                            ("FINANCE", "Finance"),
                            ("GOVERNANCE", "Governance"),
                            ("COMMUNICATION", "Communication"),
                            ("PROCUREMENT", "Procurement"),
                            ("INTEGRATIONS", "Integrations"),
                            ("APIS", "APIs"),
                            ("DATABASE", "Database"),
                            ("STORAGE", "Storage"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("CACHING", "Caching"),
                            ("QUEUES", "Background Queues"),
                            ("EXPORTS", "Exports"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Component",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="Metric Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Target Value"
                    ),
                ),
                (
                    "target_unit",
                    models.CharField(
                        choices=[
                            ("MS", "Milliseconds"),
                            ("S", "Seconds"),
                            ("B", "Bytes"),
                            ("KB", "Kilobytes"),
                            ("MB", "Megabytes"),
                            ("PCT", "Percentage"),
                            ("COUNT", "Count"),
                            ("RPS", "Requests per Second"),
                            ("QPS", "Queries per Second"),
                        ],
                        max_length=10,
                        verbose_name="Target Unit",
                    ),
                ),
                (
                    "threshold_warning",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Warning Threshold",
                    ),
                ),
                (
                    "threshold_critical",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Critical Threshold",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("lower_is_better", "Lower is Better"),
                            ("higher_is_better", "Higher is Better"),
                        ],
                        default="lower_is_better",
                        max_length=20,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "aggregation_period",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Aggregation Period",
                    ),
                ),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[
                            ("avg", "Average"),
                            ("median", "Median"),
                            ("p95", "95th Percentile"),
                            ("p99", "99th Percentile"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="avg",
                        max_length=20,
                        verbose_name="Aggregation Method",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance KPI",
                "verbose_name_plural": "Performance KPIs",
                "ordering": ["component", "name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("DASHBOARD", "Dashboard"),
                            ("REPORTS", "Reports"),
                            ("DOCUMENTS", "Documents"),
                            ("SEARCH", "Search"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("BENEFICIARIES", "Beneficiaries"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                            ("MEAL", "MEAL"),
                            ("FINANCE", "Finance"),
                            ("GOVERNANCE", "Governance"),
                            ("COMMUNICATION", "Communication"),
                            ("PROCUREMENT", "Procurement"),
                            ("INTEGRATIONS", "Integrations"),
                            ("APIS", "APIs"),
                            ("DATABASE", "Database"),
                            ("STORAGE", "Storage"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("CACHING", "Caching"),
                            ("QUEUES", "Background Queues"),
                            ("EXPORTS", "Exports"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Component",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Module"
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Metric Name"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=4,
                        max_digits=20,
                        verbose_name="Value",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("MS", "Milliseconds"),
                            ("S", "Seconds"),
                            ("B", "Bytes"),
                            ("KB", "Kilobytes"),
                            ("MB", "Megabytes"),
                            ("PCT", "Percentage"),
                            ("COUNT", "Count"),
                            ("RPS", "Requests per Second"),
                            ("QPS", "Queries per Second"),
                        ],
                        default="MS",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        db_index=True,
                        default="production",
                        max_length=20,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Request Path"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Query Parameters"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=dict, verbose_name="Tags"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Metric",
                "verbose_name_plural": "Performance Metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Report Title"),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period Start")),
                ("period_end", models.DateTimeField(verbose_name="Period End")),
                ("summary", models.JSONField(default=dict, verbose_name="Summary")),
                ("metrics", models.JSONField(default=dict, verbose_name="Metrics")),
                (
                    "kpi_evaluations",
                    models.JSONField(default=dict, verbose_name="KPI Evaluations"),
                ),
                ("alerts", models.JSONField(default=list, verbose_name="Alerts")),
                (
                    "optimizations",
                    models.JSONField(default=list, verbose_name="Optimizations"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("PDF", "PDF"),
                            ("XLSX", "XLSX"),
                            ("CSV", "CSV"),
                        ],
                        default="HTML",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="performance_reports/",
                        verbose_name="Report File",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Report",
                "verbose_name_plural": "Performance Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueMonitoring",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Queue Name"
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("REDIS", "Redis"),
                            ("RABBITMQ", "RabbitMQ"),
                            ("AMAZON_SQS", "Amazon SQS"),
                        ],
                        default="DATABASE",
                        max_length=20,
                        verbose_name="Backend",
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(
                        max_length=200, verbose_name="Queue Name (backend)"
                    ),
                ),
                (
                    "connection_config",
                    models.JSONField(
                        default=dict, verbose_name="Connection Configuration"
                    ),
                ),
                (
                    "monitor_depth",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Queue Depth"
                    ),
                ),
                (
                    "monitor_processing_time",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Processing Time"
                    ),
                ),
                (
                    "monitor_failure_rate",
                    models.BooleanField(
                        default=True, verbose_name="Monitor Failure Rate"
                    ),
                ),
                (
                    "alert_depth_threshold",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Alert Depth Threshold"
                    ),
                ),
                (
                    "alert_processing_time_threshold",
                    models.PositiveIntegerField(
                        default=60,
                        verbose_name="Alert Processing Time Threshold (seconds)",
                    ),
                ),
                (
                    "alert_failure_rate_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="Alert Failure Rate Threshold (%)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Monitoring",
                "verbose_name_plural": "Queue Monitorings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QueueMetrics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(default=0, verbose_name="Queue Depth"),
                ),
                (
                    "pending",
                    models.PositiveIntegerField(default=0, verbose_name="Pending Jobs"),
                ),
                (
                    "processing",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Processing Jobs"
                    ),
                ),
                (
                    "completed",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Completed Jobs"
                    ),
                ),
                (
                    "failed",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Failed Jobs"
                    ),
                ),
                (
                    "avg_processing_time",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Average Processing Time (seconds)",
                    ),
                ),
                (
                    "max_processing_time",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Max Processing Time (seconds)",
                    ),
                ),
                (
                    "throughput_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Throughput (jobs/minute)",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="performance.queuemonitoring",
                        verbose_name="Queue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Metrics",
                "verbose_name_plural": "Queue Metrics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceAlert",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Alert Title")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="WARNING",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("DASHBOARD", "Dashboard"),
                            ("REPORTS", "Reports"),
                            ("DOCUMENTS", "Documents"),
                            ("SEARCH", "Search"),
                            ("NOTIFICATIONS", "Notifications"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("BENEFICIARIES", "Beneficiaries"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                            ("MEAL", "MEAL"),
                            ("FINANCE", "Finance"),
                            ("GOVERNANCE", "Governance"),
                            ("COMMUNICATION", "Communication"),
                            ("PROCUREMENT", "Procurement"),
                            ("INTEGRATIONS", "Integrations"),
                            ("APIS", "APIs"),
                            ("DATABASE", "Database"),
                            ("STORAGE", "Storage"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("CACHING", "Caching"),
                            ("QUEUES", "Background Queues"),
                            ("EXPORTS", "Exports"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Component",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Metric Name"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Current Value",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Threshold Value",
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="Acknowledged"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acknowledged By",
                    ),
                ),
                (
                    "cache_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="performance.cacheconfiguration",
                        verbose_name="Related Cache",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="performance.databasemonitoring",
                        verbose_name="Related Database",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="performance.performancekpi",
                        verbose_name="Related KPI",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="performance.queuemonitoring",
                        verbose_name="Related Queue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Alert",
                "verbose_name_plural": "Performance Alerts",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="benchmark",
            index=models.Index(
                fields=["component", "status"], name="performance_compone_9d4e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benchmark",
            index=models.Index(
                fields=["status", "created_at"], name="performance_status_f37177_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="benchmarkrun",
            unique_together={("benchmark", "run_number")},
        ),
        migrations.AddIndex(
            model_name="cachemetrics",
            index=models.Index(
                fields=["cache_config", "created_at"],
                name="performance_cache_c_098ad8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="databasemetrics",
            index=models.Index(
                fields=["database", "created_at"], name="performance_databas_9f34b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrecord",
            index=models.Index(
                fields=["optimization_type", "status"],
                name="performance_optimiz_f1dd34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrecord",
            index=models.Index(
                fields=["component", "status"], name="performance_compone_1f83d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrecord",
            index=models.Index(
                fields=["status", "identified_at"], name="performance_status_31cd55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["component", "metric_name", "created_at"],
                name="performance_compone_71c074_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["module", "created_at"], name="performance_module_8aea0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["environment", "created_at"],
                name="performance_environ_e42b6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queuemetrics",
            index=models.Index(
                fields=["queue", "created_at"], name="performance_queue_i_0a6f52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["severity", "is_acknowledged"],
                name="performance_severit_87b5cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["component", "created_at"],
                name="performance_compone_7ffde2_idx",
            ),
        ),
    ]
