# Generated by Django 5.0.7 on 2026-08-06 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0006_deliverable_submitted_by"),
        ("reports", "0003_reportconfiguration_reportingperiod"),
        ("stakeholders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="default",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "max_upload_size",
                    models.PositiveBigIntegerField(
                        default=20971520, verbose_name="Max upload size (bytes)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed extensions"
                    ),
                ),
                (
                    "enable_checkout",
                    models.BooleanField(default=True, verbose_name="Enable checkout"),
                ),
                (
                    "enable_versioning",
                    models.BooleanField(default=True, verbose_name="Enable versioning"),
                ),
                (
                    "auto_increment_version",
                    models.BooleanField(
                        default=True, verbose_name="Auto-increment version"
                    ),
                ),
                (
                    "require_change_summary",
                    models.BooleanField(
                        default=False, verbose_name="Require change summary"
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                            ("SAFEGUARDING", "Safeguarding Restricted"),
                            ("FINANCIAL", "Financial Restricted"),
                            ("EXECUTIVE", "Executive Restricted"),
                            ("BOARD", "Board Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Default confidentiality",
                    ),
                ),
                (
                    "enable_external_sharing",
                    models.BooleanField(
                        default=False, verbose_name="Enable external sharing"
                    ),
                ),
                (
                    "enable_qr_codes",
                    models.BooleanField(default=False, verbose_name="Enable QR codes"),
                ),
                (
                    "enable_barcodes",
                    models.BooleanField(default=False, verbose_name="Enable barcodes"),
                ),
                (
                    "storage_path_prefix",
                    models.CharField(
                        default="documents",
                        max_length=200,
                        verbose_name="Storage path prefix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Settings",
                "verbose_name_plural": "Document Settings",
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                            ("SAFEGUARDING", "Safeguarding Restricted"),
                            ("FINANCIAL", "Financial Restricted"),
                            ("EXECUTIVE", "Executive Restricted"),
                            ("BOARD", "Board Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Default confidentiality",
                    ),
                ),
                (
                    "default_retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Retention period in days. Null means no default.",
                        null=True,
                        verbose_name="Default retention period (days)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=60, verbose_name="Icon"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="documents.documentcategory",
                        verbose_name="Parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(max_length=200, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                            ("SAFEGUARDING", "Safeguarding Restricted"),
                            ("FINANCIAL", "Financial Restricted"),
                            ("EXECUTIVE", "Executive Restricted"),
                            ("BOARD", "Board Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Confidentiality level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="documents.documentfolder",
                        verbose_name="Parent folder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Folder",
                "verbose_name_plural": "Document Folders",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Reference number",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "short_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Short title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/files/", verbose_name="File"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original filename"),
                ),
                (
                    "stored_filename",
                    models.CharField(max_length=255, verbose_name="Stored filename"),
                ),
                (
                    "file_extension",
                    models.CharField(max_length=10, verbose_name="File extension"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=255, verbose_name="MIME type"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="File size (bytes)"),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 hex digest",
                        max_length=64,
                        verbose_name="Checksum",
                    ),
                ),
                (
                    "current_version_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Current version number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UPLOADED", "Uploaded"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RETURNED_FOR_CORRECTION", "Returned for Correction"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("ARCHIVED", "Archived"),
                            ("DISPOSAL_PENDING", "Disposal Pending"),
                            ("DISPOSED", "Disposed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RETURNED", "Returned"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NOT_SUBMITTED",
                        max_length=30,
                        verbose_name="Approval status",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("NOT_PUBLISHED", "Not Published"),
                            ("PUBLISHED", "Published"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="NOT_PUBLISHED",
                        max_length=30,
                        verbose_name="Publication status",
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                            ("SAFEGUARDING", "Safeguarding Restricted"),
                            ("FINANCIAL", "Financial Restricted"),
                            ("EXECUTIVE", "Executive Restricted"),
                            ("BOARD", "Board Restricted"),
                        ],
                        db_index=True,
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Confidentiality level",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="Is sensitive"),
                ),
                (
                    "responsible_unit",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsible unit"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry date"),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, null=True, verbose_name="Review date"),
                ),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Renewal date"
                    ),
                ),
                (
                    "retention_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Retention end date"
                    ),
                ),
                (
                    "legal_hold",
                    models.BooleanField(default=False, verbose_name="Legal hold"),
                ),
                (
                    "safeguarding_hold",
                    models.BooleanField(
                        default=False, verbose_name="Safeguarding hold"
                    ),
                ),
                (
                    "download_restricted",
                    models.BooleanField(
                        default=False, verbose_name="Download restricted"
                    ),
                ),
                (
                    "print_restricted",
                    models.BooleanField(default=False, verbose_name="Print restricted"),
                ),
                (
                    "external_sharing_restricted",
                    models.BooleanField(
                        default=True, verbose_name="External sharing restricted"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published at"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, default=list, verbose_name="Keywords"),
                ),
                (
                    "metadata_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata snapshot"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_documents",
                        to="programs.program",
                        verbose_name="Program",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published by",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="reports.reporttemplate",
                        verbose_name="Report",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_documents",
                        to="stakeholders.stakeholder",
                        verbose_name="Stakeholder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentfolder",
                        verbose_name="Folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentHold",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hold_type",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Legal Hold"),
                            ("SAFEGUARDING", "Safeguarding Hold"),
                            ("REGULATORY", "Regulatory Hold"),
                            ("INVESTIGATION", "Investigation Hold"),
                            ("OTHER", "Other Hold"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Hold type",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Applied at"),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, null=True, verbose_name="Review date"),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Released at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RELEASED", "Released")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "restricted_notes",
                    models.TextField(blank=True, verbose_name="Restricted notes"),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_holds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applied by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_holds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Released by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Hold",
                "verbose_name_plural": "Document Holds",
                "ordering": ("-applied_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentRelationship",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("REPLACES", "Replaces"),
                            ("SUPERSEDES", "Supersedes"),
                            ("AMENDS", "Amends"),
                            ("SUPPORTS", "Supports"),
                            ("REFERENCES", "References"),
                            ("ATTACHED_TO", "Attached to"),
                            ("EVIDENCE_FOR", "Evidence for"),
                            ("DERIVED_FROM", "Derived from"),
                            ("RELATED_TO", "Related to"),
                            ("SIGNED_VERSION", "Signed version of"),
                            ("TRANSLATION_OF", "Translation of"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Relationship type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="documents.document",
                        verbose_name="Source document",
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="documents.document",
                        verbose_name="Target document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Relationship",
                "verbose_name_plural": "Document Relationships",
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="documents.documentcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                to="documents.documenttag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="DocumentTimelineEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("METADATA_UPDATED", "Metadata Updated"),
                            ("CHECKED_OUT", "Checked Out"),
                            ("CHECKED_IN", "Checked In"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("DOWNLOADED", "Downloaded"),
                            ("SHARED", "Shared"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("EXPIRED", "Expired"),
                            ("DISPOSED", "Disposed"),
                            ("VERSION_UPLOADED", "Version Uploaded"),
                            ("RETURNED", "Returned for Correction"),
                            ("HOLD_APPLIED", "Hold Applied"),
                            ("HOLD_RELEASED", "Hold Released"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Previous status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="New status"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Timeline Event",
                "verbose_name_plural": "Document Timeline Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed extensions"
                    ),
                ),
                (
                    "max_file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max file size (bytes)"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires approval"
                    ),
                ),
                (
                    "requires_versioning",
                    models.BooleanField(
                        default=True, verbose_name="Requires versioning"
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                            ("SAFEGUARDING", "Safeguarding Restricted"),
                            ("FINANCIAL", "Financial Restricted"),
                            ("EXECUTIVE", "Executive Restricted"),
                            ("BOARD", "Board Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Default confidentiality",
                    ),
                ),
                (
                    "default_retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Default retention period (days)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_types",
                        to="documents.documentcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documenttype",
                verbose_name="Document type",
            ),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Version number"),
                ),
                (
                    "version_label",
                    models.CharField(max_length=50, verbose_name="Version label"),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[("MAJOR", "Major"), ("MINOR", "Minor")],
                        default="MAJOR",
                        max_length=10,
                        verbose_name="Version type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/versions/", verbose_name="File"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original filename"),
                ),
                (
                    "stored_filename",
                    models.CharField(max_length=255, verbose_name="Stored filename"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=255, verbose_name="MIME type"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="File size (bytes)"),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 hex digest",
                        max_length=64,
                        verbose_name="Checksum",
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(blank=True, verbose_name="Change summary"),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="Change reason"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is current"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RETURNED", "Returned"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        max_length=30,
                        verbose_name="Approval status",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("NOT_PUBLISHED", "Not Published"),
                            ("PUBLISHED", "Published"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="NOT_PUBLISHED",
                        max_length=30,
                        verbose_name="Publication status",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective date"
                    ),
                ),
                (
                    "superseded_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Superseded date"
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Scan"),
                            ("CLEAN", "Clean"),
                            ("SUSPICIOUS", "Suspicious"),
                            ("INFECTED", "Infected"),
                            ("SCAN_FAILED", "Scan Failed"),
                            ("QUARANTINED", "Quarantined"),
                            ("RELEASED", "Released"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Scan status",
                    ),
                ),
                (
                    "metadata_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata snapshot"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "ordering": ("-version_number",),
            },
        ),
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shared_with_role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shared with role"
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Shared at"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry date"),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("COMMENT", "Comment"),
                            ("DOWNLOAD", "Download"),
                            ("EDIT_METADATA", "Edit Metadata"),
                            ("UPLOAD_VERSION", "Upload Version"),
                        ],
                        default="VIEW",
                        max_length=20,
                        verbose_name="Permission level",
                    ),
                ),
                (
                    "download_allowed",
                    models.BooleanField(default=False, verbose_name="Download allowed"),
                ),
                (
                    "print_allowed",
                    models.BooleanField(default=False, verbose_name="Print allowed"),
                ),
                (
                    "reshare_allowed",
                    models.BooleanField(default=False, verbose_name="Reshare allowed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revoked at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_shares_revoked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revoked by",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_shares_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shared by",
                    ),
                ),
                (
                    "shared_with_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_shares_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shared with user",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="documents.documentversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Share",
                "verbose_name_plural": "Document Shares",
                "ordering": ("-shared_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentCheckout",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Checked out at"
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected return date"
                    ),
                ),
                (
                    "checkout_reason",
                    models.TextField(blank=True, verbose_name="Checkout reason"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("FORCE_RELEASED", "Force Released"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Checked in at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled at"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_checkouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled by",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_checkouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked out by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkouts",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "new_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_new_version",
                        to="documents.documentversion",
                        verbose_name="New version",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkouts",
                        to="documents.documentversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Checkout",
                "verbose_name_plural": "Document Checkouts",
            },
        ),
        migrations.CreateModel(
            name="RetentionCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Retention period in days. Null means permanent.",
                        null=True,
                        verbose_name="Retention period (days)",
                    ),
                ),
                (
                    "retention_trigger",
                    models.CharField(
                        choices=[
                            ("CREATION", "Creation Date"),
                            ("APPROVAL", "Approval Date"),
                            ("PUBLICATION", "Publication Date"),
                            ("EXPIRY", "Expiry Date"),
                            ("PROJECT_CLOSURE", "Project Closure"),
                            ("AGREEMENT_TERMINATION", "Agreement Termination"),
                            ("MEMBERSHIP_EXIT", "Membership Exit"),
                            ("BENEFICIARY_EXIT", "Beneficiary Exit"),
                            ("LAST_ACTIVITY", "Last Activity Date"),
                        ],
                        default="CREATION",
                        max_length=30,
                        verbose_name="Retention trigger",
                    ),
                ),
                (
                    "disposal_action",
                    models.CharField(
                        choices=[
                            ("DELETE", "Permanent Delete"),
                            ("ARCHIVE", "Move to Archive"),
                            ("ANONYMIZE", "Anonymize"),
                            ("NONE", "No Action Required"),
                        ],
                        default="NONE",
                        max_length=20,
                        verbose_name="Disposal action",
                    ),
                ),
                (
                    "supports_legal_hold",
                    models.BooleanField(
                        default=True, verbose_name="Supports legal hold"
                    ),
                ),
                (
                    "requires_review",
                    models.BooleanField(default=False, verbose_name="Requires review"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires approval"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Category",
                "verbose_name_plural": "Retention Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DocumentDisposalRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "retention_end_date",
                    models.DateField(verbose_name="Retention end date"),
                ),
                ("disposal_reason", models.TextField(verbose_name="Disposal reason")),
                (
                    "has_legal_hold",
                    models.BooleanField(default=False, verbose_name="Has legal hold"),
                ),
                (
                    "has_safeguarding_hold",
                    models.BooleanField(
                        default=False, verbose_name="Has safeguarding hold"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "disposal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disposal date"
                    ),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SECURE_DELETE", "Secure Digital Deletion"),
                            ("PHYSICAL_DESTRUCTION", "Physical Destruction"),
                            ("TRANSFER", "Transfer to Archive"),
                            ("DONATION", "Donation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Disposal method",
                    ),
                ),
                (
                    "disposal_certificate_reference",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Disposal certificate reference",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_disposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal_requests",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_disposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_disposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed by",
                    ),
                ),
                (
                    "retention_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal_requests",
                        to="documents.retentioncategory",
                        verbose_name="Retention category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Disposal Request",
                "verbose_name_plural": "Document Disposal Requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="retention_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.retentioncategory",
                verbose_name="Retention category",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("FILE_UPLOADED", "File Uploaded"),
                            ("UPLOAD_REJECTED", "Upload Rejected"),
                            ("VIEWED", "Viewed"),
                            ("PREVIEWED", "Previewed"),
                            ("DOWNLOADED", "Downloaded"),
                            ("PRINTED", "Printed"),
                            ("METADATA_CHANGED", "Metadata Changed"),
                            ("NEW_VERSION", "New Version Uploaded"),
                            ("CHECKED_OUT", "Checked Out"),
                            ("CHECKED_IN", "Checked In"),
                            ("CHECKOUT_CANCELLED", "Checkout Cancelled"),
                            ("SUBMITTED_FOR_REVIEW", "Submitted for Review"),
                            ("RETURNED", "Returned for Correction"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("UNPUBLISHED", "Unpublished"),
                            ("SHARED", "Shared"),
                            ("SHARE_REVOKED", "Share Revoked"),
                            ("CONFIDENTIALITY_CHANGED", "Confidentiality Changed"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("RETENTION_CHANGED", "Retention Changed"),
                            ("HOLD_APPLIED", "Hold Applied"),
                            ("HOLD_RELEASED", "Hold Released"),
                            ("DISPOSAL_REQUESTED", "Disposal Requested"),
                            ("DISPOSAL_APPROVED", "Disposal Approved"),
                            ("DISPOSED", "Disposed"),
                            ("ACCESS_DENIED", "Access Denied"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Audit Record",
                "verbose_name_plural": "Document Audit Records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type"], name="docaudit_entity_type_idx"
                    ),
                    models.Index(fields=["entity_id"], name="docaudit_entity_id_idx"),
                    models.Index(fields=["action"], name="docaudit_action_idx"),
                    models.Index(fields=["changed_by"], name="docaudit_changed_by_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="documents_d_is_acti_3e97db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="documents_d_is_acti_6b5d76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documenthold",
            index=models.Index(fields=["document"], name="dochold_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documenthold",
            index=models.Index(fields=["status"], name="dochold_status_idx"),
        ),
        migrations.AddIndex(
            model_name="documenthold",
            index=models.Index(fields=["hold_type"], name="dochold_type_idx"),
        ),
        migrations.AddIndex(
            model_name="documentrelationship",
            index=models.Index(fields=["source_document"], name="docrel_source_idx"),
        ),
        migrations.AddIndex(
            model_name="documentrelationship",
            index=models.Index(fields=["target_document"], name="docrel_target_idx"),
        ),
        migrations.AddIndex(
            model_name="documentrelationship",
            index=models.Index(fields=["relationship_type"], name="docrel_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentrelationship",
            constraint=models.UniqueConstraint(
                fields=("source_document", "target_document", "relationship_type"),
                name="document_relationship_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttimelineevent",
            index=models.Index(fields=["document"], name="doctimeline_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttimelineevent",
            index=models.Index(
                fields=["event_type"], name="doctimeline_event_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttimelineevent",
            index=models.Index(
                fields=["created_at"], name="doctimeline_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttype",
            index=models.Index(
                fields=["is_active", "name"], name="documents_d_is_acti_e038a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["document"], name="docver_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["is_current"], name="docver_is_current_idx"),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["version_number"], name="docver_version_num_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_number"),
                name="document_version_number_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("document", "is_current"),
                name="document_single_current_version",
            ),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(fields=["document"], name="docshare_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(fields=["shared_with_user"], name="docshare_user_idx"),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(fields=["shared_by"], name="docshare_shared_by_idx"),
        ),
        migrations.AddIndex(
            model_name="documentshare",
            index=models.Index(fields=["is_active"], name="docshare_active_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcheckout",
            index=models.Index(fields=["document"], name="docck_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcheckout",
            index=models.Index(fields=["status"], name="docck_status_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcheckout",
            index=models.Index(
                fields=["checked_out_by"], name="docck_checked_out_by_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcheckout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("document", "status"),
                name="document_single_active_checkout",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdisposalrequest",
            index=models.Index(fields=["document"], name="docdisp_document_idx"),
        ),
        migrations.AddIndex(
            model_name="documentdisposalrequest",
            index=models.Index(fields=["status"], name="docdisp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="documentdisposalrequest",
            index=models.Index(
                fields=["retention_category"], name="docdisp_retcat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["reference_number"], name="doc_ref_number_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="doc_title_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["category"], name="doc_category_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_type"], name="doc_type_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["folder"], name="doc_folder_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="doc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["approval_status"], name="doc_approval_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["publication_status"], name="doc_pub_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["confidentiality_level"], name="doc_conf_level_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner"], name="doc_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["effective_date"], name="doc_eff_date_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["expiry_date"], name="doc_exp_date_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["checksum"], name="doc_checksum_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["created_at"], name="doc_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["updated_at"], name="doc_updated_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("reference_number",), name="document_reference_number_uniq"
            ),
        ),
    ]
