# Generated by Django 6.0.8 on 2026-08-12 07:25

from django.db import migrations, models


def backfill_null_disposal_methods(apps, schema_editor):
    DocumentDisposalRequest = apps.get_model(
        "documents", "DocumentDisposalRequest"
    )
    DocumentDisposalRequest.objects.filter(
        disposal_method__isnull=True
    ).update(disposal_method="")


def reverse_backfill(apps, schema_editor):
    DocumentDisposalRequest = apps.get_model(
        "documents", "DocumentDisposalRequest"
    )
    DocumentDisposalRequest.objects.filter(
        disposal_method=""
    ).update(disposal_method=None)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_null_disposal_methods, reverse_backfill),
        migrations.AlterField(
            model_name="documentdisposalrequest",
            name="disposal_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SECURE_DELETE", "Secure Digital Deletion"),
                    ("PHYSICAL_DESTRUCTION", "Physical Destruction"),
                    ("TRANSFER", "Transfer to Archive"),
                    ("DONATION", "Donation"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                verbose_name="Disposal method",
            ),
        ),
    ]