# Generated by Django 5.1 on 2026-08-11 09:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Export reference",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Report"),
                            ("REGISTER", "Organizational Register"),
                            ("DIRECTORY", "People Directory"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("MEETING", "Meeting"),
                            ("DOCUMENT", "Document Metadata"),
                            ("SEARCH", "Search Results"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "source_object_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source object ID"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "Word (DOCX)"),
                            ("XLSX", "Excel (XLSX)"),
                            ("CSV", "CSV"),
                            ("PRINT_HTML", "Print-ready HTML"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filters"),
                ),
                (
                    "selected_columns",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Selected columns"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, verbose_name="Record count"),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Filename"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Storage path"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="MIME type"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="File size (bytes)"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        db_index=True,
                        default="INTERNAL",
                        max_length=30,
                        verbose_name="Confidentiality",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="Sensitive export"),
                ),
                (
                    "is_bulk",
                    models.BooleanField(default=False, verbose_name="Bulk export"),
                ),
                (
                    "confirmed_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="Sensitive export confirmed"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Requested at"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Failed at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "failure_summary",
                    models.TextField(blank=True, verbose_name="Failure summary"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Error code"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Source content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Request",
                "verbose_name_plural": "Export Requests",
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="ExportActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Export requested"),
                            ("GENERATED", "Export generated"),
                            ("SENSITIVE_GENERATED", "Sensitive export generated"),
                            ("BULK_GENERATED", "Bulk export generated"),
                            ("DOWNLOADED", "Export downloaded"),
                            ("SENSITIVE_DOWNLOADED", "Sensitive export downloaded"),
                            ("CANCELLED", "Export cancelled"),
                            ("EXPIRED", "Export expired"),
                            ("FAILED", "Export failed"),
                            ("REGENERATED", "Export regenerated"),
                            ("PREVIEWED", "Export previewed"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User agent"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "export_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="exports.exportrequest",
                        verbose_name="Export request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Activity",
                "verbose_name_plural": "Export Activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Report"),
                            ("REGISTER", "Organizational Register"),
                            ("DIRECTORY", "People Directory"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("MEETING", "Meeting"),
                            ("DOCUMENT", "Document Metadata"),
                            ("SEARCH", "Search Results"),
                        ],
                        db_index=True,
                        default="REPORT",
                        max_length=20,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "formats",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Supported formats"
                    ),
                ),
                (
                    "page_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("LETTER", "Letter")],
                        default="A4",
                        max_length=10,
                        verbose_name="Page size",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("PORTRAIT", "Portrait"), ("LANDSCAPE", "Landscape")],
                        default="PORTRAIT",
                        max_length=10,
                        verbose_name="Orientation",
                    ),
                ),
                (
                    "logo_enabled",
                    models.BooleanField(default=True, verbose_name="Logo enabled"),
                ),
                (
                    "header_enabled",
                    models.BooleanField(default=True, verbose_name="Header enabled"),
                ),
                (
                    "footer_enabled",
                    models.BooleanField(default=True, verbose_name="Footer enabled"),
                ),
                (
                    "show_page_numbers",
                    models.BooleanField(default=True, verbose_name="Show page numbers"),
                ),
                (
                    "confidentiality_marking",
                    models.BooleanField(
                        default=True, verbose_name="Confidentiality marking"
                    ),
                ),
                (
                    "watermark_text",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Watermark text"
                    ),
                ),
                (
                    "default_columns",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Default columns"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Template",
                "verbose_name_plural": "Export Templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ExportConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(
                        default="default",
                        max_length=20,
                        unique=True,
                        verbose_name="Singleton key",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Sustainable Initiatives Through Transformative Actions for Development in Communities — SITADC Youth Organization",
                        max_length=300,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="SITADC Youth Organization",
                        max_length=120,
                        verbose_name="Short name",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@sitadc.org",
                        max_length=254,
                        verbose_name="Contact email",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "default_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "Word (DOCX)"),
                            ("XLSX", "Excel (XLSX)"),
                            ("CSV", "CSV"),
                            ("PRINT_HTML", "Print-ready HTML"),
                        ],
                        default="PDF",
                        max_length=20,
                        verbose_name="Default format",
                    ),
                ),
                (
                    "default_page_size",
                    models.CharField(
                        choices=[("A4", "A4"), ("LETTER", "Letter")],
                        default="A4",
                        max_length=10,
                        verbose_name="Default page size",
                    ),
                ),
                (
                    "default_orientation",
                    models.CharField(
                        choices=[("PORTRAIT", "Portrait"), ("LANDSCAPE", "Landscape")],
                        default="PORTRAIT",
                        max_length=10,
                        verbose_name="Default orientation",
                    ),
                ),
                (
                    "logo_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Branding logo enabled"
                    ),
                ),
                (
                    "enabled_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Formats the engine may produce.",
                        verbose_name="Enabled formats",
                    ),
                ),
                (
                    "max_sync_rows",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Maximum synchronous rows"
                    ),
                ),
                (
                    "max_bulk_rows",
                    models.PositiveIntegerField(
                        default=25000, verbose_name="Maximum bulk export rows"
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Maximum file size (MB)"
                    ),
                ),
                (
                    "max_columns",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Maximum columns"
                    ),
                ),
                (
                    "standard_retention_hours",
                    models.PositiveIntegerField(
                        default=168, verbose_name="Standard retention (hours)"
                    ),
                ),
                (
                    "sensitive_retention_hours",
                    models.PositiveIntegerField(
                        default=48, verbose_name="Sensitive retention (hours)"
                    ),
                ),
                (
                    "download_expiry_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Download expiry (hours)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Configuration",
                "verbose_name_plural": "Export Configuration",
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(("singleton_key", "default")),
                        name="export_configuration_singleton",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="exportrequest",
            index=models.Index(
                fields=["requested_by", "status"], name="exports_exp_request_351fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrequest",
            index=models.Index(
                fields=["source_type", "status"], name="exports_exp_source__084d9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrequest",
            index=models.Index(
                fields=["format", "status"], name="exports_exp_format_90e357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrequest",
            index=models.Index(
                fields=["expires_at"], name="exports_exp_expires_af429d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrequest",
            index=models.Index(
                fields=["confidentiality"], name="exports_exp_confide_046283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportactivity",
            index=models.Index(
                fields=["export_request", "action"],
                name="exports_exp_export__7eefb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportactivity",
            index=models.Index(
                fields=["actor", "action"], name="exports_exp_actor_i_c0aa79_idx"
            ),
        ),
    ]
