# Generated by Django 5.1 on 2026-08-16 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportactivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Export requested"),
                    ("GENERATED", "Export generated"),
                    ("SENSITIVE_GENERATED", "Sensitive export generated"),
                    ("BULK_GENERATED", "Bulk export generated"),
                    ("DOWNLOADED", "Export downloaded"),
                    ("SENSITIVE_DOWNLOADED", "Sensitive export downloaded"),
                    ("CANCELLED", "Export cancelled"),
                    ("EXPIRED", "Export expired"),
                    ("FAILED", "Export failed"),
                    ("REGENERATED", "Export regenerated"),
                    ("PREVIEWED", "Export previewed"),
                    ("QUEUED", "Export queued"),
                    ("BATCH_STARTED", "Batch export started"),
                    ("BATCH_COMPLETED", "Batch export completed"),
                    ("SCHEDULED_RUN", "Scheduled export run"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="exportconfiguration",
            name="default_format",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("DOCX", "Word (DOCX)"),
                    ("XLSX", "Excel (XLSX)"),
                    ("CSV", "CSV"),
                    ("PRINT_HTML", "Print-ready HTML"),
                    ("PNG", "PNG Image"),
                    ("JPEG", "JPEG Image"),
                ],
                default="PDF",
                max_length=20,
                verbose_name="Default format",
            ),
        ),
        migrations.AlterField(
            model_name="exportrequest",
            name="format",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("DOCX", "Word (DOCX)"),
                    ("XLSX", "Excel (XLSX)"),
                    ("CSV", "CSV"),
                    ("PRINT_HTML", "Print-ready HTML"),
                    ("PNG", "PNG Image"),
                    ("JPEG", "JPEG Image"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Format",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledExport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Report"),
                            ("REGISTER", "Organizational Register"),
                            ("DIRECTORY", "People Directory"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("MEETING", "Meeting"),
                            ("DOCUMENT", "Document Metadata"),
                            ("SEARCH", "Search Results"),
                        ],
                        max_length=20,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "Word (DOCX)"),
                            ("XLSX", "Excel (XLSX)"),
                            ("CSV", "CSV"),
                            ("PRINT_HTML", "Print-ready HTML"),
                            ("PNG", "PNG Image"),
                            ("JPEG", "JPEG Image"),
                        ],
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filters"),
                ),
                (
                    "selected_columns",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Selected columns"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                            ("CUSTOM", "Custom (cron)"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Used when frequency is CUSTOM",
                        max_length=100,
                        verbose_name="Cron expression",
                    ),
                ),
                (
                    "run_at_time",
                    models.TimeField(default="02:00", verbose_name="Run at time"),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Day of week (1=Mon)"
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Day of month"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last run"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next run"
                    ),
                ),
                (
                    "notify_on_completion",
                    models.BooleanField(
                        default=True, verbose_name="Notify on completion"
                    ),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(default=True, verbose_name="Notify on failure"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Export",
                "verbose_name_plural": "Scheduled Exports",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ExportQueue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priority")),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Attempts"),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=3, verbose_name="Max attempts"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled for"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "failure_summary",
                    models.TextField(blank=True, verbose_name="Failure summary"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Error code"
                    ),
                ),
                (
                    "export_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entry",
                        to="exports.exportrequest",
                        verbose_name="Export request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Queue",
                "verbose_name_plural": "Export Queue",
                "ordering": ("-priority", "scheduled_for", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="exports_exp_status_debf17_idx",
                    ),
                    models.Index(
                        fields=["scheduled_for"], name="exports_exp_schedul_a367c8_idx"
                    ),
                ],
            },
        ),
    ]
