# Generated by Django 5.1 on 2026-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_add_queue_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrequest",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, verbose_name="Barcode"),
        ),
        migrations.AddField(
            model_name="exportrequest",
            name="digital_signature",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Digital signature"
            ),
        ),
        migrations.AddField(
            model_name="exportrequest",
            name="qr_code",
            field=models.TextField(blank=True, verbose_name="QR code data"),
        ),
    ]
