# Generated by Django 5.1 on 2026-08-21 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0003_add_digital_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        db_index=True,
                        default="DAILY",
                        max_length=20,
                        verbose_name="Period type",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(db_index=True, verbose_name="Period start"),
                ),
                (
                    "period_end",
                    models.DateTimeField(db_index=True, verbose_name="Period end"),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Empty means aggregate across all source types",
                        max_length=20,
                        verbose_name="Source type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Empty means aggregate across all formats",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "total_exports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total exports"
                    ),
                ),
                (
                    "completed_exports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed exports"
                    ),
                ),
                (
                    "failed_exports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed exports"
                    ),
                ),
                (
                    "cancelled_exports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cancelled exports"
                    ),
                ),
                (
                    "expired_exports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Expired exports"
                    ),
                ),
                (
                    "total_records_exported",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total records exported"
                    ),
                ),
                (
                    "total_file_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total file size (bytes)"
                    ),
                ),
                (
                    "avg_generation_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Average generation time (ms)"
                    ),
                ),
                (
                    "avg_file_size_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Average file size (bytes)"
                    ),
                ),
                (
                    "storage_used_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Storage used (bytes)"
                    ),
                ),
                (
                    "storage_expired_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Storage expired (bytes)"
                    ),
                ),
                (
                    "template_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of template code -> count",
                        verbose_name="Template usage",
                    ),
                ),
                (
                    "user_activity",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of user_id -> export count",
                        verbose_name="User activity",
                    ),
                ),
                (
                    "format_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of format -> count",
                        verbose_name="Format distribution",
                    ),
                ),
                (
                    "source_type_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of source_type -> count",
                        verbose_name="Source type distribution",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty means aggregate across all users",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_analytics_agg",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Analytics",
                "verbose_name_plural": "Export Analytics",
                "ordering": ("-period_start",),
                "indexes": [
                    models.Index(
                        fields=["period", "period_start"],
                        name="exports_exp_period_0ab1ee_idx",
                    ),
                    models.Index(
                        fields=["source_type", "period_start"],
                        name="exports_exp_source__f50efb_idx",
                    ),
                    models.Index(
                        fields=["format", "period_start"],
                        name="exports_exp_format_d05b20_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "period_start"],
                        name="exports_exp_request_4c45aa_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "period",
                            "period_start",
                            "source_type",
                            "format",
                            "requested_by",
                        ),
                        name="export_analytics_unique_period_dimensions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportTemplateAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        db_index=True,
                        default="DAILY",
                        max_length=20,
                        verbose_name="Period type",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(db_index=True, verbose_name="Period start"),
                ),
                (
                    "period_end",
                    models.DateTimeField(db_index=True, verbose_name="Period end"),
                ),
                (
                    "export_count",
                    models.PositiveIntegerField(default=0, verbose_name="Export count"),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed count"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Failed count"),
                ),
                (
                    "total_records",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total records"
                    ),
                ),
                (
                    "total_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total size (bytes)"
                    ),
                ),
                (
                    "avg_generation_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Average generation time (ms)"
                    ),
                ),
                (
                    "format_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Format breakdown"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="exports.exporttemplate",
                        verbose_name="Export template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Template Analytics",
                "verbose_name_plural": "Export Template Analytics",
                "ordering": ("-period_start",),
                "indexes": [
                    models.Index(
                        fields=["template", "period_start"],
                        name="exports_exp_templat_c0aa29_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "period", "period_start"),
                        name="export_template_analytics_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportUserAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        db_index=True,
                        default="DAILY",
                        max_length=20,
                        verbose_name="Period type",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(db_index=True, verbose_name="Period start"),
                ),
                (
                    "period_end",
                    models.DateTimeField(db_index=True, verbose_name="Period end"),
                ),
                (
                    "export_count",
                    models.PositiveIntegerField(default=0, verbose_name="Export count"),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed count"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Failed count"),
                ),
                (
                    "total_records",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total records"
                    ),
                ),
                (
                    "total_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Total size (bytes)"
                    ),
                ),
                (
                    "format_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Format breakdown"
                    ),
                ),
                (
                    "source_type_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Source type breakdown"
                    ),
                ),
                (
                    "template_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Template breakdown"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analytics_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export User Analytics",
                "verbose_name_plural": "Export User Analytics",
                "ordering": ("-period_start",),
                "indexes": [
                    models.Index(
                        fields=["user", "period_start"],
                        name="exports_exp_user_id_66b9fc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "period", "period_start"),
                        name="export_user_analytics_unique",
                    )
                ],
            },
        ),
    ]
