# Generated by Django 5.1 on 2026-08-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_profiles",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_profiles",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_profiles",
                to="locations.ward",
                verbose_name="Ward / Community",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_applications",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_applications",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_applications",
                to="locations.ward",
                verbose_name="Ward / Community",
            ),
        ),
        migrations.AddField(
            model_name="membershiptransfer",
            name="from_district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.district",
                verbose_name="From District",
            ),
        ),
        migrations.AddField(
            model_name="membershiptransfer",
            name="from_province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.province",
                verbose_name="From Province",
            ),
        ),
        migrations.AddField(
            model_name="membershiptransfer",
            name="to_district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.district",
                verbose_name="To District",
            ),
        ),
        migrations.AddField(
            model_name="membershiptransfer",
            name="to_province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.province",
                verbose_name="To Province",
            ),
        ),
    ]
