# Generated by Django 5.1 on 2026-08-05 05:25

import apps.programs.storage
import apps.programs.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_lessonslearned_procurementrequest_resourceallocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryParticipation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participation_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("activity_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("services_received", models.TextField(blank=True)),
                ("outcomes_achieved", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Beneficiary Participation",
                "verbose_name_plural": "Beneficiary Participations",
                "ordering": ("-participation_date",),
            },
        ),
        migrations.CreateModel(
            name="EvidenceVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(db_index=True)),
                (
                    "file",
                    models.FileField(
                        storage=apps.programs.storage.PrivateProgramStorage(),
                        upload_to="programs/evidence/versions/",
                        validators=[apps.programs.validators.validate_program_document],
                        verbose_name="Version file",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evidence Version",
                "verbose_name_plural": "Evidence Versions",
                "ordering": ("evidence", "-version_number"),
            },
        ),
        migrations.CreateModel(
            name="ProjectClosure",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VERIFIED", "Verified"),
                            ("APPROVED", "Approved"),
                            ("COMPLETE", "Complete"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("completion_verification", models.TextField(blank=True)),
                ("financial_reconciliation", models.TextField(blank=True)),
                ("final_evaluation_notes", models.TextField(blank=True)),
                ("asset_handover", models.TextField(blank=True)),
                ("stakeholder_signoff", models.TextField(blank=True)),
                ("final_documentation", models.TextField(blank=True)),
                ("closure_notes", models.TextField(blank=True)),
                (
                    "closure_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Project Closure",
                "verbose_name_plural": "Project Closures",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PROGRESS", "Progress report"),
                            ("WORK_PLAN", "Work plan report"),
                            ("ACTIVITY", "Activity report"),
                            ("TASK", "Task report"),
                            ("MILESTONE", "Milestone report"),
                            ("BUDGET", "Budget utilization report"),
                            ("RESOURCE", "Resource utilization report"),
                            ("BENEFICIARY", "Beneficiary report"),
                            ("RISK", "Risk register"),
                            ("ISSUE", "Issue register"),
                            ("DELIVERABLE", "Deliverables report"),
                            ("PROCUREMENT", "Procurement report"),
                            ("CLOSURE", "Project closure report"),
                            ("LESSONS", "Lessons learned report"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Report type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("period_label", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.programs.storage.PrivateProgramStorage(),
                        upload_to="programs/reports/",
                        validators=[apps.programs.validators.validate_program_document],
                        verbose_name="Report file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Report",
                "verbose_name_plural": "Project Reports",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("OUTPUT", "Output"),
                            ("OUTCOME", "Outcome"),
                            ("IMPACT", "Impact"),
                        ],
                        db_index=True,
                        default="OUTPUT",
                        max_length=20,
                        verbose_name="Result type",
                    ),
                ),
                ("code", models.CharField(max_length=80, verbose_name="Result code")),
                ("description", models.TextField()),
                ("indicator", models.CharField(blank=True, max_length=255)),
                ("baseline", models.CharField(blank=True, max_length=120)),
                ("target", models.CharField(blank=True, max_length=120)),
                ("actual", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("PARTIAL", "Partially achieved"),
                            ("ACHIEVED", "Achieved"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Project Result",
                "verbose_name_plural": "Project Results",
                "ordering": ("project", "result_type", "code"),
            },
        ),
        migrations.CreateModel(
            name="ProjectTimeline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("planned_start_date", models.DateField(db_index=True)),
                ("planned_end_date", models.DateField(db_index=True)),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("DELAYED", "Delayed"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project Timeline",
                "verbose_name_plural": "Project Timelines",
                "ordering": ("order", "planned_start_date"),
            },
        ),
        migrations.CreateModel(
            name="WBSNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="WBS node ID",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("PHASE", "Phase"),
                            ("WORK_PACKAGE", "Work package"),
                            ("ACTIVITY", "Activity"),
                            ("TASK", "Task"),
                            ("SUB_TASK", "Sub-task"),
                        ],
                        db_index=True,
                        default="WORK_PACKAGE",
                        max_length=20,
                        verbose_name="Node type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="WBS code"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "planned_start_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "planned_end_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_effort_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimated effort (hours)",
                    ),
                ),
                (
                    "actual_effort_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual effort (hours)",
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[apps.programs.validators.validate_percentage],
                        verbose_name="Completion percentage",
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Budget allocated",
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Budget spent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "WBS Node",
                "verbose_name_plural": "WBS Nodes",
                "ordering": ("project", "code", "title"),
            },
        ),
        migrations.AddField(
            model_name="deliverable",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_deliverables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidencerecord",
            name="version_number",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="milestone",
            name="approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="milestone",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="milestone",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="classifications",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"kind": "PROJECT_CLASSIFICATION"},
                related_name="classified_projects",
                to="programs.programreferencedata",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=5,
                validators=[apps.programs.validators.validate_percentage],
                verbose_name="Completion percentage",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Approval status",
            ),
        ),
        migrations.AlterField(
            model_name="programreferencedata",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CATEGORY", "Program category"),
                    ("PROJECT_CATEGORY", "Project category"),
                    ("PILLAR", "Organizational pillar"),
                    ("SDG", "Sustainable Development Goal"),
                    ("FUNDING_SOURCE", "Funding source"),
                    ("BENEFICIARY_CATEGORY", "Beneficiary category"),
                    ("RISK_CATEGORY", "Risk category"),
                    ("INDICATOR_TYPE", "Indicator type"),
                    ("RESOURCE_TYPE", "Resource type"),
                    ("DOCUMENT_TYPE", "Document type"),
                    ("LESSON_CATEGORY", "Lessons learned category"),
                    ("EVIDENCE_TYPE", "Evidence type"),
                    ("BUDGET_CATEGORY", "Budget category"),
                    ("PROJECT_CLASSIFICATION", "Project classification"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Kind",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "approval_status"],
                name="programs_mi_project_883622_idx",
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryparticipation",
            name="beneficiary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="programs.beneficiaryrecord",
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryparticipation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryparticipation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="evidenceversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="evidenceversion",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="programs.evidencerecord",
            ),
        ),
        migrations.AddField(
            model_name="evidenceversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_project_closures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="closure",
                to="programs.project",
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_project_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="programs.project",
            ),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_project_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="projectresult",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="projectresult",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="programs.project",
            ),
        ),
        migrations.AddField(
            model_name="projectresult",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="projecttimeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="projecttimeline",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_entries",
                to="programs.projecttimeline",
            ),
        ),
        migrations.AddField(
            model_name="projecttimeline",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_entries",
                to="programs.project",
            ),
        ),
        migrations.AddField(
            model_name="projecttimeline",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="programs.wbsnode"
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="programs.wbsnode",
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wbs_nodes",
                to="programs.project",
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="responsible_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_wbs_nodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wbsnode",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiaryparticipation",
            index=models.Index(
                fields=["beneficiary", "participation_date"],
                name="programs_be_benefic_3f806f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceversion",
            constraint=models.UniqueConstraint(
                fields=("evidence", "version_number"),
                name="evidence_version_number_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="projectclosure",
            index=models.Index(
                fields=["project", "status"], name="programs_pr_project_edbb3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreport",
            index=models.Index(
                fields=["project", "report_type", "status"],
                name="programs_pr_project_1b9788_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectresult",
            index=models.Index(
                fields=["project", "result_type", "status"],
                name="programs_pr_project_3c6b9e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectresult",
            constraint=models.UniqueConstraint(
                fields=("project", "result_type", "code"),
                name="project_result_type_code_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="projecttimeline",
            index=models.Index(
                fields=["project", "status", "planned_start_date"],
                name="programs_pr_project_20b4d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wbsnode",
            index=models.Index(
                fields=["project", "parent"], name="programs_wb_project_efd8c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wbsnode",
            index=models.Index(
                fields=["project", "status"], name="programs_wb_project_0092ed_idx"
            ),
        ),
    ]
