# Generated by Django 5.1 on 2026-08-05 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_milestone_submitted_at_milestone_submitted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="proposed_value",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="reviewer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="target_field",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="target_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="target_record_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
