# Generated by Django 6.0.8 on 2026-08-16 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Integration Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Service"),
                            ("auth", "Authentication"),
                            ("storage", "Storage"),
                            ("notification", "Notifications"),
                            ("api", "External API"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Integration Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Credentials"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync"
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("never", "Never Synced"),
                        ],
                        default="never",
                        max_length=20,
                        verbose_name="Last Status",
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="Last Error")),
            ],
            options={
                "verbose_name": "Integration Settings",
                "verbose_name_plural": "Integration Settings",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="default",
                        help_text="Unique key to enforce singleton pattern.",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="SITADC Youth Hub",
                        max_length=150,
                        verbose_name="System Name",
                    ),
                ),
                (
                    "system_short_name",
                    models.CharField(
                        default="SITADC Hub",
                        max_length=50,
                        verbose_name="System Short Name",
                    ),
                ),
                (
                    "system_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="System Email"
                    ),
                ),
                (
                    "system_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Maintenance"),
                            ("disabled", "Disabled"),
                        ],
                        default="operational",
                        max_length=20,
                        verbose_name="System Status",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Maintenance Mode"),
                ),
                (
                    "maintenance_message",
                    models.TextField(blank=True, verbose_name="Maintenance Message"),
                ),
                (
                    "maintenance_allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Allowed Roles During Maintenance",
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Session Timeout (minutes)"
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Minimum Password Length"
                    ),
                ),
                (
                    "password_require_uppercase",
                    models.BooleanField(default=True, verbose_name="Require Uppercase"),
                ),
                (
                    "password_require_lowercase",
                    models.BooleanField(default=True, verbose_name="Require Lowercase"),
                ),
                (
                    "password_require_digits",
                    models.BooleanField(default=True, verbose_name="Require Digits"),
                ),
                (
                    "password_require_special",
                    models.BooleanField(
                        default=True, verbose_name="Require Special Characters"
                    ),
                ),
                (
                    "password_expiry_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Password Expiry (days)"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Max Login Attempts"
                    ),
                ),
                (
                    "lockout_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Lockout Duration (minutes)"
                    ),
                ),
                (
                    "require_2fa_admin",
                    models.BooleanField(
                        default=False, verbose_name="Require 2FA for Admins"
                    ),
                ),
                (
                    "max_upload_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Max Upload Size (MB)"
                    ),
                ),
                (
                    "allowed_file_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed File Types"
                    ),
                ),
                (
                    "audit_log_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Audit Logging Enabled"
                    ),
                ),
                (
                    "audit_retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Audit Retention (days)"
                    ),
                ),
                (
                    "backup_enabled",
                    models.BooleanField(default=True, verbose_name="Backup Enabled"),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Backup Frequency",
                    ),
                ),
                (
                    "backup_retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Backup Retention (days)"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="UserSettingsDefault",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="defaults",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System Default"),
                        ],
                        default="system",
                        max_length=10,
                        verbose_name="Default Theme",
                    ),
                ),
                (
                    "default_density",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("comfortable", "Comfortable"),
                        ],
                        default="comfortable",
                        max_length=15,
                        verbose_name="Default Density",
                    ),
                ),
                (
                    "default_dashboard_layout",
                    models.CharField(
                        choices=[
                            ("grid", "Grid"),
                            ("list", "List"),
                            ("masonry", "Masonry"),
                        ],
                        default="grid",
                        max_length=20,
                        verbose_name="Default Dashboard Layout",
                    ),
                ),
                (
                    "default_animations",
                    models.BooleanField(
                        default=True, verbose_name="Default Animations Enabled"
                    ),
                ),
                (
                    "default_email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Default Email Notifications"
                    ),
                ),
                (
                    "default_in_app_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Default In-App Notifications"
                    ),
                ),
                (
                    "default_browser_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Default Browser Notifications"
                    ),
                ),
                (
                    "default_profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization Only"),
                            ("team", "Team Only"),
                            ("private", "Private"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Default Profile Visibility",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Default Language"
                    ),
                ),
                (
                    "default_country",
                    models.CharField(
                        default="ZM", max_length=2, verbose_name="Default Country"
                    ),
                ),
                (
                    "default_timezone",
                    models.CharField(
                        default="Africa/Lusaka",
                        max_length=50,
                        verbose_name="Default Timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings Defaults",
                "verbose_name_plural": "User Settings Defaults",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System Default"),
                        ],
                        default="system",
                        max_length=10,
                        verbose_name="Theme",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color token: primary, secondary, success, danger, warning, info",
                        max_length=20,
                        verbose_name="Accent Color",
                    ),
                ),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("comfortable", "Comfortable"),
                        ],
                        default="comfortable",
                        max_length=15,
                        verbose_name="Interface Density",
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False, verbose_name="Sidebar Collapsed"
                    ),
                ),
                (
                    "dashboard_layout",
                    models.CharField(
                        choices=[
                            ("grid", "Grid"),
                            ("list", "List"),
                            ("masonry", "Masonry"),
                        ],
                        default="grid",
                        max_length=20,
                        verbose_name="Dashboard Layout",
                    ),
                ),
                (
                    "animations_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Animations Enabled"
                    ),
                ),
                (
                    "reduced_motion",
                    models.BooleanField(default=False, verbose_name="Reduced Motion"),
                ),
                (
                    "high_contrast",
                    models.BooleanField(default=False, verbose_name="High Contrast"),
                ),
                (
                    "larger_text",
                    models.BooleanField(default=False, verbose_name="Larger Text"),
                ),
                (
                    "focus_indicators",
                    models.BooleanField(default=True, verbose_name="Focus Indicators"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Email Notifications"
                    ),
                ),
                (
                    "in_app_notifications",
                    models.BooleanField(
                        default=True, verbose_name="In-App Notifications"
                    ),
                ),
                (
                    "browser_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Browser Notifications"
                    ),
                ),
                (
                    "report_reminders",
                    models.BooleanField(default=True, verbose_name="Report Reminders"),
                ),
                (
                    "report_submission_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Report Submission Notifications"
                    ),
                ),
                (
                    "report_review_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Report Review Notifications"
                    ),
                ),
                (
                    "approval_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Approval Notifications"
                    ),
                ),
                (
                    "meeting_reminders",
                    models.BooleanField(default=True, verbose_name="Meeting Reminders"),
                ),
                (
                    "training_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Training Reminders"
                    ),
                ),
                (
                    "task_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Task Notifications"
                    ),
                ),
                (
                    "system_announcements",
                    models.BooleanField(
                        default=True, verbose_name="System Announcements"
                    ),
                ),
                (
                    "security_alerts",
                    models.BooleanField(default=True, verbose_name="Security Alerts"),
                ),
                (
                    "organizational_announcements",
                    models.BooleanField(
                        default=True, verbose_name="Organizational Announcements"
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization Only"),
                            ("team", "Team Only"),
                            ("private", "Private"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Profile Visibility",
                    ),
                ),
                (
                    "contact_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization Only"),
                            ("team", "Team Only"),
                            ("private", "Private"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Contact Information Visibility",
                    ),
                ),
                (
                    "activity_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization Only"),
                            ("team", "Team Only"),
                            ("private", "Private"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Activity Visibility",
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=True, verbose_name="Show Online Status"
                    ),
                ),
                (
                    "directory_visibility",
                    models.BooleanField(
                        default=True, verbose_name="Directory Visibility"
                    ),
                ),
                (
                    "data_sharing",
                    models.BooleanField(
                        default=False, verbose_name="Data Sharing Preferences"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Language"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="ZM", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Lusaka", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="Y-m-d", max_length=20, verbose_name="Date Format"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="H:i:s", max_length=20, verbose_name="Time Format"
                    ),
                ),
                (
                    "currency_format",
                    models.CharField(
                        default="ZMW", max_length=10, verbose_name="Currency Format"
                    ),
                ),
                (
                    "first_day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        verbose_name="First Day of Week",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
