# Generated by Django 5.1 on 2026-08-01 12:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=60,
                        unique=True,
                        verbose_name="Application reference",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=150, verbose_name="Full name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Phone number"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=20, verbose_name="Gender"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Residential address"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "Community Volunteer"),
                            ("STUDENT", "Student Volunteer"),
                            ("YOUTH", "Youth Volunteer"),
                            ("PROFESSIONAL", "Professional Volunteer"),
                            ("TECHNICAL", "Technical Volunteer"),
                            ("PROGRAM", "Program Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("REMOTE", "Remote Volunteer"),
                            ("INTERNATIONAL", "International Volunteer"),
                        ],
                        max_length=40,
                        verbose_name="Preferred category",
                    ),
                ),
                (
                    "volunteer_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time Volunteer"),
                            ("PART_TIME", "Part-Time Volunteer"),
                            ("PROJECT_BASED", "Project-Based Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("ONLINE", "Online / Virtual Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("SPECIALIST", "Specialist Volunteer"),
                            ("MENTOR", "Mentor"),
                            ("TRAINER", "Trainer"),
                            ("ADVISORY", "Advisory Volunteer"),
                        ],
                        max_length=40,
                        verbose_name="Preferred type",
                    ),
                ),
                (
                    "skills",
                    models.TextField(blank=True, verbose_name="Skills & experience"),
                ),
                (
                    "motivation",
                    models.TextField(blank=True, verbose_name="Motivation statement"),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="volunteers/applications/cv/",
                        verbose_name="Curriculum Vitae (CV)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_SCREENING", "Under Screening"),
                            ("SHORTLISTED", "Shortlisted for Interview"),
                            ("INTERVIEWED", "Interviewed"),
                            ("APPROVED", "Approved for Onboarding"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Application",
                "verbose_name_plural": "Volunteer Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Volunteer profile created"),
                            ("UPDATED", "Volunteer profile updated"),
                            ("STATUS_CHANGED", "Volunteer status changed"),
                            ("DEPLOYED", "Volunteer deployed"),
                            ("ATTENDANCE_LOGGED", "Attendance logged"),
                            ("TRAINING_COMPLETED", "Training recorded"),
                            ("REVIEWED", "Performance review completed"),
                            ("AWARDED", "Recognition awarded"),
                            ("LEAVE_APPROVED", "Leave approved"),
                            ("EXITED", "Volunteer exited"),
                            ("ARCHIVED", "Volunteer profile archived"),
                            ("RESTORED", "Volunteer profile restored"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data before change"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data after change"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Audit Record",
                "verbose_name_plural": "Volunteer Audit Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerInterview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "scheduled_datetime",
                    models.DateTimeField(verbose_name="Scheduled date and time"),
                ),
                (
                    "venue_or_link",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Venue / Online Link"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Interview score (0-100)"
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="Recommendation & Notes"),
                ),
                (
                    "passed",
                    models.BooleanField(default=False, verbose_name="Interview passed"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="volunteers.volunteerapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Interview",
                "verbose_name_plural": "Volunteer Interviews",
            },
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        help_text="Immutable reference number issued by the numbering service (e.g. SITADC-VOL-2026-000001).",
                        max_length=60,
                        unique=True,
                        verbose_name="Volunteer reference number",
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional Phase 12 membership number link.",
                        max_length=60,
                        verbose_name="Membership number",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="National ID / Passport"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="volunteers/profiles/",
                        verbose_name="Profile photograph",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=20, verbose_name="Gender"),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Zambian", max_length=60, verbose_name="Nationality"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "residential_address",
                    models.TextField(blank=True, verbose_name="Residential address"),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Region / Province"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                (
                    "community",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Community"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Emergency contact name",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="Emergency contact relationship",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Emergency contact phone",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Highest level of education",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Occupation / Profession",
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated languages.",
                        max_length=255,
                        verbose_name="Languages spoken",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "Community Volunteer"),
                            ("STUDENT", "Student Volunteer"),
                            ("YOUTH", "Youth Volunteer"),
                            ("PROFESSIONAL", "Professional Volunteer"),
                            ("TECHNICAL", "Technical Volunteer"),
                            ("PROGRAM", "Program Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("REMOTE", "Remote Volunteer"),
                            ("INTERNATIONAL", "International Volunteer"),
                        ],
                        db_index=True,
                        default="COMMUNITY",
                        max_length=40,
                        verbose_name="Volunteer category",
                    ),
                ),
                (
                    "volunteer_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time Volunteer"),
                            ("PART_TIME", "Part-Time Volunteer"),
                            ("PROJECT_BASED", "Project-Based Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("ONLINE", "Online / Virtual Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("SPECIALIST", "Specialist Volunteer"),
                            ("MENTOR", "Mentor"),
                            ("TRAINER", "Trainer"),
                            ("ADVISORY", "Advisory Volunteer"),
                        ],
                        db_index=True,
                        default="PART_TIME",
                        max_length=40,
                        verbose_name="Volunteer type",
                    ),
                ),
                (
                    "volunteer_level",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Level"),
                            ("REGIONAL", "Regional Level"),
                            ("DISTRICT", "District Level"),
                            ("COMMUNITY", "Community Level"),
                            ("TEAM", "Team Level"),
                        ],
                        db_index=True,
                        default="COMMUNITY",
                        max_length=40,
                        verbose_name="Volunteer level",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time"),
                            ("PART_TIME", "Part-Time"),
                            ("WEEKDAYS", "Weekdays"),
                            ("WEEKENDS", "Weekends"),
                            ("EVENINGS", "Evenings"),
                            ("REMOTE", "Remote / Online"),
                            ("FIELD", "Field-Based"),
                            ("SEASONAL", "Seasonal"),
                        ],
                        default="PART_TIME",
                        max_length=40,
                        verbose_name="Availability type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("APPROVED", "Approved"),
                            ("REGISTERED", "Registered"),
                            ("ONBOARDING", "Onboarding"),
                            ("ACTIVE", "Active"),
                            ("ASSIGNED", "Assigned"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                            ("EXITED", "Exited"),
                            ("ALUMNI", "Alumni"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="APPLICANT",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Volunteer start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected end date"
                    ),
                ),
                (
                    "exit_date",
                    models.DateField(blank=True, null=True, verbose_name="Exit date"),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("CONTRACT_COMPLETION", "Contract Completion"),
                            ("DISMISSAL", "Dismissal / Termination"),
                            ("RETIREMENT", "Retirement"),
                            ("TRANSFER", "Transfer"),
                            ("ALUMNI_TRANSITION", "Transition to Alumni"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Exit reason",
                    ),
                ),
                (
                    "biography",
                    models.TextField(blank=True, verbose_name="Biography / Summary"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_volunteers",
                        to="volunteers.volunteerprofile",
                        verbose_name="Assigned supervisor",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunteer_team_members",
                        to="organizations.organizationunit",
                        verbose_name="Assigned organizational team / unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Linked user account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Profile",
                "verbose_name_plural": "Volunteer Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerPerformance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "review_period",
                    models.CharField(
                        max_length=60, verbose_name="Review Period (e.g. 2026 Q1)"
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="Overall Score (1-100)"
                    ),
                ),
                (
                    "kpis_met",
                    models.TextField(
                        blank=True, verbose_name="KPIs & Targets Achieved"
                    ),
                ),
                (
                    "strengths",
                    models.TextField(blank=True, verbose_name="Key Strengths"),
                ),
                (
                    "areas_for_growth",
                    models.TextField(
                        blank=True, verbose_name="Areas for Growth & Coaching"
                    ),
                ),
                (
                    "community_feedback",
                    models.TextField(
                        blank=True, verbose_name="Community / Beneficiary Feedback"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Review Date"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Performance Review",
                "verbose_name_plural": "Volunteer Performance Reviews",
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerOnboarding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "orientation_completed",
                    models.BooleanField(
                        default=False, verbose_name="Orientation completed"
                    ),
                ),
                (
                    "code_of_conduct_signed",
                    models.BooleanField(
                        default=False, verbose_name="Code of conduct signed"
                    ),
                ),
                (
                    "safeguarding_agreed",
                    models.BooleanField(
                        default=False, verbose_name="Safeguarding policy agreed"
                    ),
                ),
                (
                    "confidentiality_signed",
                    models.BooleanField(
                        default=False, verbose_name="Confidentiality agreement signed"
                    ),
                ),
                (
                    "welcome_pack_issued",
                    models.BooleanField(
                        default=False, verbose_name="Welcome pack issued"
                    ),
                ),
                (
                    "id_card_issued",
                    models.BooleanField(default=False, verbose_name="ID Card issued"),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Onboarding complete"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completion date"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Onboarding",
                "verbose_name_plural": "Volunteer Onboardings",
            },
        ),
        migrations.CreateModel(
            name="VolunteerLeave",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("MEDICAL", "Medical / Sick Leave"),
                            ("STUDY", "Study Leave"),
                            ("PERSONAL", "Personal Leave"),
                            ("COMPASSIONATE", "Compassionate Leave"),
                        ],
                        default="ANNUAL",
                        max_length=30,
                        verbose_name="Leave Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("reason", models.TextField(verbose_name="Reason for Leave")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True, verbose_name="Approval / Rejection Notes"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_volunteer_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Leave Application",
                "verbose_name_plural": "Volunteer Leave Applications",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerExit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("RESIGNATION", "Resignation"),
                            ("CONTRACT_COMPLETION", "Contract Completion"),
                            ("DISMISSAL", "Dismissal / Termination"),
                            ("RETIREMENT", "Retirement"),
                            ("TRANSFER", "Transfer"),
                            ("ALUMNI_TRANSITION", "Transition to Alumni"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Exit Reason",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(verbose_name="Effective Exit Date"),
                ),
                (
                    "exit_interview_notes",
                    models.TextField(blank=True, verbose_name="Exit Interview Notes"),
                ),
                (
                    "assets_returned",
                    models.BooleanField(
                        default=False, verbose_name="Assets & Badges Returned"
                    ),
                ),
                (
                    "documents_returned",
                    models.BooleanField(
                        default=False, verbose_name="Documents & Files Returned"
                    ),
                ),
                (
                    "clearance_approved",
                    models.BooleanField(
                        default=False, verbose_name="Supervisor Clearance Approved"
                    ),
                ),
                (
                    "transition_to_alumni",
                    models.BooleanField(
                        default=True,
                        verbose_name="Transfer to Volunteer Alumni Network",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("INTERVIEW_COMPLETED", "Exit Interview Completed"),
                            ("CLEARANCE_PENDING", "Clearance Pending"),
                            ("APPROVED", "Approved"),
                            ("EXITED", "Exited"),
                            ("ALUMNI", "Transferred to Alumni"),
                        ],
                        default="INITIATED",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_record",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Exit Record",
                "verbose_name_plural": "Volunteer Exit Records",
            },
        ),
        migrations.CreateModel(
            name="VolunteerDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Document Title"),
                ),
                (
                    "document_type",
                    models.CharField(
                        default="General", max_length=100, verbose_name="Document Type"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="volunteers/documents/", verbose_name="File"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Document",
                "verbose_name_plural": "Volunteer Documents",
            },
        ),
        migrations.CreateModel(
            name="VolunteerDeploymentHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "assignment_title",
                    models.CharField(max_length=200, verbose_name="Assignment Title"),
                ),
                (
                    "program_or_project",
                    models.CharField(max_length=200, verbose_name="Program / Project"),
                ),
                (
                    "community_served",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Community Served"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "supervisor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Supervisor Name"
                    ),
                ),
                (
                    "outcomes_summary",
                    models.TextField(
                        blank=True, verbose_name="Outcomes & Impact Summary"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_history",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Deployment History",
                "verbose_name_plural": "Volunteer Deployment Histories",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerAttendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date",
                    models.DateField(db_index=True, verbose_name="Date of Service"),
                ),
                (
                    "activity_name",
                    models.CharField(
                        max_length=200, verbose_name="Activity / Event Name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Service"),
                            ("WEEKLY", "Weekly Service"),
                            ("MONTHLY", "Monthly Service"),
                            ("MEETING", "Meeting"),
                            ("TRAINING", "Training Session"),
                            ("OUTREACH", "Community Outreach"),
                            ("WORKSHOP", "Workshop"),
                            ("CAMPAIGN", "Campaign Activity"),
                        ],
                        default="DAILY",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("EXCUSED", "Excused"),
                            ("LATE", "Late"),
                            ("REMOTE", "Remote Participation"),
                        ],
                        default="PRESENT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "hours_served",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Hours served",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Location"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Attendance",
                "verbose_name_plural": "Volunteer Attendance Logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Assignment / Role Title"
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Program Name"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Project Name"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, verbose_name="Key Objectives & Deliverables"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active assignment"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunteer_assignments",
                        to="organizations.organizationunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="volunteers.volunteerprofile",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_assignments",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Assignment",
                "verbose_name_plural": "Volunteer Assignments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerRecognition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Award / Recognition Title"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CERTIFICATE", "Certificate of Service"),
                            ("APPRECIATION_AWARD", "Appreciation Award"),
                            ("VOLUNTEER_OF_MONTH", "Volunteer of the Month"),
                            ("YEARS_OF_SERVICE", "Years of Service Award"),
                            ("ACHIEVEMENT_BADGE", "Achievement Badge"),
                            ("PUBLIC_RECOGNITION", "Public Recognition"),
                        ],
                        default="CERTIFICATE",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                (
                    "award_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Award Date"
                    ),
                ),
                (
                    "citation",
                    models.TextField(
                        blank=True, verbose_name="Citation / Reason for Award"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognitions",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Recognition",
                "verbose_name_plural": "Volunteer Recognitions",
                "ordering": ["-award_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerRecruitment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Recruitment title"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=60,
                        unique=True,
                        verbose_name="Campaign reference",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "Community Volunteer"),
                            ("STUDENT", "Student Volunteer"),
                            ("YOUTH", "Youth Volunteer"),
                            ("PROFESSIONAL", "Professional Volunteer"),
                            ("TECHNICAL", "Technical Volunteer"),
                            ("PROGRAM", "Program Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("REMOTE", "Remote Volunteer"),
                            ("INTERNATIONAL", "International Volunteer"),
                        ],
                        max_length=40,
                        verbose_name="Volunteer category",
                    ),
                ),
                (
                    "volunteer_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time Volunteer"),
                            ("PART_TIME", "Part-Time Volunteer"),
                            ("PROJECT_BASED", "Project-Based Volunteer"),
                            ("EVENT", "Event Volunteer"),
                            ("ONLINE", "Online / Virtual Volunteer"),
                            ("FIELD", "Field Volunteer"),
                            ("SPECIALIST", "Specialist Volunteer"),
                            ("MENTOR", "Mentor"),
                            ("TRAINER", "Trainer"),
                            ("ADVISORY", "Advisory Volunteer"),
                        ],
                        max_length=40,
                        verbose_name="Volunteer type",
                    ),
                ),
                (
                    "vacancies",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of vacancies"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Location / Region"
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True, verbose_name="Required skills & qualifications"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(verbose_name="Application deadline"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open for Applications"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_campaigns",
                        to="volunteers.volunteerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Recruitment Campaign",
                "verbose_name_plural": "Volunteer Recruitment Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="recruitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="volunteers.volunteerrecruitment",
            ),
        ),
        migrations.CreateModel(
            name="VolunteerScreening",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False, verbose_name="Identity verified"
                    ),
                ),
                (
                    "references_checked",
                    models.BooleanField(
                        default=False, verbose_name="References checked"
                    ),
                ),
                (
                    "qualifications_verified",
                    models.BooleanField(
                        default=False, verbose_name="Qualifications verified"
                    ),
                ),
                (
                    "safeguarding_cleared",
                    models.BooleanField(
                        default=False, verbose_name="Safeguarding assessment cleared"
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(default=False, verbose_name="Screening passed"),
                ),
                (
                    "review_date",
                    models.DateField(auto_now_add=True, verbose_name="Screening date"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening",
                        to="volunteers.volunteerapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Screening",
                "verbose_name_plural": "Volunteer Screenings",
            },
        ),
        migrations.CreateModel(
            name="VolunteerStatusHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "from_status",
                    models.CharField(max_length=40, verbose_name="From status"),
                ),
                (
                    "to_status",
                    models.CharField(max_length=40, verbose_name="To status"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Status History",
                "verbose_name_plural": "Volunteer Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerTraining",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Training Title"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Training Provider / Facilitator",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="Certificate Issued"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="volunteers/certificates/",
                        verbose_name="Certificate File",
                    ),
                ),
                (
                    "competencies_acquired",
                    models.TextField(blank=True, verbose_name="Competencies Acquired"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Training",
                "verbose_name_plural": "Volunteer Trainings",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerWelfare",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WELFARE_REQUEST", "Welfare Request"),
                            ("COUNSELING_REFERRAL", "Counseling Referral"),
                            ("MEDICAL_SUPPORT", "Medical Support"),
                            ("EMERGENCY_ASSISTANCE", "Emergency Assistance"),
                        ],
                        default="WELFARE_REQUEST",
                        max_length=40,
                        verbose_name="Support Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Details of Request / Referral"),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, verbose_name="Action Taken / Resolution"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Is Resolved"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welfare_records",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Welfare Record",
                "verbose_name_plural": "Volunteer Welfare Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerInterest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_name",
                    models.CharField(max_length=100, verbose_name="Interest area"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Interest",
                "verbose_name_plural": "Volunteer Interests",
                "unique_together": {("profile", "area_name")},
            },
        ),
        migrations.CreateModel(
            name="VolunteerSkill",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Skill name")),
                (
                    "category",
                    models.CharField(
                        default="Technical", max_length=50, verbose_name="Category"
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                        verbose_name="Proficiency level",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Skill",
                "verbose_name_plural": "Volunteer Skills",
                "unique_together": {("profile", "name")},
            },
        ),
    ]
