# Generated by Django 5.1 on 2026-08-02 06:05

import apps.volunteers.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        ("volunteers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerapplication",
            name="consent_confirmed",
            field=models.BooleanField(
                default=False,
                verbose_name="Privacy notice and application consent confirmed",
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="decision_notes",
            field=models.TextField(blank=True, verbose_name="Decision notes"),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reviewed at"
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_volunteer_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="is_confidential",
            field=models.BooleanField(default=True, verbose_name="Confidential"),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="volunteers/applications/cv/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="Curriculum Vitae (CV)",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("RETURNED", "Returned for correction"),
                    ("UNDER_SCREENING", "Under Screening"),
                    ("SHORTLISTED", "Shortlisted for Interview"),
                    ("INTERVIEWED", "Interviewed"),
                    ("APPROVED", "Approved for Onboarding"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerattendance",
            name="hours_served",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Hours served",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerauditrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Volunteer profile created"),
                    ("APPLICATION_SUBMITTED", "Application submitted"),
                    ("APPLICATION_REVIEWED", "Application reviewed"),
                    ("SCREENING_COMPLETED", "Screening completed"),
                    ("INTERVIEW_COMPLETED", "Interview completed"),
                    ("ONBOARDING_COMPLETED", "Onboarding completed"),
                    ("UPDATED", "Volunteer profile updated"),
                    ("STATUS_CHANGED", "Volunteer status changed"),
                    ("DEPLOYED", "Volunteer deployed"),
                    ("ATTENDANCE_LOGGED", "Attendance logged"),
                    ("TRAINING_COMPLETED", "Training recorded"),
                    ("REVIEWED", "Performance review completed"),
                    ("AWARDED", "Recognition awarded"),
                    ("LEAVE_APPROVED", "Leave approved"),
                    ("LEAVE_REJECTED", "Leave rejected"),
                    ("EXPORTED", "Volunteer data exported"),
                    ("DOCUMENT_DOWNLOADED", "Document downloaded"),
                    ("EXITED", "Volunteer exited"),
                    ("ARCHIVED", "Volunteer profile archived"),
                    ("RESTORED", "Volunteer profile restored"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerdocument",
            name="file",
            field=models.FileField(
                upload_to="volunteers/documents/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerinterview",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Interview score (0-100)",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerperformance",
            name="overall_score",
            field=models.PositiveSmallIntegerField(
                default=80,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Overall Score (1-100)",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="volunteers/profiles/",
                validators=[apps.volunteers.validators.validate_volunteer_image],
                verbose_name="Profile photograph",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="reference_number",
            field=models.CharField(
                db_index=True,
                help_text="Immutable reference number issued by the centralized numbering service.",
                max_length=60,
                unique=True,
                verbose_name="Volunteer reference number",
            ),
        ),
        migrations.AlterField(
            model_name="volunteertraining",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="volunteers/certificates/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="Certificate File",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerauditrecord",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="volunteers__entity__6fd8ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerprofile",
            index=models.Index(
                fields=["status", "category"], name="volunteers__status_a4ddac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerprofile",
            index=models.Index(
                fields=["team", "status"], name="volunteers__team_id_5bbb33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerprofile",
            index=models.Index(
                fields=["region", "district"], name="volunteers__region_f5edaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerstatushistory",
            index=models.Index(
                fields=["profile", "created_at"], name="volunteers__profile_a977e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerattendance",
            constraint=models.UniqueConstraint(
                fields=("profile", "date", "activity_name"),
                name="unique_volunteer_attendance_activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerperformance",
            constraint=models.UniqueConstraint(
                fields=("profile", "review_period"),
                name="unique_volunteer_review_period",
            ),
        ),
    ]
