# Generated by Django 5.1 on 2026-08-02 06:11

import apps.volunteers.storage
import apps.volunteers.validators
from pathlib import Path
import shutil
from django.conf import settings
from django.db import migrations, models


def move_existing_volunteer_files(apps, schema_editor):
    """Move legacy volunteer uploads out of publicly served media storage."""
    model_fields = (
        (apps.get_model("volunteers", "VolunteerApplication"), "cv_file"),
        (apps.get_model("volunteers", "VolunteerDocument"), "file"),
        (apps.get_model("volunteers", "VolunteerTraining"), "certificate_file"),
    )
    public_root = Path(settings.MEDIA_ROOT)
    private_root = Path(settings.PRIVATE_MEDIA_ROOT)
    for model, field_name in model_fields:
        for record in model.objects.exclude(**{field_name: ""}).iterator():
            name = getattr(record, field_name).name
            if not name:
                continue
            source = public_root / name
            destination = private_root / name
            if not source.exists():
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                source.unlink()
            else:
                shutil.move(str(source), str(destination))


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_volunteerapplication_consent_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerapplication",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                upload_to="volunteers/applications/cv/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="Curriculum Vitae (CV)",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerdocument",
            name="file",
            field=models.FileField(
                storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                upload_to="volunteers/documents/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="volunteertraining",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                upload_to="volunteers/certificates/",
                validators=[apps.volunteers.validators.validate_volunteer_document],
                verbose_name="Certificate File",
            ),
        ),
        migrations.RunPython(move_existing_volunteer_files, migrations.RunPython.noop),
    ]
