# Generated by Django 5.0.7 on 2026-08-03 04:48

import apps.volunteers.storage
import apps.volunteers.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_taxonomies(apps, schema_editor):
    """Seed the default configurable volunteer taxonomies (idempotent)."""
    VolunteerCategory = apps.get_model("volunteers", "VolunteerCategory")
    VolunteerType = apps.get_model("volunteers", "VolunteerType")
    VolunteerLevel = apps.get_model("volunteers", "VolunteerLevel")

    categories = [
        ("COMMUNITY", "Community Volunteer", 10),
        ("STUDENT", "Student Volunteer", 20),
        ("YOUTH", "Youth Volunteer", 30),
        ("PROFESSIONAL", "Professional Volunteer", 40),
        ("TECHNICAL", "Technical Volunteer", 50),
        ("PROGRAM", "Program Volunteer", 60),
        ("EVENT", "Event Volunteer", 70),
        ("FIELD", "Field Volunteer", 80),
        ("REMOTE", "Remote Volunteer", 90),
        ("INTERNATIONAL", "International Volunteer", 100),
    ]
    for code, name, sort_order in categories:
        VolunteerCategory.objects.get_or_create(
            code=code, defaults={"name": name, "sort_order": sort_order}
        )

    types = [
        ("FULL_TIME", "Full-Time Volunteer", 10),
        ("PART_TIME", "Part-Time Volunteer", 20),
        ("PROJECT_BASED", "Project-Based Volunteer", 30),
        ("EVENT", "Event Volunteer", 40),
        ("ONLINE", "Online / Virtual Volunteer", 50),
        ("FIELD", "Field Volunteer", 60),
        ("SPECIALIST", "Specialist Volunteer", 70),
        ("MENTOR", "Mentor", 80),
        ("TRAINER", "Trainer", 90),
        ("ADVISORY", "Advisory Volunteer", 100),
    ]
    for code, name, sort_order in types:
        VolunteerType.objects.get_or_create(
            code=code, defaults={"name": name, "sort_order": sort_order}
        )

    levels = [
        ("NATIONAL", "National Level", 10),
        ("REGIONAL", "Regional Level", 20),
        ("DISTRICT", "District Level", 30),
        ("COMMUNITY", "Community Level", 40),
        ("TEAM", "Team Level", 50),
    ]
    for code, name, sort_order in levels:
        VolunteerLevel.objects.get_or_create(
            code=code, defaults={"name": name, "sort_order": sort_order}
        )


def backfill_taxonomies(apps, schema_editor):
    """Convert stored taxonomy codes into foreign-key references."""
    VolunteerProfile = apps.get_model("volunteers", "VolunteerProfile")
    VolunteerRecruitment = apps.get_model("volunteers", "VolunteerRecruitment")
    VolunteerApplication = apps.get_model("volunteers", "VolunteerApplication")
    VolunteerCategory = apps.get_model("volunteers", "VolunteerCategory")
    VolunteerType = apps.get_model("volunteers", "VolunteerType")
    VolunteerLevel = apps.get_model("volunteers", "VolunteerLevel")

    for profile in VolunteerProfile.objects.all():
        category = (
            VolunteerCategory.objects.filter(code=profile.category).first()
            if profile.category
            else None
        )
        volunteer_type = (
            VolunteerType.objects.filter(code=profile.volunteer_type).first()
            if profile.volunteer_type
            else None
        )
        volunteer_level = (
            VolunteerLevel.objects.filter(code=profile.volunteer_level).first()
            if profile.volunteer_level
            else None
        )
        VolunteerProfile.objects.filter(pk=profile.pk).update(
            category_ref=category,
            volunteer_type_ref=volunteer_type,
            volunteer_level_ref=volunteer_level,
        )

    for recruitment in VolunteerRecruitment.objects.all():
        category = VolunteerCategory.objects.filter(code=recruitment.category).first()
        volunteer_type = VolunteerType.objects.filter(
            code=recruitment.volunteer_type
        ).first()
        VolunteerRecruitment.objects.filter(pk=recruitment.pk).update(
            category_ref=category,
            volunteer_type_ref=volunteer_type,
        )

    for application in VolunteerApplication.objects.all():
        category = VolunteerCategory.objects.filter(code=application.category).first()
        volunteer_type = VolunteerType.objects.filter(
            code=application.volunteer_type
        ).first()
        VolunteerApplication.objects.filter(pk=application.pk).update(
            category_ref=category,
            volunteer_type_ref=volunteer_type,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0003_alter_volunteerapplication_cv_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "eligibility_requirements",
                    models.TextField(
                        blank=True, verbose_name="Eligibility Requirements"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Volunteer Category",
                "verbose_name_plural": "Volunteer Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Volunteer Type",
                "verbose_name_plural": "Volunteer Types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerLevel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "Volunteer Level",
                "verbose_name_plural": "Volunteer Levels",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerActivityLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "activity_title",
                    models.CharField(max_length=200, verbose_name="Activity Title"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEETING", "Meeting"),
                            ("TRAINING", "Training Session"),
                            ("OUTREACH", "Community Outreach"),
                            ("PROGRAM", "Program Implementation"),
                            ("WORKSHOP", "Workshop"),
                            ("CONFERENCE", "Conference"),
                            ("CAMPAIGN", "Campaign Activity"),
                            ("SERVICE_DAY", "Volunteer Service Day"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(db_index=True, verbose_name="Activity Date"),
                ),
                (
                    "program_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Program / Project Name",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Location"
                    ),
                ),
                (
                    "hours_served",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Hours served",
                    ),
                ),
                (
                    "beneficiaries_reached",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Beneficiaries reached"
                    ),
                ),
                (
                    "supervisor_comments",
                    models.TextField(blank=True, verbose_name="Supervisor Comments"),
                ),
                (
                    "supporting_evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                        upload_to="volunteers/activity_evidence/",
                        validators=[
                            apps.volunteers.validators.validate_volunteer_document
                        ],
                        verbose_name="Supporting Evidence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Activity Log",
                "verbose_name_plural": "Volunteer Activity Logs",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerCommunication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-app notification"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PHONE", "Phone call"),
                            ("LETTER", "Letter / Post"),
                            ("NEWSLETTER", "Newsletter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("body", models.TextField(blank=True, verbose_name="Message Body")),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                        upload_to="volunteers/communications/",
                        validators=[
                            apps.volunteers.validators.validate_volunteer_document
                        ],
                        verbose_name="Attachment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Communication",
                "verbose_name_plural": "Volunteer Communications",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerDisciplinaryRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=60,
                        unique=True,
                        verbose_name="Disciplinary reference",
                    ),
                ),
                (
                    "incident_date",
                    models.DateField(db_index=True, verbose_name="Incident Date"),
                ),
                (
                    "nature_of_concern",
                    models.TextField(verbose_name="Nature of Concern / Incident"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Investigation"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPLIED", "Action Applied"),
                            ("APPEALED", "Appealed"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_ACTION", "No Further Action"),
                            ("VERBAL_WARNING", "Verbal Warning"),
                            ("WRITTEN_WARNING", "Written Warning"),
                            ("SUSPENSION", "Suspension"),
                            ("TERMINATION", "Termination"),
                        ],
                        max_length=30,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "investigation_summary",
                    models.TextField(blank=True, verbose_name="Investigation Summary"),
                ),
                (
                    "corrective_action",
                    models.TextField(
                        blank=True, verbose_name="Corrective Action / Outcome"
                    ),
                ),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.volunteers.storage.PrivateVolunteerStorage(),
                        upload_to="volunteers/disciplinary/",
                        validators=[
                            apps.volunteers.validators.validate_volunteer_document
                        ],
                        verbose_name="Supporting Documents",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decided At"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Disciplinary Record",
                "verbose_name_plural": "Volunteer Disciplinary Records",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="volunteerdocument",
            options={
                "ordering": ["-version"],
                "verbose_name": "Volunteer Document",
                "verbose_name_plural": "Volunteer Documents",
            },
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_volunteer_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="retention_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Retention Until"
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="PENDING_APPROVAL",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseding_versions",
                to="volunteers.volunteerdocument",
                verbose_name="Supersedes version",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdocument",
            name="version",
            field=models.PositiveIntegerField(
                db_index=True, default=1, verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="volunteerauditrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Volunteer profile created"),
                    ("APPLICATION_SUBMITTED", "Application submitted"),
                    ("APPLICATION_REVIEWED", "Application reviewed"),
                    ("SCREENING_COMPLETED", "Screening completed"),
                    ("INTERVIEW_COMPLETED", "Interview completed"),
                    ("ONBOARDING_COMPLETED", "Onboarding completed"),
                    ("UPDATED", "Volunteer profile updated"),
                    ("STATUS_CHANGED", "Volunteer status changed"),
                    ("DEPLOYED", "Volunteer deployed"),
                    ("ATTENDANCE_LOGGED", "Attendance logged"),
                    ("TRAINING_COMPLETED", "Training recorded"),
                    ("REVIEWED", "Performance review completed"),
                    ("AWARDED", "Recognition awarded"),
                    ("LEAVE_APPROVED", "Leave approved"),
                    ("LEAVE_REJECTED", "Leave rejected"),
                    ("EXPORTED", "Volunteer data exported"),
                    ("DOCUMENT_DOWNLOADED", "Document downloaded"),
                    ("EXITED", "Volunteer exited"),
                    ("ARCHIVED", "Volunteer profile archived"),
                    ("RESTORED", "Volunteer profile restored"),
                    ("ACTIVITY_LOGGED", "Volunteer activity logged"),
                    ("DISCIPLINARY_OPENED", "Disciplinary record opened"),
                    ("DISCIPLINARY_DECIDED", "Disciplinary record decided"),
                    ("DISCIPLINARY_REOPENED", "Disciplinary record reopened"),
                    ("COMMUNICATION_SENT", "Volunteer communication recorded"),
                    ("DOCUMENT_UPLOADED", "Volunteer document uploaded"),
                    ("DOCUMENT_APPROVED", "Volunteer document approved"),
                    ("DOCUMENT_REJECTED", "Volunteer document rejected"),
                    ("DOCUMENT_ARCHIVED", "Volunteer document archived"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Action",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerdocument",
            index=models.Index(
                fields=["profile", "status"], name="volunteers__profile_c0aaab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerdocument",
            index=models.Index(
                fields=["profile", "version"], name="volunteers__profile_8448e5_idx"
            ),
        ),
        migrations.AddField(
            model_name="volunteeractivitylog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="volunteeractivitylog",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="volunteers.volunteerprofile",
            ),
        ),
        migrations.AddField(
            model_name="volunteeractivitylog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="volunteercategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="volunteercommunication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="volunteercommunication",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communications",
                to="volunteers.volunteerprofile",
            ),
        ),
        migrations.AddField(
            model_name="volunteercommunication",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_volunteer_communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteercommunication",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdisciplinaryrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdisciplinaryrecord",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_volunteer_disciplinary_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerdisciplinaryrecord",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinary_records",
                to="volunteers.volunteerprofile",
            ),
        ),
        migrations.AddField(
            model_name="volunteerdisciplinaryrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="volunteerlevel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="volunteertype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.RunPython(seed_taxonomies, migrations.RunPython.noop),
        migrations.AddField(
            model_name="volunteerprofile",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="volunteers.volunteercategory",
                verbose_name="Volunteer category",
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="volunteer_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="volunteers.volunteertype",
                verbose_name="Volunteer type",
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="volunteer_level_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="volunteers.volunteerlevel",
                verbose_name="Volunteer level",
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerrecruitment",
            name="category_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_campaigns",
                to="volunteers.volunteercategory",
                verbose_name="Volunteer category",
            ),
        ),
        migrations.AddField(
            model_name="volunteerrecruitment",
            name="volunteer_type_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_campaigns",
                to="volunteers.volunteertype",
                verbose_name="Volunteer type",
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="category_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="volunteers.volunteercategory",
                verbose_name="Preferred category",
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="volunteer_type_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="volunteers.volunteertype",
                verbose_name="Preferred type",
            ),
        ),
        migrations.RunPython(backfill_taxonomies, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="volunteerprofile",
            name="volunteers__status_a4ddac_idx",
        ),
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="category",
        ),
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="volunteer_type",
        ),
        migrations.RemoveField(
            model_name="volunteerprofile",
            name="volunteer_level",
        ),
        migrations.RemoveField(
            model_name="volunteerrecruitment",
            name="category",
        ),
        migrations.RemoveField(
            model_name="volunteerrecruitment",
            name="volunteer_type",
        ),
        migrations.RemoveField(
            model_name="volunteerapplication",
            name="category",
        ),
        migrations.RemoveField(
            model_name="volunteerapplication",
            name="volunteer_type",
        ),
        migrations.RenameField(
            model_name="volunteerprofile",
            old_name="category_ref",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="volunteerprofile",
            old_name="volunteer_type_ref",
            new_name="volunteer_type",
        ),
        migrations.RenameField(
            model_name="volunteerprofile",
            old_name="volunteer_level_ref",
            new_name="volunteer_level",
        ),
        migrations.RenameField(
            model_name="volunteerrecruitment",
            old_name="category_ref",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="volunteerrecruitment",
            old_name="volunteer_type_ref",
            new_name="volunteer_type",
        ),
        migrations.RenameField(
            model_name="volunteerapplication",
            old_name="category_ref",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="volunteerapplication",
            old_name="volunteer_type_ref",
            new_name="volunteer_type",
        ),
        migrations.AlterField(
            model_name="volunteerrecruitment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_campaigns",
                to="volunteers.volunteercategory",
                verbose_name="Volunteer category",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerrecruitment",
            name="volunteer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_campaigns",
                to="volunteers.volunteertype",
                verbose_name="Volunteer type",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="volunteers.volunteercategory",
                verbose_name="Preferred category",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="volunteer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="volunteers.volunteertype",
                verbose_name="Preferred type",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerprofile",
            index=models.Index(
                fields=["status", "category"],
                name="volunteers__status_1fe415_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteeractivitylog",
            index=models.Index(
                fields=["profile", "activity_date"],
                name="volunteers__profile_b1b895_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteeractivitylog",
            index=models.Index(
                fields=["activity_date", "category"],
                name="volunteers__activit_d47afd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerdisciplinaryrecord",
            index=models.Index(
                fields=["profile", "status"], name="volunteers__profile_0986d4_idx"
            ),
        ),
    ]
