# Generated by Django 5.1 on 2026-08-28 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("organizations", "0002_seed_organizations_permissions"),
        ("volunteers", "0004_taxonomy_and_activity_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="constituency_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profiles",
                to="locations.constituency",
                verbose_name="Constituency",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profiles",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profiles",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_profiles",
                to="locations.ward",
                verbose_name="Ward / Community",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerprofile",
            index=models.Index(
                fields=["province_location", "district_location"],
                name="volunteers__provinc_3fb321_idx",
            ),
        ),
    ]
