"""Finance Engine DOCX renderer."""

from __future__ import annotations

import io
from typing import Any

# Try to import python-docx for DOCX generation
try:
    from docx import Document
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Inches

    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False

from .base import BaseFinanceRenderer


class FinanceDocxRenderer(BaseFinanceRenderer):
    """Finance report DOCX renderer."""

    def render(self) -> bytes:
        """
        Render the data as DOCX.

        Returns:
            bytes: The rendered DOCX data.
        """
        if DOCX_AVAILABLE:
            return self._render_with_docx()
        else:
            # Fallback to simple text representation
            return self._render_fallback_text()

    def _render_with_docx(self) -> bytes:
        """
        Render DOCX using python-docx.

        Returns:
            bytes: The rendered DOCX data.
        """
        # Create document
        doc = Document()

        # Set margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)

        # Add title
        title = doc.add_heading(self.data.get("title", "Financial Report"), level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add timestamp
        timestamp_para = doc.add_paragraph(
            f"Generated on: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}"
        )
        timestamp_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add a blank line
        doc.add_paragraph()

        # Add data sections
        for section_name, section_data in self.data.items():
            if section_name in ["title"]:  # Skip metadata
                continue

            # Section heading
            doc.add_heading(section_name.replace("_", " ").title(), level=1)

            # Add section data
            if isinstance(section_data, dict):
                # Create a table for key-value pairs
                table = doc.add_table(rows=1, cols=2)
                table.alignment = WD_TABLE_ALIGNMENT.CENTER

                # Set table header
                header_cells = table.rows[0].cells
                header_cells[0].text = "Key"
                header_cells[1].text = "Value"

                # Make header bold
                for cell in header_cells:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.bold = True

                # Add data rows
                for key, value in section_data.items():
                    row_cells = table.add_row().cells
                    row_cells[0].text = str(key)
                    row_cells[1].text = str(value)

            elif isinstance(section_data, list):
                if section_data and isinstance(section_data[0], dict):
                    # List of dictionaries - create a table
                    if section_data:
                        # Add table with headers
                        headers = list(section_data[0].keys())
                        table = doc.add_table(rows=1, cols=len(headers))
                        table.alignment = WD_TABLE_ALIGNMENT.CENTER

                        # Set table header
                        header_cells = table.rows[0].cells
                        for i, header in enumerate(headers):
                            header_cells[i].text = header.replace("_", " ").title()
                            # Make header bold
                            for paragraph in header_cells[i].paragraphs:
                                for run in paragraph.runs:
                                    run.font.bold = True

                        # Add data rows
                        for item in section_data:
                            row_cells = table.add_row().cells
                            for i, key in enumerate(headers):
                                row_cells[i].text = str(item.get(key, ""))
                else:
                    # Simple list
                    for item in section_data:
                        p = doc.add_paragraph(str(item))
                        p.style = "List Bullet"
            else:
                # Simple value
                p = doc.add_paragraph(str(section_data))

        # Add footer
        doc.add_paragraph()
        footer_para = doc.add_paragraph(
            "This report was generated by the SITADC Youth Hub Finance Engine."
        )
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save to bytes
        docx_file = io.BytesIO()
        doc.save(docx_file)
        docx_file.seek(0)

        return docx_file.getvalue()

    def _render_fallback_text(self) -> bytes:
        """
        Render fallback text representation when DOCX library is not available.

        Returns:
            bytes: The rendered text data.
        """
        text_content = f"""
FINANCIAL REPORT
================

Title: {self.data.get('title', 'Financial Report')}
Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}

Data:
{self._format_data_for_text(self.data)}

---
This report was generated by the SITADC Youth Hub Finance Engine.
        """.strip()

        return text_content.encode("utf-8")

    def _format_data_for_text(self, data: Any, indent: int = 0) -> str:
        """
        Format data for text representation.

        Args:
            data: The data to format.
            indent: Indentation level.

        Returns:
            str: The formatted text.
        """
        spaces = " " * indent
        result = []

        if isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, dict | list) and value:
                    result.append(f"{spaces}{key}:")
                    result.append(self._format_data_for_text(value, indent + 2))
                else:
                    result.append(f"{spaces}{key}: {value}")
        elif isinstance(data, list):
            for i, item in enumerate(data):
                if isinstance(item, dict | list) and item:
                    result.append(f"{spaces}[{i}]:")
                    result.append(self._format_data_for_text(item, indent + 2))
                else:
                    result.append(f"{spaces}[{i}]: {item}")
        else:
            result.append(f"{spaces}{data}")

        return "\n".join(result)
