"""Finance Engine PDF renderer."""

from __future__ import annotations

import io
from typing import Any

from django.template.loader import render_to_string

# Try to import weasyprint or reportlab for PDF generation
try:
    from weasyprint import HTML

    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )

        REPORTLAB_AVAILABLE = True
    except ImportError:
        REPORTLAB_AVAILABLE = False

from .base import BaseFinanceRenderer


class FinancePDFRenderer(BaseFinanceRenderer):
    """Finance report PDF renderer."""

    def render(self) -> bytes:
        """
        Render the data as PDF.

        Returns:
            bytes: The rendered PDF data.
        """
        if WEASYPRINT_AVAILABLE:
            return self._render_with_weasyprint()
        elif REPORTLAB_AVAILABLE:
            return self._render_with_reportlab()
        else:
            # Fallback to simple text representation
            return self._render_fallback_text()

    def _render_with_weasyprint(self) -> bytes:
        """
        Render PDF using WeasyPrint.

        Returns:
            bytes: The rendered PDF data.
        """
        # Render HTML template
        html_string = render_to_string(
            "finance/report_pdf.html", self._get_template_context()
        )

        # Convert to PDF
        pdf_file = io.BytesIO()
        HTML(string=html_string).write_pdf(pdf_file)

        return pdf_file.getvalue()

    def _render_with_reportlab(self) -> bytes:
        """
        Render PDF using ReportLab.

        Returns:
            bytes: The rendered PDF data.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            spaceAfter=30,
        )
        story.append(Paragraph(self.data.get("title", "Financial Report"), title_style))
        story.append(Spacer(1, 12))

        # Timestamp
        story.append(
            Paragraph(
                f"Generated on: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 20))

        # Add data sections based on report type
        # This would be customized based on the specific report being rendered
        story.append(Paragraph("Financial Data", styles["Heading2"]))

        # For demonstration, we'll add a simple table
        if "data" in self.data and isinstance(self.data["data"], dict):
            table_data = [["Key", "Value"]]
            for key, value in self.data["data"].items():
                table_data.append([str(key), str(value)])

            table = Table(table_data)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, 0), 14),
                        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                        ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ]
                )
            )
            story.append(table)

        doc.build(story)
        pdf = buffer.getvalue()
        buffer.close()

        return pdf

    def _render_fallback_text(self) -> bytes:
        """
        Render fallback text representation when PDF libraries are not available.

        Returns:
            bytes: The rendered text data.
        """
        text_content = f"""
FINANCIAL REPORT
================

Title: {self.data.get('title', 'Financial Report')}
Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}

Data:
{self._format_data_for_text(self.data)}

---
This report was generated by the SITADC Youth Hub Finance Engine.
        """.strip()

        return text_content.encode("utf-8")

    def _format_data_for_text(self, data: Any, indent: int = 0) -> str:
        """
        Format data for text representation.

        Args:
            data: The data to format.
            indent: Indentation level.

        Returns:
            str: The formatted text.
        """
        spaces = " " * indent
        result = []

        if isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, dict | list) and value:
                    result.append(f"{spaces}{key}:")
                    result.append(self._format_data_for_text(value, indent + 2))
                else:
                    result.append(f"{spaces}{key}: {value}")
        elif isinstance(data, list):
            for i, item in enumerate(data):
                if isinstance(item, dict | list) and item:
                    result.append(f"{spaces}[{i}]:")
                    result.append(self._format_data_for_text(item, indent + 2))
                else:
                    result.append(f"{spaces}[{i}]: {item}")
        else:
            result.append(f"{spaces}{data}")

        return "\n".join(result)
