"""Permission constants and helpers for the ``beneficiaries`` namespace."""

from __future__ import annotations

from apps.rbac.authorization import user_has_permission

from .constants import BENEFICIARY_ACTION_PERMISSIONS

BENEFICIARIES_VIEW = BENEFICIARY_ACTION_PERMISSIONS["view"]
BENEFICIARIES_CREATE = BENEFICIARY_ACTION_PERMISSIONS["create"]
BENEFICIARIES_UPDATE = BENEFICIARY_ACTION_PERMISSIONS["update"]
BENEFICIARIES_DELETE = BENEFICIARY_ACTION_PERMISSIONS["delete"]
BENEFICIARIES_ARCHIVE = BENEFICIARY_ACTION_PERMISSIONS["archive"]
BENEFICIARIES_RESTORE = BENEFICIARY_ACTION_PERMISSIONS["restore"]
BENEFICIARIES_EXPORT = BENEFICIARY_ACTION_PERMISSIONS["export"]
BENEFICIARIES_MANAGE = BENEFICIARY_ACTION_PERMISSIONS["manage"]
BENEFICIARIES_VIEW_CONFIDENTIAL = BENEFICIARY_ACTION_PERMISSIONS["view_confidential"]
BENEFICIARIES_SUBMIT = BENEFICIARY_ACTION_PERMISSIONS["submit"]
BENEFICIARIES_APPROVE = BENEFICIARY_ACTION_PERMISSIONS["approve"]
BENEFICIARIES_MANAGE_HOUSEHOLDS = BENEFICIARY_ACTION_PERMISSIONS["manage_households"]
BENEFICIARIES_MANAGE_GROUPS = BENEFICIARY_ACTION_PERMISSIONS["manage_groups"]
BENEFICIARIES_MANAGE_ENROLLMENTS = BENEFICIARY_ACTION_PERMISSIONS["manage_enrollments"]
BENEFICIARIES_MANAGE_PARTICIPATION = BENEFICIARY_ACTION_PERMISSIONS[
    "manage_participation"
]
BENEFICIARIES_MANAGE_ATTENDANCE = BENEFICIARY_ACTION_PERMISSIONS["manage_attendance"]
BENEFICIARIES_MANAGE_SERVICES = BENEFICIARY_ACTION_PERMISSIONS["manage_services"]
BENEFICIARIES_MANAGE_REFERRALS = BENEFICIARY_ACTION_PERMISSIONS["manage_referrals"]
BENEFICIARIES_MANAGE_CASE_NOTES = BENEFICIARY_ACTION_PERMISSIONS["manage_case_notes"]
BENEFICIARIES_MANAGE_FOLLOW_UPS = BENEFICIARY_ACTION_PERMISSIONS["manage_follow_ups"]
BENEFICIARIES_MANAGE_ASSESSMENTS = BENEFICIARY_ACTION_PERMISSIONS["manage_assessments"]
BENEFICIARIES_MANAGE_SUPPORT_PLANS = BENEFICIARY_ACTION_PERMISSIONS[
    "manage_support_plans"
]
BENEFICIARIES_MANAGE_CONSENT = BENEFICIARY_ACTION_PERMISSIONS["manage_consent"]
BENEFICIARIES_MANAGE_GUARDIANS = BENEFICIARY_ACTION_PERMISSIONS["manage_guardians"]
BENEFICIARIES_MANAGE_SAFEGUARDING = BENEFICIARY_ACTION_PERMISSIONS[
    "manage_safeguarding"
]
BENEFICIARIES_MANAGE_OUTCOMES = BENEFICIARY_ACTION_PERMISSIONS["manage_outcomes"]
BENEFICIARIES_MANAGE_EXITS = BENEFICIARY_ACTION_PERMISSIONS["manage_exits"]
BENEFICIARIES_MANAGE_DOCUMENTS = BENEFICIARY_ACTION_PERMISSIONS["manage_documents"]
BENEFICIARIES_MANAGE_FEEDBACK = BENEFICIARY_ACTION_PERMISSIONS["manage_feedback"]
BENEFICIARIES_MANAGE_TRANSFERS = BENEFICIARY_ACTION_PERMISSIONS["manage_transfers"]
BENEFICIARIES_MANAGE_DUPLICATES = BENEFICIARY_ACTION_PERMISSIONS["manage_duplicates"]
BENEFICIARIES_ANALYTICS = BENEFICIARY_ACTION_PERMISSIONS["analytics"]


def user_can_manage_beneficiaries(user) -> bool:
    return user_has_permission(user, BENEFICIARIES_MANAGE)


def user_can_view_confidential_beneficiary_data(user) -> bool:
    return bool(
        getattr(user, "is_superuser", False)
        or user_has_permission(user, BENEFICIARIES_MANAGE)
        or user_has_permission(user, BENEFICIARIES_VIEW_CONFIDENTIAL)
    )
