# Generated by Django 5.1 on 2026-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_seed_reference_numbers_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("ACTIVATED", "Activated"),
                    ("DEACTIVATED", "Deactivated"),
                    ("ARCHIVED", "Archived"),
                    ("RESTORED", "Restored"),
                    ("CLONED", "Cloned"),
                    ("DELETED", "Deleted"),
                    ("PERMISSIONS_CHANGED", "Permissions Changed"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_REVOKED", "Role Revoked"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Action",
            ),
        ),
    ]
