from .development import *  # noqa: F401,F403

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core.apps.CoreConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.rbac.apps.RbacConfig",
    "apps.organizations.apps.OrganizationsConfig",
    "apps.references.apps.ReferencesConfig",
    "apps.leadership.apps.LeadershipConfig",
    "apps.volunteers.apps.VolunteersConfig",
    "apps.memberships.apps.MembershipsConfig",
    "apps.stakeholders.apps.StakeholdersConfig",
    "apps.programs.apps.ProgramsConfig",
    "apps.beneficiaries.apps.BeneficiariesConfig",
    "apps.meal.apps.MealConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.report_instances.apps.ReportInstancesConfig",
    "apps.reviews.apps.ReviewsConfig",
    "apps.documents.apps.DocumentsConfig",
    "apps.registers.apps.RegistersConfig",
    "apps.meetings.apps.MeetingsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.search.apps.SearchConfig",
    "apps.exports.apps.ExportsConfig",
]
