"""URL routes for the Monitoring, Evaluation, Accountability & Learning module."""

from django.urls import path

from . import views

app_name = "meal"

urlpatterns = [
    path("", views.MealDashboardView.as_view(), name="dashboard"),
    path("dashboard/", views.MealDashboardView.as_view(), name="dashboard_alt"),
    # Exports
    path(
        "indicators/register.csv",
        views.IndicatorRegisterExportView.as_view(),
        name="indicator_register_export",
    ),
    path(
        "monitoring/visits/register.csv",
        views.MonitoringVisitRegisterExportView.as_view(),
        name="monitoring_visit_register_export",
    ),
    path(
        "accountability/complaints/register.csv",
        views.ComplaintRegisterExportView.as_view(),
        name="complaint_register_export",
    ),
    path(
        "accountability/feedback/register.csv",
        views.FeedbackRegisterExportView.as_view(),
        name="feedback_register_export",
    ),
    path(
        "evaluations/register.csv",
        views.EvaluationRegisterExportView.as_view(),
        name="evaluation_register_export",
    ),
    path(
        "learning/lessons/register.csv",
        views.LessonRegisterExportView.as_view(),
        name="lesson_register_export",
    ),
    path(
        "reports/register.csv",
        views.MEALReportRegisterExportView.as_view(),
        name="meal_report_register_export",
    ),
    path(
        "reports/<uuid:pk>/export/<str:fmt>/",
        views.MEALReportExportView.as_view(),
        name="meal_report_export",
    ),
    # Indicators
    path(
        "indicators/", views.IndicatorRegistryView.as_view(), name="indicator_registry"
    ),
    path(
        "indicators/new/", views.IndicatorCreateView.as_view(), name="indicator_create"
    ),
    path(
        "indicators/<uuid:pk>/",
        views.IndicatorDetailView.as_view(),
        name="indicator_detail",
    ),
    path(
        "indicators/<uuid:pk>/edit/",
        views.IndicatorUpdateView.as_view(),
        name="indicator_edit",
    ),
    path(
        "indicators/<uuid:pk>/activate/",
        views.IndicatorActivateView.as_view(),
        name="indicator_activate",
    ),
    # Frameworks - Theory of Change
    path(
        "frameworks/theories-of-change/new/",
        views.TheoryOfChangeCreateView.as_view(),
        name="theory_of_change_create",
    ),
    path(
        "frameworks/theories-of-change/<uuid:pk>/",
        views.TheoryOfChangeDetailView.as_view(),
        name="theory_of_change_detail",
    ),
    path(
        "frameworks/theories-of-change/<uuid:pk>/edit/",
        views.TheoryOfChangeUpdateView.as_view(),
        name="theory_of_change_edit",
    ),
    path(
        "frameworks/theories-of-change/<uuid:pk>/actions/",
        views.TheoryOfChangeTransitionView.as_view(),
        name="theory_of_change_actions",
    ),
    # Frameworks - Results Framework
    path(
        "frameworks/results-frameworks/new/",
        views.ResultsFrameworkCreateView.as_view(),
        name="results_framework_create",
    ),
    path(
        "frameworks/results-frameworks/<uuid:pk>/",
        views.ResultsFrameworkDetailView.as_view(),
        name="results_framework_detail",
    ),
    path(
        "frameworks/results-frameworks/<uuid:pk>/edit/",
        views.ResultsFrameworkUpdateView.as_view(),
        name="results_framework_edit",
    ),
    path(
        "frameworks/results-frameworks/<uuid:pk>/actions/",
        views.ResultsFrameworkTransitionView.as_view(),
        name="results_framework_actions",
    ),
    # Frameworks - Logframe
    path(
        "frameworks/logframes/new/",
        views.LogicalFrameworkCreateView.as_view(),
        name="logical_framework_create",
    ),
    path(
        "frameworks/logframes/<uuid:pk>/",
        views.LogicalFrameworkDetailView.as_view(),
        name="logical_framework_detail",
    ),
    path(
        "frameworks/logframes/<uuid:pk>/edit/",
        views.LogicalFrameworkUpdateView.as_view(),
        name="logical_framework_edit",
    ),
    path(
        "frameworks/logframes/<uuid:pk>/actions/",
        views.LogicalFrameworkTransitionView.as_view(),
        name="logical_framework_actions",
    ),
    # Data collection
    path(
        "data-collection/new/",
        views.DataCollectionPlanCreateView.as_view(),
        name="data_collection_create",
    ),
    path(
        "data-collection/<uuid:pk>/",
        views.DataCollectionPlanDetailView.as_view(),
        name="data_collection_detail",
    ),
    path(
        "data-collection/<uuid:pk>/edit/",
        views.DataCollectionPlanUpdateView.as_view(),
        name="data_collection_edit",
    ),
    path(
        "data-collection/<uuid:pk>/actions/",
        views.DataCollectionPlanTransitionView.as_view(),
        name="data_collection_actions",
    ),
    path(
        "data-collection/<uuid:plan_pk>/submissions/new/",
        views.DataSubmissionCreateView.as_view(),
        name="data_submission_create",
    ),
    # Monitoring
    path(
        "monitoring/visits/",
        views.MonitoringVisitDirectoryView.as_view(),
        name="monitoring_visit_directory",
    ),
    path(
        "monitoring/visits/new/",
        views.MonitoringVisitCreateView.as_view(),
        name="monitoring_visit_create",
    ),
    path(
        "monitoring/visits/<uuid:pk>/",
        views.MonitoringVisitDetailView.as_view(),
        name="monitoring_visit_detail",
    ),
    path(
        "monitoring/visits/<uuid:pk>/edit/",
        views.MonitoringVisitUpdateView.as_view(),
        name="monitoring_visit_edit",
    ),
    path(
        "monitoring/visits/<uuid:pk>/actions/",
        views.MonitoringVisitTransitionView.as_view(),
        name="monitoring_visit_actions",
    ),
    path(
        "monitoring/visits/<uuid:visit_pk>/findings/new/",
        views.MonitoringFindingCreateView.as_view(),
        name="monitoring_finding_create",
    ),
    path(
        "monitoring/plans/new/",
        views.MonitoringPlanCreateView.as_view(),
        name="monitoring_plan_create",
    ),
    path(
        "monitoring/plans/<uuid:pk>/",
        views.MonitoringPlanDetailView.as_view(),
        name="monitoring_plan_detail",
    ),
    path(
        "monitoring/plans/<uuid:pk>/edit/",
        views.MonitoringPlanUpdateView.as_view(),
        name="monitoring_plan_edit",
    ),
    # Evaluations
    path(
        "evaluations/",
        views.EvaluationDirectoryView.as_view(),
        name="evaluation_directory",
    ),
    path(
        "evaluations/new/",
        views.EvaluationCreateView.as_view(),
        name="evaluation_create",
    ),
    path(
        "evaluations/<uuid:pk>/",
        views.EvaluationDetailView.as_view(),
        name="evaluation_detail",
    ),
    path(
        "evaluations/<uuid:pk>/edit/",
        views.EvaluationUpdateView.as_view(),
        name="evaluation_edit",
    ),
    path(
        "evaluations/<uuid:pk>/actions/",
        views.EvaluationTransitionView.as_view(),
        name="evaluation_actions",
    ),
    # DQA
    path("dqa/new/", views.DQACreateView.as_view(), name="dqa_create"),
    path("dqa/<uuid:pk>/", views.DQADetailView.as_view(), name="dqa_detail"),
    path(
        "dqa/<uuid:pk>/actions/", views.DQATransitionView.as_view(), name="dqa_actions"
    ),
    # Accountability - Complaints
    path(
        "accountability/complaints/",
        views.ComplaintDirectoryView.as_view(),
        name="complaint_directory",
    ),
    path(
        "accountability/complaints/new/",
        views.ComplaintCreateView.as_view(),
        name="complaint_create",
    ),
    path(
        "accountability/complaints/<uuid:pk>/",
        views.ComplaintDetailView.as_view(),
        name="complaint_detail",
    ),
    path(
        "accountability/complaints/<uuid:pk>/resolve/",
        views.ComplaintResolveView.as_view(),
        name="complaint_resolve",
    ),
    path(
        "accountability/complaints/<uuid:pk>/close/",
        views.ComplaintCloseView.as_view(),
        name="complaint_close",
    ),
    # Accountability - Feedback
    path(
        "accountability/feedback/",
        views.FeedbackDirectoryView.as_view(),
        name="feedback_directory",
    ),
    path(
        "accountability/feedback/new/",
        views.FeedbackCreateView.as_view(),
        name="feedback_create",
    ),
    path(
        "accountability/feedback/<uuid:pk>/",
        views.FeedbackDetailView.as_view(),
        name="feedback_detail",
    ),
    path(
        "accountability/feedback/<uuid:pk>/respond/",
        views.FeedbackRespondView.as_view(),
        name="feedback_respond",
    ),
    path(
        "accountability/feedback/<uuid:pk>/close/",
        views.FeedbackCloseView.as_view(),
        name="feedback_close",
    ),
    # Accountability - Corrective actions
    path(
        "accountability/corrective-actions/new/",
        views.CorrectiveActionCreateView.as_view(),
        name="corrective_action_create",
    ),
    path(
        "accountability/corrective-actions/<uuid:pk>/",
        views.CorrectiveActionDetailView.as_view(),
        name="corrective_action_detail",
    ),
    path(
        "accountability/corrective-actions/<uuid:pk>/complete/",
        views.CorrectiveActionResolveView.as_view(),
        name="corrective_action_complete",
    ),
    path(
        "accountability/corrective-actions/<uuid:pk>/verify/",
        views.CorrectiveActionVerifyView.as_view(),
        name="corrective_action_verify",
    ),
    # Learning
    path(
        "learning/outcome-harvests/new/",
        views.OutcomeHarvestCreateView.as_view(),
        name="outcome_harvest_create",
    ),
    path(
        "learning/outcome-harvests/<uuid:pk>/",
        views.OutcomeHarvestDetailView.as_view(),
        name="outcome_harvest_detail",
    ),
    path(
        "learning/logs/new/",
        views.LearningLogCreateView.as_view(),
        name="learning_log_create",
    ),
    path(
        "learning/logs/<uuid:pk>/",
        views.LearningLogDetailView.as_view(),
        name="learning_log_detail",
    ),
    path(
        "learning/best-practices/new/",
        views.BestPracticeCreateView.as_view(),
        name="best_practice_create",
    ),
    path(
        "learning/best-practices/<uuid:pk>/",
        views.BestPracticeDetailView.as_view(),
        name="best_practice_detail",
    ),
    path(
        "learning/best-practices/<uuid:pk>/actions/",
        views.BestPracticeTransitionView.as_view(),
        name="best_practice_actions",
    ),
    path(
        "learning/lessons/new/",
        views.LessonLearnedCreateView.as_view(),
        name="lesson_create",
    ),
    path(
        "learning/lessons/<uuid:pk>/",
        views.LessonLearnedDetailView.as_view(),
        name="lesson_detail",
    ),
    # Scorecards & KPIs
    path(
        "scorecards/new/",
        views.PerformanceScorecardCreateView.as_view(),
        name="scorecard_create",
    ),
    path(
        "scorecards/<uuid:pk>/",
        views.PerformanceScorecardDetailView.as_view(),
        name="scorecard_detail",
    ),
    path(
        "scorecards/<uuid:pk>/actions/",
        views.ScorecardTransitionView.as_view(),
        name="scorecard_actions",
    ),
    path(
        "scorecards/kpis/new/",
        views.OrganizationalKPICreateView.as_view(),
        name="organizational_kpi_create",
    ),
    path(
        "scorecards/kpis/<uuid:pk>/",
        views.OrganizationalKPIDetailView.as_view(),
        name="organizational_kpi_detail",
    ),
    # Reports
    path(
        "reports/",
        views.MEALReportDirectoryView.as_view(),
        name="meal_report_directory",
    ),
    path(
        "reports/new/", views.MEALReportCreateView.as_view(), name="meal_report_create"
    ),
    path(
        "reports/<uuid:pk>/",
        views.MEALReportDetailView.as_view(),
        name="meal_report_detail",
    ),
    path(
        "reports/<uuid:pk>/edit/",
        views.MEALReportUpdateView.as_view(),
        name="meal_report_edit",
    ),
    path(
        "reports/<uuid:pk>/actions/",
        views.MEALReportTransitionView.as_view(),
        name="meal_report_actions",
    ),
]
