# Generated by Django 5.0.7 on 2026-08-05 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("code", models.SlugField(max_length=100, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Group",
                "verbose_name_plural": "Field Groups",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "code",
                    models.SlugField(max_length=120, verbose_name="Internal name"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Single-line text"),
                            ("MULTILINE_TEXT", "Multi-line text"),
                            ("RICH_TEXT", "Rich text"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("CURRENCY", "Currency"),
                            ("PERCENTAGE", "Percentage"),
                            ("DATE", "Date"),
                            ("TIME", "Time"),
                            ("DATETIME", "Date & time"),
                            ("DROPDOWN", "Dropdown"),
                            ("MULTI_SELECT", "Multi-select"),
                            ("RADIO", "Radio buttons"),
                            ("CHECKBOX", "Checkboxes"),
                            ("TOGGLE", "Toggle switch"),
                            ("IMAGE", "Image upload"),
                            ("VIDEO", "Video upload"),
                            ("AUDIO", "Audio upload"),
                            ("DOCUMENT", "Document upload"),
                            ("SIGNATURE", "Signature"),
                            ("QR_CODE", "QR code"),
                            ("BARCODE", "Barcode"),
                            ("GPS_COORDINATES", "GPS coordinates"),
                            ("USER_SELECTOR", "User selector"),
                            ("ORGANIZATION_SELECTOR", "Organization selector"),
                            ("BENEFICIARY_SELECTOR", "Beneficiary selector"),
                            ("PROGRAM_SELECTOR", "Program selector"),
                            ("PROJECT_SELECTOR", "Project selector"),
                            ("FORMULA", "Formula (calculated)"),
                            ("AUTO_REFERENCE", "Auto-generated reference number"),
                            ("TABLE_GRID", "Table / grid"),
                            ("REPEATING_GROUP", "Repeating group"),
                        ],
                        db_index=True,
                        default="TEXT",
                        max_length=30,
                        verbose_name="Field type",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("BOOLEAN", "Boolean"),
                            ("DATE", "Date"),
                            ("DATETIME", "Datetime"),
                            ("JSON", "Structured data"),
                        ],
                        default="STRING",
                        max_length=20,
                        verbose_name="Data type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Required"),
                ),
                (
                    "read_only",
                    models.BooleanField(default=False, verbose_name="Read only"),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
                (
                    "is_repeatable",
                    models.BooleanField(default=False, verbose_name="Repeatable"),
                ),
                (
                    "is_calculated",
                    models.BooleanField(default=False, verbose_name="Calculated"),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Formula"
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Default value"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Placeholder"
                    ),
                ),
                ("help_text", models.TextField(blank=True, verbose_name="Help text")),
                (
                    "tooltip",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tooltip"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="reports.fieldgroup",
                        verbose_name="Field group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Field",
                "verbose_name_plural": "Dynamic Fields",
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=120, verbose_name="Value")),
                ("label", models.CharField(max_length=200, verbose_name="Label")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="reports.dynamicfield",
                        verbose_name="Field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Option",
                "verbose_name_plural": "Field Options",
                "ordering": ("sort_order", "value"),
            },
        ),
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Color"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=60, verbose_name="Icon"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Category",
                "verbose_name_plural": "Report Categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=80,
                        unique=True,
                        verbose_name="Template ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Template code"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Department / directorate",
                    ),
                ),
                (
                    "reporting_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMI_ANNUAL", "Semi-annual"),
                            ("ANNUAL", "Annual"),
                            ("ONE_OFF", "One-off"),
                            ("ON_DEMAND", "On demand"),
                        ],
                        default="ONE_OFF",
                        max_length=20,
                        verbose_name="Reporting frequency",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective from"
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(blank=True, null=True, verbose_name="Expiry date"),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Retention period (days)"
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                        verbose_name="Confidentiality",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="reports.reportcategory",
                        verbose_name="Report category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_report_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Template created"),
                            ("UPDATED", "Template updated"),
                            ("DELETED", "Template deleted"),
                            ("RESTORED", "Template restored"),
                            ("PUBLISHED", "Template published"),
                            ("UNPUBLISHED", "Template unpublished"),
                            ("ARCHIVED", "Template archived"),
                            ("CLONED", "Template cloned"),
                            ("IMPORTED", "Template imported"),
                            ("EXPORTED", "Template exported"),
                            ("VERSION_CREATED", "Version created"),
                            ("VERSION_RESTORED", "Version restored"),
                            ("SCHEMA_UPDATED", "Schema updated"),
                            ("VALIDATION_FAILED", "Schema validation failed"),
                            ("PREVIEWED", "Template previewed"),
                            ("CATEGORY_CREATED", "Category created"),
                            ("CATEGORY_UPDATED", "Category updated"),
                            ("CATEGORY_ACTIVATED", "Category activated"),
                            ("CATEGORY_DEACTIVATED", "Category deactivated"),
                            ("SETTINGS_UPDATED", "Report builder settings updated"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_template_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Builder Audit Record",
                "verbose_name_plural": "Report Builder Audit Records",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        default="default",
                        max_length=40,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "template_numbering_scheme_code",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="Template numbering scheme",
                    ),
                ),
                (
                    "default_reporting_frequency",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Default reporting frequency",
                    ),
                ),
                (
                    "branding",
                    models.JSONField(blank=True, default=dict, verbose_name="Branding"),
                ),
                (
                    "default_page_layout",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Default page layout"
                    ),
                ),
                (
                    "default_export_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Default export settings"
                    ),
                ),
                (
                    "auto_save_interval_seconds",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Auto-save interval (seconds)"
                    ),
                ),
                (
                    "archive_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Archive rules"
                    ),
                ),
                (
                    "notification_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Notification rules"
                    ),
                ),
                (
                    "retention_default_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Default retention period (days)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Builder Settings",
                "verbose_name_plural": "Report Builder Settings",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateStatusHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="From status"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(max_length=40, verbose_name="To status"),
                ),
                ("action", models.CharField(max_length=40, verbose_name="Action")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Status History",
                "verbose_name_plural": "Template Status History",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=40, verbose_name="Version number"),
                ),
                (
                    "major",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Major version"
                    ),
                ),
                (
                    "minor",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Minor version"
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(blank=True, verbose_name="Change summary"),
                ),
                (
                    "schema_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Schema snapshot"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Checksum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is current"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_template_versions_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Version",
                "verbose_name_plural": "Template Versions",
                "ordering": ("-major", "-minor"),
            },
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reports.reporttemplateversion",
                verbose_name="Current version",
            ),
        ),
        migrations.CreateModel(
            name="TableColumnDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "column_name",
                    models.CharField(max_length=200, verbose_name="Column name"),
                ),
                (
                    "column_code",
                    models.CharField(max_length=120, verbose_name="Column code"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("BOOLEAN", "Boolean"),
                            ("DATE", "Date"),
                            ("DATETIME", "Datetime"),
                            ("JSON", "Structured data"),
                        ],
                        default="STRING",
                        max_length=20,
                        verbose_name="Data type",
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Width"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Required"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "table_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_columns",
                        to="reports.dynamicfield",
                        verbose_name="Table field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Column Definition",
                "verbose_name_plural": "Table Column Definitions",
                "ordering": ("sort_order",),
            },
        ),
        migrations.CreateModel(
            name="TemplateComponent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("HEADER", "Header"),
                            ("COVER_PAGE", "Cover page"),
                            ("METADATA_BLOCK", "Metadata block"),
                            ("INSTRUCTIONS", "Instructions"),
                            ("SECTION", "Section"),
                            ("SUBSECTION", "Subsection"),
                            ("TABLE", "Table"),
                            ("CHART", "Chart"),
                            ("ATTACHMENTS", "Attachments"),
                            ("SIGNATURE_BLOCK", "Signature block"),
                            ("APPROVAL_BLOCK", "Approval block"),
                            ("FOOTER", "Footer"),
                        ],
                        default="HEADER",
                        max_length=20,
                        verbose_name="Component type",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(blank=True, max_length=100, verbose_name="Code"),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="Shared component"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Component",
                "verbose_name_plural": "Template Components",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="TemplateReferenceRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("organizations", "Organizations"),
                            ("leadership", "Leadership"),
                            ("memberships", "Memberships"),
                            ("volunteers", "Volunteers"),
                            ("stakeholders", "Stakeholders"),
                            ("programs", "Programs"),
                            ("projects", "Projects"),
                            ("beneficiaries", "Beneficiaries"),
                            ("meal", "MEAL"),
                            ("finance", "Finance"),
                        ],
                        max_length=30,
                        verbose_name="Source module",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=120, verbose_name="Model name"),
                ),
                (
                    "display_field",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Display field"
                    ),
                ),
                (
                    "value_field",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Value field"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filters"),
                ),
                (
                    "is_multiple",
                    models.BooleanField(
                        default=False, verbose_name="Multiple selection"
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Allowed roles"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_rule",
                        to="reports.dynamicfield",
                        verbose_name="Field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Reference Rule",
                "verbose_name_plural": "Template Reference Rules",
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("code", models.SlugField(max_length=100, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_repeatable",
                    models.BooleanField(default=False, verbose_name="Repeatable"),
                ),
                (
                    "is_collapsible",
                    models.BooleanField(default=True, verbose_name="Collapsible"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Locked"),
                ),
                (
                    "visibility_mode",
                    models.CharField(
                        choices=[
                            ("ALWAYS", "Always visible"),
                            ("CONDITIONAL", "Conditional visibility"),
                            ("ROLE_BASED", "Role-based visibility"),
                            ("REPORTING_PERIOD", "Reporting-period logic"),
                        ],
                        default="ALWAYS",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Visibility condition"
                    ),
                ),
                (
                    "required_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Required roles"
                    ),
                ),
                (
                    "required_departments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Required departments"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="reports.templatesection",
                        verbose_name="Parent section",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Section",
                "verbose_name_plural": "Template Sections",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="fieldgroup",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="reports.templatesection",
                verbose_name="Section",
            ),
        ),
        migrations.CreateModel(
            name="ConditionalLogicRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("FIELD", "Field"), ("SECTION", "Section")],
                        default="FIELD",
                        max_length=20,
                        verbose_name="Target type",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("SHOW_FIELD", "Show field"),
                            ("HIDE_FIELD", "Hide field"),
                            ("ENABLE_FIELD", "Enable field"),
                            ("DISABLE_FIELD", "Disable field"),
                            ("REQUIRE_FIELD", "Require field"),
                            ("SHOW_SECTION", "Show section"),
                            ("HIDE_SECTION", "Hide section"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Condition type",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("NOT_EQUALS", "Does not equal"),
                            ("CONTAINS", "Contains"),
                            ("NOT_CONTAINS", "Does not contain"),
                            ("GREATER_THAN", "Greater than"),
                            ("GREATER_THAN_OR_EQUAL", "Greater than or equal"),
                            ("LESS_THAN", "Less than"),
                            ("LESS_THAN_OR_EQUAL", "Less than or equal"),
                            ("IS_EMPTY", "Is empty"),
                            ("IS_NOT_EMPTY", "Is not empty"),
                            ("IN", "Is one of"),
                            ("NOT_IN", "Is none of"),
                            ("STARTS_WITH", "Starts with"),
                            ("ENDS_WITH", "Ends with"),
                        ],
                        default="EQUALS",
                        max_length=30,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "value",
                    models.JSONField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "logic",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Advanced logic"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="Priority"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drives_conditional_rules",
                        to="reports.dynamicfield",
                        verbose_name="Source field",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_rules",
                        to="reports.dynamicfield",
                        verbose_name="Target field",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_rules",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "target_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditional_rules",
                        to="reports.templatesection",
                        verbose_name="Target section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conditional Logic Rule",
                "verbose_name_plural": "Conditional Logic Rules",
                "ordering": ("priority", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required field"),
                            ("MIN_LENGTH", "Minimum length"),
                            ("MAX_LENGTH", "Maximum length"),
                            ("MIN_VALUE", "Numeric minimum"),
                            ("MAX_VALUE", "Numeric maximum"),
                            ("DATE_MIN", "Earliest date"),
                            ("DATE_MAX", "Latest date"),
                            ("REGEX", "Pattern match"),
                            ("EMAIL", "Email address"),
                            ("URL", "URL"),
                            ("FILE_TYPE", "Allowed file types"),
                            ("FILE_SIZE_MAX", "Maximum file size"),
                            ("DUPLICATE_PREVENTION", "Duplicate prevention"),
                            ("CROSS_FIELD", "Cross-field comparison"),
                            ("BUSINESS_RULE", "Business rule"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Rule type",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Operator"
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parameters"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Message"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="reports.dynamicfield",
                        verbose_name="Field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Rule",
                "verbose_name_plural": "Validation Rules",
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddIndex(
            model_name="dynamicfield",
            index=models.Index(
                fields=["field_type"], name="reports_dyn_field_t_8ca297_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dynamicfield",
            constraint=models.UniqueConstraint(
                fields=("group", "code"), name="report_dynamic_field_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldoption",
            constraint=models.UniqueConstraint(
                fields=("field", "value"), name="report_field_option_value_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcategory",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="reports_rep_is_acti_3643ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplateauditrecord",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="reports_rep_entity__c66c95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplatestatushistory",
            index=models.Index(
                fields=["template", "created_at"], name="reports_rep_templat_c67848_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"),
                name="report_template_version_number_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("template",),
                name="report_template_single_current_version",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(fields=["status"], name="reports_rep_status_748a26_idx"),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["category", "status"], name="reports_rep_categor_b38be1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tablecolumndefinition",
            constraint=models.UniqueConstraint(
                fields=("table_field", "column_code"),
                name="report_table_column_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatesection",
            constraint=models.UniqueConstraint(
                fields=("template", "code"), name="report_template_section_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldgroup",
            constraint=models.UniqueConstraint(
                fields=("section", "code"), name="report_field_group_code_uniq"
            ),
        ),
    ]
