# Generated by Django 5.0.7 on 2026-08-06 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='Workflow name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definition', to='reports.reporttemplate', verbose_name='Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=100, verbose_name='Stage name')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Stage code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Initial stage')),
                ('is_final', models.BooleanField(default=False, verbose_name='Final stage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'verbose_name_plural': 'Workflow Stages',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requires_signature', models.BooleanField(default=False, verbose_name='Requires digital signature')),
                ('min_approvals_required', models.PositiveSmallIntegerField(default=1, verbose_name='Min approvals required')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_approval_rules', to=settings.AUTH_USER_MODEL, verbose_name='Required role/user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='reports.workflowstage', verbose_name='Workflow stage')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'ordering': ('stage', 'created_at'),
            },
        ),
    ]
