# Generated by Django 5.0.7 on 2026-08-06 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_workflowdefinition_workflowstage_approvalrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(default='default', max_length=40, unique=True, verbose_name='Key')),
                ('numbering_scheme_code', models.CharField(blank=True, max_length=60, verbose_name='Numbering scheme code')),
                ('numbering_prefix', models.CharField(default='RPT', max_length=30, verbose_name='Reference number prefix')),
                ('auto_save_interval_seconds', models.PositiveIntegerField(default=60, verbose_name='Auto-save interval (seconds)')),
                ('draft_retention_days', models.PositiveIntegerField(default=90, verbose_name='Draft retention (days)')),
                ('archive_after_days', models.PositiveIntegerField(default=30, verbose_name='Archive approved reports after (days)')),
                ('default_confidentiality', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=20, verbose_name='Default confidentiality')),
                ('allow_withdrawal', models.BooleanField(default=True, verbose_name='Allow report withdrawal')),
                ('allow_resubmission', models.BooleanField(default=True, verbose_name='Allow resubmission')),
                ('require_evidence_on_submit', models.BooleanField(default=False, verbose_name='Require evidence on submit')),
                ('reminder_days_before_due', models.PositiveIntegerField(default=7, verbose_name='Reminder days before due')),
                ('escalation_days_after_due', models.PositiveIntegerField(default=3, verbose_name='Escalation days after due')),
                ('max_file_size_mb', models.PositiveIntegerField(default=20, verbose_name='Max attachment file size (MB)')),
                ('allowed_file_types', models.JSONField(blank=True, default=list, verbose_name='Allowed file types')),
                ('notification_rules', models.JSONField(blank=True, default=dict, verbose_name='Notification rules')),
                ('export_defaults', models.JSONField(blank=True, default=dict, verbose_name='Export defaults')),
                ('branding', models.JSONField(blank=True, default=dict, verbose_name='Branding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Report Management Configuration',
                'verbose_name_plural': 'Report Management Configurations',
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Period name')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Code')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-annual'), ('ANNUAL', 'Annual'), ('ONE_OFF', 'One-off'), ('ON_DEMAND', 'On demand')], default='QUARTERLY', max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_2f0817_idx')],
            },
        ),
    ]
