# Generated by Django 5.0.7 on 2026-08-06 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report_instances", "0001_initial"),
        ("reports", "0003_reportconfiguration_reportingperiod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Review number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_ASSIGNMENT", "Pending Assignment"),
                            ("ASSIGNED", "Assigned"),
                            ("ACCEPTED", "Accepted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("AWAITING_CLARIFICATION", "Awaiting Clarification"),
                            ("EVIDENCE_VERIFICATION", "Evidence Verification"),
                            ("VALIDATION_COMPLETED", "Validation Completed"),
                            ("RETURNED_FOR_CORRECTION", "Returned for Correction"),
                            ("RESUBMITTED", "Resubmitted"),
                            ("APPROVED", "Approved"),
                            ("CONDITIONALLY_APPROVED", "Conditionally Approved"),
                            ("REJECTED", "Rejected"),
                            ("ESCALATED", "Escalated"),
                            ("DELEGATED", "Delegated"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PENDING_ASSIGNMENT",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED_FOR_CORRECTION", "Returned for Correction"),
                            ("REJECTED", "Rejected"),
                            ("ESCALATED", "Escalated"),
                            ("DELEGATED", "Delegated"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "decision_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decision at"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Decision notes"),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Overall score",
                    ),
                ),
                (
                    "checklist_completed",
                    models.BooleanField(
                        default=False, verbose_name="Checklist completed"
                    ),
                ),
                (
                    "evidence_verified",
                    models.BooleanField(
                        default=False, verbose_name="Evidence verified"
                    ),
                ),
                (
                    "validation_completed",
                    models.BooleanField(
                        default=False, verbose_name="Validation completed"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "primary_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Primary reviewer",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="report_instances.report",
                        verbose_name="Report",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EscalationRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("OVERDUE", "Overdue Review"),
                            ("HIGH_RISK", "High-Risk Report"),
                            ("GOVERNANCE", "Governance Exception"),
                            ("COMPLIANCE", "Compliance Concern"),
                            ("FINANCIAL", "Financial Exception"),
                            ("SAFEGUARDING", "Safeguarding Concern"),
                            ("TECHNICAL", "Technical Dispute"),
                            ("CUSTOM", "Custom Trigger"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Escalation trigger",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Escalation reason")),
                (
                    "escalated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Escalated at"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Resolved"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "escalated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Escalated by",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Escalated to",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Record",
                "verbose_name_plural": "Escalation Records",
                "ordering": ("-escalated_at",),
            },
        ),
        migrations.CreateModel(
            name="DelegationRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(verbose_name="Delegation reason")),
                (
                    "delegated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Delegated at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires at"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "delegated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated by",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated to",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegation Record",
                "verbose_name_plural": "Delegation Records",
                "ordering": ("-delegated_at",),
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Reviewer"),
                            ("SECONDARY", "Secondary Reviewer"),
                            ("TECHNICAL", "Technical Reviewer"),
                            ("FINANCIAL", "Financial Reviewer"),
                            ("MEAL", "MEAL Reviewer"),
                            ("QA", "Quality Assurance Reviewer"),
                            ("COMPLIANCE", "Compliance Reviewer"),
                            ("DIRECTORATE", "Directorate Reviewer"),
                            ("EXECUTIVE", "Executive Reviewer"),
                            ("FINAL_APPROVER", "Final Approver"),
                        ],
                        default="PRIMARY",
                        max_length=30,
                        verbose_name="Reviewer role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned by",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Assignment",
                "verbose_name_plural": "Review Assignments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReviewChecklist",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Default checklist"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_checklists",
                        to="reports.reportcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Checklist",
                "verbose_name_plural": "Review Checklists",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ReviewChecklistItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=300, verbose_name="Label")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Required"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reviews.reviewchecklist",
                        verbose_name="Checklist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Checklist Item",
                "verbose_name_plural": "Review Checklist Items",
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="ReviewChecklistResponse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="reviews.reviewchecklistitem",
                        verbose_name="Checklist item",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_responses",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_item_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Response",
                "verbose_name_plural": "Checklist Responses",
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Comment"),
                            ("SECTION", "Section Comment"),
                            ("FIELD", "Field Comment"),
                            ("RECOMMENDATION", "Recommendation"),
                            ("REQUIRED_CORRECTION", "Required Correction"),
                            ("CLARIFICATION", "Clarification"),
                            ("COMPLIANCE", "Compliance Observation"),
                            ("QUALITY", "Quality Observation"),
                            ("POSITIVE", "Positive Feedback"),
                            ("CONFIDENTIAL", "Confidential Note"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=30,
                        verbose_name="Comment type",
                    ),
                ),
                ("body", models.TextField(verbose_name="Comment")),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="Internal note"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Resolved"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="reports.dynamicfield",
                        verbose_name="Field",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reviews.reviewcomment",
                        verbose_name="Parent comment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_review_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="reports.templatesection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Comment",
                "verbose_name_plural": "Review Comments",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReviewConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("value", models.JSONField(verbose_name="Value")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Configuration",
                "verbose_name_plural": "Review Configurations",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED_FOR_CORRECTION", "Returned for Correction"),
                            ("REJECTED", "Rejected"),
                            ("ESCALATED", "Escalated"),
                            ("DELEGATED", "Delegated"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Decision",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Decision reason")),
                ("conditions", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "decided_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Decided at"),
                ),
                (
                    "signature_data",
                    models.TextField(blank=True, verbose_name="Signature data"),
                ),
                (
                    "signature_type",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Signature type"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Decision",
                "verbose_name_plural": "Review Decisions",
                "ordering": ("-decided_at",),
            },
        ),
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("TYPED", "Typed Signature"),
                            ("HANDWRITTEN", "Handwritten Signature"),
                            ("UPLOADED", "Uploaded Signature Image"),
                            ("ELECTRONIC", "Verified Electronic Signature"),
                            ("STAMP", "Organizational Approval Stamp"),
                        ],
                        max_length=30,
                        verbose_name="Signature type",
                    ),
                ),
                ("signature_data", models.TextField(verbose_name="Signature data")),
                (
                    "signature_hash",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Signature hash"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Signed at"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="Valid")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="reviews.reviewdecision",
                        verbose_name="Decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Signature",
                "verbose_name_plural": "Digital Signatures",
                "ordering": ("-signed_at",),
            },
        ),
        migrations.CreateModel(
            name="SLAConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "review_deadline_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Review deadline (days)"
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Reminder days before deadline"
                    ),
                ),
                (
                    "escalation_days_after",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Escalation days after deadline"
                    ),
                ),
                (
                    "max_extensions",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Max extensions"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_configurations",
                        to="reports.reportcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Configuration",
                "verbose_name_plural": "SLA Configurations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SLAEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DEADLINE_SET", "Deadline Set"),
                            ("REMINDER_SENT", "Reminder Sent"),
                            ("OVERDUE", "Overdue"),
                            ("ESCALATED", "Escalated"),
                            ("EXTENDED", "Extended"),
                            ("MET", "SLA Met"),
                            ("BREACHED", "SLA Breached"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Event date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_events",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "sla_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="reviews.slaconfiguration",
                        verbose_name="SLA configuration",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Event",
                "verbose_name_plural": "SLA Events",
                "ordering": ("-event_date",),
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["status"], name="reviews_rev_status_5966f7_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["report", "status"], name="reviews_rev_report__e9d342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["primary_reviewer", "status"],
                name="reviews_rev_primary_f9d3bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["due_date"], name="reviews_rev_due_dat_b2f8e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["review", "is_active"], name="reviews_rev_review__e5871c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewchecklistresponse",
            constraint=models.UniqueConstraint(
                fields=("review", "item"), name="review_checklist_response_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcomment",
            index=models.Index(
                fields=["review", "comment_type"], name="reviews_rev_review__ef464d_idx"
            ),
        ),
    ]
