# Generated by Django 6.0.8 on 2026-08-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="meetingactionitem",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="meetingdecision",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="meetingminutes",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="Reference",
            ),
        ),
    ]
