# Generated by Django 6.0.8 on 2026-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_alter_calendar_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingparticipant",
            name="participant_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal"),
                    ("EXTERNAL", "External"),
                    ("USER", "User"),
                    ("LEADER", "Leader"),
                    ("MEMBER", "Member"),
                    ("VOLUNTEER", "Volunteer"),
                    ("STAKEHOLDER", "Stakeholder"),
                    ("PARTNER", "Partner"),
                    ("DONOR", "Donor"),
                    ("SPONSOR", "Sponsor"),
                    ("GOVERNMENT", "Government"),
                    ("CONSULTANT", "Consultant"),
                    ("GUEST", "Guest"),
                ],
                default="USER",
                max_length=30,
                verbose_name="Participant type",
            ),
        ),
    ]
