# Generated by Django 5.1 on 2026-07-31 22:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rbac", "0002_seed_rbac_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationLevel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Level",
                "verbose_name_plural": "Organizational Levels",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "identifier",
                    models.CharField(
                        help_text="Stable organizational identifier that never changes.",
                        max_length=50,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Short name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ORGANIZATION", "National Organization"),
                            ("GENERAL_ASSEMBLY", "General Assembly"),
                            ("BOARD_OF_TRUSTEES", "Board of Trustees"),
                            (
                                "NATIONAL_EXECUTIVE_COMMITTEE",
                                "National Executive Committee",
                            ),
                            ("EXECUTIVE_MANAGEMENT", "Executive Management"),
                            ("EXECUTIVE_OFFICE", "Executive Office"),
                            ("DIRECTORATE", "Directorate"),
                            ("DEPARTMENT", "Department"),
                            ("REGION", "Region"),
                            ("DISTRICT", "District"),
                            ("COMMUNITY", "Community"),
                            ("TEAM", "Team"),
                            ("PROGRAM_UNIT", "Program Unit"),
                            ("PROJECT_UNIT", "Project Unit"),
                            ("COMMITTEE", "Committee"),
                            ("WORKING_GROUP", "Working Group"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Unit type",
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Office location"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Contact phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("UNDER_REVIEW", "Under Review"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective date"
                    ),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date established"
                    ),
                ),
                (
                    "access_scope",
                    models.ForeignKey(
                        blank=True,
                        help_text="The RBAC access scope this unit maps onto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_units",
                        to="rbac.accessscope",
                        verbose_name="Access scope",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="organizations.organizationlevel",
                        verbose_name="Organizational level",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Every unit has at most one parent unit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="organizations.organizationunit",
                        verbose_name="Parent unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Responsibilities"),
                ),
                (
                    "required_competencies",
                    models.TextField(blank=True, verbose_name="Required competencies"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("ACTING", "Acting"),
                            ("INTERIM", "Interim"),
                            ("TEMPORARY", "Temporary"),
                            ("VOLUNTEER", "Volunteer Appointment"),
                            ("CONTRACT", "Contract"),
                            ("HONORARY", "Honorary"),
                        ],
                        default="PERMANENT",
                        max_length=30,
                        verbose_name="Appointment type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective date"
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(
                        default=False,
                        help_text="Protected executive positions require elevated authorization to modify.",
                        verbose_name="Protected position",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="organizations.organizationunit",
                        verbose_name="Organizational unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="organizationunit",
            name="unit_head",
            field=models.ForeignKey(
                blank=True,
                help_text="The position that heads this unit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_units",
                to="organizations.position",
                verbose_name="Unit head",
            ),
        ),
        migrations.CreateModel(
            name="ActingAppointment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "effective_from",
                    models.DateField(verbose_name="Effective start date"),
                ),
                ("end_date", models.DateField(verbose_name="End date")),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("ENDED", "Ended"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="organizations/acting/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "acting_officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acting officer",
                    ),
                ),
                (
                    "approval_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approval authority",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "original_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="covered_acting_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Original assignee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_appointments",
                        to="organizations.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acting Appointment",
                "verbose_name_plural": "Acting Appointments",
                "ordering": ("-effective_from", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "appointment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Appointment date",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Effective date",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("ACTING", "Acting"),
                            ("INTERIM", "Interim"),
                            ("TEMPORARY", "Temporary"),
                            ("VOLUNTEER", "Volunteer Appointment"),
                            ("CONTRACT", "Contract"),
                            ("HONORARY", "Honorary"),
                        ],
                        db_index=True,
                        default="PERMANENT",
                        max_length=30,
                        verbose_name="Appointment type",
                    ),
                ),
                (
                    "term_start",
                    models.DateField(blank=True, null=True, verbose_name="Term start"),
                ),
                (
                    "term_end",
                    models.DateField(blank=True, null=True, verbose_name="Term end"),
                ),
                (
                    "renewal_eligible",
                    models.BooleanField(default=False, verbose_name="Renewal eligible"),
                ),
                (
                    "renewal_status",
                    models.CharField(
                        choices=[
                            ("NOT_ELIGIBLE", "Not Eligible"),
                            ("ELIGIBLE", "Eligible"),
                            ("RENEWED", "Renewed"),
                            ("NOT_RENEWED", "Not Renewed"),
                        ],
                        default="NOT_ELIGIBLE",
                        max_length=30,
                        verbose_name="Renewal status",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("ENDED", "Ended"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="organizations/appointments/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "appointed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Appointed by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="organizations.organizationunit",
                        verbose_name="Organizational unit",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organizations.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Assignment",
                "verbose_name_plural": "Position Assignments",
                "ordering": ("-effective_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PositionClassification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Classification",
                "verbose_name_plural": "Position Classifications",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="position",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="organizations.positionclassification",
                verbose_name="Classification",
            ),
        ),
        migrations.CreateModel(
            name="ReportingRelationship",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Primary reporting line"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Effective from",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective to"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_relationships",
                        to="organizations.position",
                        verbose_name="Position",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_relationships",
                        to="organizations.position",
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporting Relationship",
                "verbose_name_plural": "Reporting Relationships",
                "ordering": ("position", "-is_primary", "effective_from"),
            },
        ),
        migrations.CreateModel(
            name="TransferRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("effective_date", models.DateField(verbose_name="Effective date")),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Transfer reason"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="organizations/transfers/",
                        verbose_name="Supporting document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "new_organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organizationunit",
                        verbose_name="New organizational unit",
                    ),
                ),
                (
                    "new_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.position",
                        verbose_name="New position",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
                (
                    "previous_organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organizationunit",
                        verbose_name="Previous organizational unit",
                    ),
                ),
                (
                    "previous_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.position",
                        verbose_name="Previous position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Record",
                "verbose_name_plural": "Transfer Records",
                "ordering": ("-effective_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "vacancy_reason",
                    models.TextField(blank=True, verbose_name="Vacancy reason"),
                ),
                (
                    "date_vacant",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date vacant",
                    ),
                ),
                (
                    "recruitment_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_RECRUITMENT", "In Recruitment"),
                            ("ON_HOLD", "On Hold"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=30,
                        verbose_name="Recruitment status",
                    ),
                ),
                (
                    "expected_appointment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected appointment date"
                    ),
                ),
                (
                    "acting_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="covering_vacancies",
                        to="organizations.actingappointment",
                        verbose_name="Acting appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="organizations.organizationunit",
                        verbose_name="Organizational unit",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy",
                        to="organizations.position",
                        verbose_name="Position",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
                "ordering": ("-date_vacant", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="OrganizationAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Entity ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("ACTIVATED", "Activated"),
                            ("DEACTIVATED", "Deactivated"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("PARENT_CHANGED", "Parent Changed"),
                            ("REPORTING_LINE_CHANGED", "Reporting Line Changed"),
                            ("APPOINTED", "Appointed"),
                            ("APPOINTMENT_ENDED", "Appointment Ended"),
                            ("APPOINTMENT_REVOKED", "Appointment Revoked"),
                            ("ACTING_APPOINTED", "Acting Appointed"),
                            ("ACTING_ENDED", "Acting Ended"),
                            ("VACANCY_OPENED", "Vacancy Opened"),
                            ("VACANCY_FILLED", "Vacancy Filled"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Action",
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Audit Record",
                "verbose_name_plural": "Organization Audit Records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="organizatio_entity__70b3fd_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(
                fields=["status", "unit_type"], name="organizatio_status_008c48_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("position",),
                name="unique_active_assignment_per_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("person",),
                name="unique_active_assignment_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportingrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("position", "supervisor"),
                name="unique_active_reporting_relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportingrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("position",),
                name="unique_primary_reporting_line_per_position",
            ),
        ),
    ]
