# Generated by Django 5.1 on 2026-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationunit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("GENERAL_ASSEMBLY", "General Assembly"),
                    (
                        "BOARD_OF_DIRECTORS_TRUSTEES",
                        "Board of Directors / Board of Trustees",
                    ),
                    ("NATIONAL_EXECUTIVE_COMMITTEE", "National Executive Committee"),
                    ("EXECUTIVE_MANAGEMENT", "Executive Management"),
                    ("EXECUTIVE_OFFICE", "Executive Office"),
                    ("DIRECTORATE", "Directorate"),
                    ("DEPARTMENT", "Department"),
                    (
                        "PROGRAM_TECHNICAL_MANAGEMENT",
                        "Program and Technical Management",
                    ),
                    ("REGION", "Region"),
                    ("DISTRICT", "District"),
                    ("COMMUNITY", "Community"),
                    ("TEAM", "Team"),
                    ("VOLUNTEER_MEMBER", "Volunteers / Members"),
                    ("PROGRAM_UNIT", "Program Unit"),
                    ("PROJECT_UNIT", "Project Unit"),
                    ("COMMITTEE", "Committee"),
                    ("WORKING_GROUP", "Working Group"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Unit type",
            ),
        ),
    ]
