# Generated by Django 5.0.7 on 2026-08-09 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_organizations_permissions"),
        ("rbac", "0017_seed_notification_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap Icons class name.",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap color token.",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Category",
                "verbose_name_plural": "Notification Categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("NEVER", "Never"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period start")),
                ("period_end", models.DateTimeField(verbose_name="Period end")),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Summary"),
                ),
                (
                    "notification_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Notification count"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "sent_via",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sent via"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Digest",
                "verbose_name_plural": "Notification Digests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. report.submitted, meeting.scheduled, action.overdue",
                        max_length=100,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "source_app",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Source application"
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source model"
                    ),
                ),
                (
                    "source_object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Source object ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Safe, non-sensitive event context used for template rendering.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional key used to collapse repeated identical events.",
                        max_length=255,
                        verbose_name="Deduplication key",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Processed"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed at"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_events",
                        to="organizations.organizationunit",
                        verbose_name="Organization unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Event",
                "verbose_name_plural": "Notification Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="In-app enabled"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=False, verbose_name="Email enabled"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS enabled"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=False, verbose_name="Push enabled"),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("NEVER", "Never"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                        verbose_name="Digest frequency",
                    ),
                ),
                (
                    "digest_timezone",
                    models.CharField(
                        default="Africa/Lusaka",
                        max_length=64,
                        verbose_name="Digest timezone",
                    ),
                ),
                (
                    "digest_channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Digest channels"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Quiet hours enabled"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Quiet hours start"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Quiet hours end"
                    ),
                ),
                (
                    "quiet_hours_policy",
                    models.CharField(
                        choices=[
                            ("RESPECT", "Respect Quiet Hours"),
                            ("OVERRIDE", "Override for Critical"),
                            ("IGNORE", "Ignore Quiet Hours"),
                        ],
                        default="RESPECT",
                        max_length=20,
                        verbose_name="Quiet hours policy",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Lusaka", max_length=64, verbose_name="Timezone"
                    ),
                ),
                (
                    "category_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of category to {in_app, email, sms, push} booleans.",
                        verbose_name="Category preferences",
                    ),
                ),
                (
                    "reminder_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                        verbose_name="Reminder frequency",
                    ),
                ),
                (
                    "marketing_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Marketing/announcements enabled"
                    ),
                ),
                (
                    "mandatory_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category codes that may not be disabled by the user.",
                        verbose_name="Mandatory categories",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SYSTEM", "System"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SECURITY", "Security"),
                            ("GOVERNANCE", "Governance"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEER", "Volunteer"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("STAKEHOLDER", "Stakeholder"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("REPORTS", "Reports"),
                            ("REVIEW_APPROVAL", "Review and Approval"),
                            ("DOCUMENTS", "Documents"),
                            ("ORGANIZATIONAL_REGISTERS", "Organizational Registers"),
                            ("CALENDAR", "Calendar"),
                            ("MEETINGS", "Meetings"),
                            ("TRAINING", "Training"),
                            ("FINANCE", "Finance"),
                            ("PARTNERSHIP", "Partnership"),
                            ("RISK_COMPLIANCE", "Risk and Compliance"),
                            ("SAFEGUARDING", "Safeguarding"),
                            ("DEADLINES", "Deadlines"),
                            ("ANNOUNCEMENTS", "Announcements"),
                        ],
                        default="GENERAL",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        default="IN_APP",
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject template"
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=255, verbose_name="Title template"),
                ),
                ("message_template", models.TextField(verbose_name="Message template")),
                (
                    "short_message_template",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Short message template",
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Action label"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "required_variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Required variables"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="Version"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_templates",
                        to="organizations.organizationunit",
                        verbose_name="Organization scope",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Event type"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SYSTEM", "System"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SECURITY", "Security"),
                            ("GOVERNANCE", "Governance"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEER", "Volunteer"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("STAKEHOLDER", "Stakeholder"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("REPORTS", "Reports"),
                            ("REVIEW_APPROVAL", "Review and Approval"),
                            ("DOCUMENTS", "Documents"),
                            ("ORGANIZATIONAL_REGISTERS", "Organizational Registers"),
                            ("CALENDAR", "Calendar"),
                            ("MEETINGS", "Meetings"),
                            ("TRAINING", "Training"),
                            ("FINANCE", "Finance"),
                            ("PARTNERSHIP", "Partnership"),
                            ("RISK_COMPLIANCE", "Risk and Compliance"),
                            ("SAFEGUARDING", "Safeguarding"),
                            ("DEADLINES", "Deadlines"),
                            ("ANNOUNCEMENTS", "Announcements"),
                        ],
                        default="GENERAL",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFORMATION", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ACTION_REQUIRED", "Action Required"),
                            ("REMINDER", "Reminder"),
                            ("DEADLINE", "Deadline"),
                            ("OVERDUE", "Overdue"),
                            ("APPROVAL_REQUIRED", "Approval Required"),
                            ("REVIEW_REQUIRED", "Review Required"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                            ("ASSIGNMENT", "Assignment"),
                            ("INVITATION", "Invitation"),
                            ("MENTION", "Mention"),
                            ("COMMENT", "Comment"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("ESCALATION", "Escalation"),
                        ],
                        default="INFORMATION",
                        max_length=50,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(blank=True, default=list, verbose_name="Channels"),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        blank=True,
                        default="USER",
                        max_length=50,
                        verbose_name="Recipient type",
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Delay (minutes)"
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=False, verbose_name="Reminder enabled"),
                ),
                (
                    "reminder_offsets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of offset hours, e.g. [-168, -72, -24, -2, 0, 24, 72].",
                        verbose_name="Reminder offsets",
                    ),
                ),
                (
                    "escalation_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Escalation enabled"
                    ),
                ),
                (
                    "escalation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("SUPERVISOR", "Supervisor"),
                            ("MANAGER", "Manager"),
                            ("DIRECTOR", "Director"),
                            ("EXECUTIVE", "Executive"),
                            ("BOARD", "Board"),
                        ],
                        max_length=30,
                        verbose_name="Escalation level",
                    ),
                ),
                (
                    "escalation_after_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Escalation after hours"
                    ),
                ),
                (
                    "digest_eligible",
                    models.BooleanField(default=False, verbose_name="Digest eligible"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_rules",
                        to="organizations.organizationunit",
                        verbose_name="Organization scope",
                    ),
                ),
                (
                    "recipient_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_rules",
                        to="rbac.role",
                        verbose_name="Role recipient",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_rules_specific",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Specific recipient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="notifications.notificationtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Rule",
                "verbose_name_plural": "Notification Rules",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Archived at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        unique=True,
                        verbose_name="Notification reference",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SYSTEM", "System"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SECURITY", "Security"),
                            ("GOVERNANCE", "Governance"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEER", "Volunteer"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("STAKEHOLDER", "Stakeholder"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("REPORTS", "Reports"),
                            ("REVIEW_APPROVAL", "Review and Approval"),
                            ("DOCUMENTS", "Documents"),
                            ("ORGANIZATIONAL_REGISTERS", "Organizational Registers"),
                            ("CALENDAR", "Calendar"),
                            ("MEETINGS", "Meetings"),
                            ("TRAINING", "Training"),
                            ("FINANCE", "Finance"),
                            ("PARTNERSHIP", "Partnership"),
                            ("RISK_COMPLIANCE", "Risk and Compliance"),
                            ("SAFEGUARDING", "Safeguarding"),
                            ("DEADLINES", "Deadlines"),
                            ("ANNOUNCEMENTS", "Announcements"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFORMATION", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ACTION_REQUIRED", "Action Required"),
                            ("REMINDER", "Reminder"),
                            ("DEADLINE", "Deadline"),
                            ("OVERDUE", "Overdue"),
                            ("APPROVAL_REQUIRED", "Approval Required"),
                            ("REVIEW_REQUIRED", "Review Required"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                            ("ASSIGNMENT", "Assignment"),
                            ("INVITATION", "Invitation"),
                            ("MENTION", "Mention"),
                            ("COMMENT", "Comment"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("ESCALATION", "Escalation"),
                        ],
                        db_index=True,
                        default="INFORMATION",
                        max_length=50,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "short_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Short message"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCHEDULED", "Scheduled"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("PARTIALLY_DELIVERED", "Partially Delivered"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "read_status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("READ", "Read"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        db_index=True,
                        default="UNREAD",
                        max_length=20,
                        verbose_name="Read status",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "acknowledgement_required",
                    models.BooleanField(
                        default=False, verbose_name="Acknowledgement required"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged at"
                    ),
                ),
                (
                    "source_app",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Source application",
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source model"
                    ),
                ),
                (
                    "source_object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Source object ID",
                    ),
                ),
                (
                    "source_object_reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Source reference"
                    ),
                ),
                (
                    "deep_link",
                    models.CharField(
                        blank=True,
                        help_text="Internal validated URL or named-route for navigation.",
                        max_length=500,
                        verbose_name="Deep link",
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Action label"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Scheduled at",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "expiry_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Deduplication key",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "is_digest_eligible",
                    models.BooleanField(default=False, verbose_name="Digest eligible"),
                ),
                (
                    "digest_sent",
                    models.BooleanField(
                        default=False, verbose_name="Included in digest"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acknowledged by",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_acted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="organizations.organizationunit",
                        verbose_name="Organization unit",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationevent",
                        verbose_name="Source event",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SystemAnnouncement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        unique=True,
                        verbose_name="Announcement reference",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION_WIDE", "Organization-wide"),
                            ("DIRECTORATE", "Directorate"),
                            ("REGIONAL", "Regional"),
                            ("DISTRICT", "District"),
                            ("COMMUNITY", "Community"),
                            ("TEAM", "Team"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("EVENT", "Event"),
                            ("TRAINING", "Training"),
                            ("EMERGENCY", "Emergency Notice"),
                            ("POLICY", "Policy Notice"),
                            ("MAINTENANCE", "Maintenance Notice"),
                        ],
                        default="ORGANIZATION_WIDE",
                        max_length=30,
                        verbose_name="Announcement type",
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("EVERYONE", "Everyone"),
                            ("SPECIFIC_ROLES", "Specific Roles"),
                            ("ORGANIZATION_UNITS", "Organization Units"),
                            ("DIRECTORATES", "Directorates"),
                            ("REGIONS", "Regions"),
                            ("DISTRICTS", "Districts"),
                            ("PROGRAMS", "Programs"),
                            ("PROJECTS", "Projects"),
                        ],
                        default="EVERYONE",
                        max_length=30,
                        verbose_name="Audience",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SYSTEM", "System"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SECURITY", "Security"),
                            ("GOVERNANCE", "Governance"),
                            ("LEADERSHIP", "Leadership"),
                            ("MEMBERSHIP", "Membership"),
                            ("VOLUNTEER", "Volunteer"),
                            ("BENEFICIARY", "Beneficiary"),
                            ("STAKEHOLDER", "Stakeholder"),
                            ("PROGRAM", "Program"),
                            ("PROJECT", "Project"),
                            ("MEAL", "MEAL"),
                            ("REPORTS", "Reports"),
                            ("REVIEW_APPROVAL", "Review and Approval"),
                            ("DOCUMENTS", "Documents"),
                            ("ORGANIZATIONAL_REGISTERS", "Organizational Registers"),
                            ("CALENDAR", "Calendar"),
                            ("MEETINGS", "Meetings"),
                            ("TRAINING", "Training"),
                            ("FINANCE", "Finance"),
                            ("PARTNERSHIP", "Partnership"),
                            ("RISK_COMPLIANCE", "Risk and Compliance"),
                            ("SAFEGUARDING", "Safeguarding"),
                            ("DEADLINES", "Deadlines"),
                            ("ANNOUNCEMENTS", "Announcements"),
                        ],
                        default="ANNOUNCEMENTS",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Publish at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published at"
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(default=True, verbose_name="Dismissible"),
                ),
                (
                    "acknowledgement_required",
                    models.BooleanField(
                        default=False, verbose_name="Acknowledgement required"
                    ),
                ),
                (
                    "deep_link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Deep link"
                    ),
                ),
                (
                    "audience_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="rbac.role",
                        verbose_name="Audience roles",
                    ),
                ),
                (
                    "audience_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="organizations.organizationunit",
                        verbose_name="Audience organization units",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_announcements",
                        to="organizations.organizationunit",
                        verbose_name="Organization scope",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Announcement",
                "verbose_name_plural": "System Announcements",
                "ordering": ("-publish_at",),
            },
        ),
        migrations.CreateModel(
            name="AnnouncementDismissal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Dismissed at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissals",
                        to="notifications.systemannouncement",
                        verbose_name="Announcement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Dismissal",
                "verbose_name_plural": "Announcement Dismissals",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementDelivery",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered at"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dismissed at"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged at"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.systemannouncement",
                        verbose_name="Announcement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Delivery",
                "verbose_name_plural": "Announcement Deliveries",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.systemannouncement",),
        ),
        migrations.CreateModel(
            name="NotificationAuditRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Target type"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Target ID"
                    ),
                ),
                (
                    "from_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="From data"
                    ),
                ),
                (
                    "to_data",
                    models.JSONField(blank=True, default=dict, verbose_name="To data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Audit Record",
                "verbose_name_plural": "Notification Audit Records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="notificatio_action_0af365_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provider"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Attempt number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Queued at"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered at"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Failed at"
                    ),
                ),
                (
                    "failure_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Failure category"
                    ),
                ),
                (
                    "safe_error_summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Safe error summary"
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provider reference"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry count"),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Next retry at",
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last error at"
                    ),
                ),
                (
                    "payload_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Payload snapshot"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["notification", "channel"],
                        name="notificatio_notific_7707f8_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="notificatio_status_e5e8a7_idx",
                    ),
                    models.Index(
                        fields=["channel", "status", "created_at"],
                        name="notificatio_channel_1e1dba_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["event_type", "source_app", "source_model", "source_object_id"],
                name="notificatio_event_t_646c46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["deduplication_key", "processed"],
                name="notificatio_dedupli_c63afd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationevent",
            constraint=models.UniqueConstraint(
                fields=(
                    "event_type",
                    "source_app",
                    "source_model",
                    "source_object_id",
                    "deduplication_key",
                ),
                name="uniq_notification_event_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationrule",
            constraint=models.UniqueConstraint(
                fields=("event_type", "name"), name="uniq_notification_rule_event_name"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_status", "created_at"],
                name="notificatio_recipie_678648_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "status", "created_at"],
                name="notificatio_recipie_3f77fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "scheduled_at"], name="notificatio_status_a9c93f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category", "created_at"], name="notificatio_categor_e0e064_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "created_at"], name="notificatio_priorit_f7c359_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["source_app", "source_model", "source_object_id"],
                name="notificatio_source__d984a3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementdismissal",
            constraint=models.UniqueConstraint(
                fields=("announcement", "user"), name="uniq_announcement_dismissal"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementdelivery",
            constraint=models.UniqueConstraint(
                fields=("announcement", "recipient"), name="uniq_announcement_recipient"
            ),
        ),
    ]
