# Generated by Django 5.1 on 2026-08-28 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("locations", "0001_initial"),
        ("organizations", "0002_seed_organizations_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="constituency_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_profiles",
                to="locations.constituency",
                verbose_name="Constituency",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_profiles",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_profiles",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_profiles",
                to="locations.ward",
                verbose_name="Ward",
            ),
        ),
        migrations.AddField(
            model_name="beneficiarygroup",
            name="district_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_groups",
                to="locations.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="beneficiarygroup",
            name="province_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_groups",
                to="locations.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="beneficiarygroup",
            name="ward_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_groups",
                to="locations.ward",
                verbose_name="Ward / Community",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(
                fields=["province_location", "district_location"],
                name="beneficiari_provinc_301070_idx",
            ),
        ),
    ]
